### ISSUE TITLE
python-ldap and python-retrying are dependencies for user management tool

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#100]
The user management tool (obol) needs python-ldap and python-retrying  to work. These should be added to the startup scripts for the login node and the containers.

**Comment by abhimukh** [comment]
Could not assign multiple people for this.

**Comment by hansthen** [comment]
Obol only needs to work inside the login node. Reassigning.

**Comment by themisa** [comment]
obol works. Fixed in * r3
ae94b4a
