### ISSUE TITLE
login node: root should have passwordless access to containers

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#101]
On login node creation, root should be set up such that it has passwordless access to all nodes/containers associated with the virtual login node.

**Comment by abhimukh** [comment]
@themisa Do we need really need this?

**Comment by themisa** [comment]
@hansthen should root have passworldess access to containers of their virtual cluster, or only the users?

**Comment by hansthen** [comment]
Only the users?

**Comment by themisa** [comment]
Ok, closing this. It is not necessary for root to have passwordless access to containers. Only the users of the cluster, who will be submitting jobs should have passwordless access.

**Comment by brunopereira81** [comment]
So, lets say that a user submitted a job and that process left some processes behind, who kills them?

The user will not really care (or should be allowed to handle these kind of situations), not to mention on how you are to detect in a cluster without root access to the whole system.

Would it not just be simpler to add root key access to the nodes and to the containers?
