### ISSUE TITLE
Dashboard: hpc_overview gives an error for admin user

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#102]
Software: Trinity * r3
74c8094
Component: dashboard
Use Case: Not applicable

When logged in to the dashboard as admin user there are menu items project-->High Performance Computing-->Overview and Admin-->HPCPanel-->Overview. Clicking these options will trigger an error message.

**Comment by abhimukh** [comment]
The Trinity API server was not running on the openstack node. Now this works.

**Comment by themisa** [comment]
works.
