### ISSUE TITLE
Dashboard: hpc_overview gives an error for a tenant user

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#103]
Version: r3 74c8094
Component: Dashboard
Use Case: 3.1

When logged in as tenant user, menu item Project --> High Performance --> Computing --> Overview http://node003/dashboard/project/hpc_overview/ raises an error (Unexpected Error).

**Comment by abhimukh** [comment]
The trinity API server has had not been started/ was stopped on the openstack node. Now overview works.

**Comment by themisa** [comment]
resolved
