### ISSUE TITLE
Login node creation: symlink from /etc/slurm/ to /cluster/etc/slurm is missing

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#105]
Software: Trinity * r3
74c8094
Component: Login node creation
Use Case: 3.2

Symlinks from /etc/slurm to /cluster/etc/slurm is missing. Instead, there are symlinks to individual config files inside that directory. 

[root@a14 home]# ls -ltr /etc/slurm/
total 24
-rwxr-xr-x. 1 root root  820 Oct 13 14:56 slurm.epilog.clean
-rw-r--r--. 1 root root  739 Oct 13 14:56 slurmdbd.conf.example
-rw-r--r--. 1 root root 1928 Oct 13 14:56 slurm.conf.example
-rwxr-xr-x. 1 root root 3254 Oct 13 14:56 cgroup.release_common.example
-rw-r--r--. 1 root root  258 Oct 13 14:56 cgroup.conf.example
-rw-r--r--. 1 root root   67 Oct 13 14:56 cgroup_allowed_devices_file.conf.example
drwxr-xr-x. 2 root root   70 Mar 12 14:54 cgroup
lrwxrwxrwx. 1 root root   34 Mar 12 14:55 slurm-user.conf -> /cluster/etc/slurm/slurm-user.conf
lrwxrwxrwx. 1 root root   29 Mar 12 14:55 slurm.conf -> /cluster/etc/slurm/slurm.conf
lrwxrwxrwx. 1 root root   35 Mar 12 14:55 slurm-nodes.conf -> /cluster/etc/slurm/slurm-nodes.conf

**Comment by themisa** [comment]
[root@login ~]# ls -ltr /etc/slurm
lrwxrwxrwx. 1 root root 18 17 mrt 14:03 /etc/slurm -> /cluster/etc/slurm

NOTE: fixed in r3_login branch

**Comment by themisa** [comment]
lrwxrwxrwx.  1 root  root       18 Mar 19 13:05 slurm -> /cluster/etc/slurm (blinking red)

not fixed

**Comment by themisa** [comment]
lrwxrwxrwx.  1 root  root       18 Mar 20 14:03 slurm -> /cluster/etc/slurm

fixed
