### ISSUE TITLE
Login node creation: DNS resolution fails

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#106]
Software: Trinity * r3
74c8094
Component: Login node creation
Use Case: 3.2

[root@a14 ~]# ping c001
ping: unknown host c001

**Comment by abhimukh** [comment]
This has been fixed

**Comment by themisa** [comment]
Fixed: 
* r3
ae94b4a

[root@login ~]# host c002
c002.vc-a has address 172.16.0.2
