### ISSUE TITLE
Login node creation: missing `host` command

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#107]
Software: Trinity * r3
74c8094
Component: Login node creation
Use Case: 3.2

[root@a14 ~]# host c001 localhost
-bash: host: command not found

**Comment by themisa** [comment]
fixed in r3_login 
C[root@login ~]# host c001.vc-a
c001.vc-a has address 172.16.0.1

Needs to be merged to r3

**Comment by themisa** [comment]
fixed
