### ISSUE TITLE
Controller should have a route table entry for every virtual cluster

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#109]
The containers and the login node in a virtual cluster depend on the controller for routing. Thus the controller should have an entry in its routing table for each virtual cluster.

**Comment by hansthen** [comment]
@abhimukh Do you remember the content of the routing table entry we created?

**Comment by hansthen** [comment]
See here: https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s1-networkscripts-static-routes.html

ip route add 172.16.0.0/12 dev eno2

**Comment by themisa** [comment]
[root@controller ~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         master.cluster  0.0.0.0         UG    1024   0        0 eno1
10.0.0.0        0.0.0.0         255.255.0.0     U     0      0        0 docker0
10.141.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
10.148.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
172.16.0.0      0.0.0.0         255.240.0.0     U     0      0        0 eno2
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eno1

* r3
7cb356e
