### ISSUE TITLE
User-management tool not available on any shared directory

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#110]
The user-management tool is not available on any of the directory exported from the xCAT controller

**Comment by hansthen** [comment]
Workaround: copy the files yourself to any location you like.

**Comment by hansthen** [comment]
Is now under controller:/trinity/login/obol.

**Comment by abhimukh** [comment]
We need either a setup tool/script/instrutctions for obol

**Comment by themisa** [comment]
obol now available in a shared directory.

 [root@login home]# ls /trinity/login/obol/
