### ISSUE TITLE
trinity images: need bridge-utils

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#111]
trinity images need bridge-utils

**Comment by hansthen** [comment]
To test: `psh node001 brctl show`

**Comment by themisa** [comment]
root@controller ~]# psh node001 brctl show
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /opt/xcat/bin/psh line 56.
node001: bridge name    bridge id               STP enabled     interfaces

Fixed: * r3
ae94b4a
