### ISSUE TITLE
controller installation: munge key not present for default virtual cluster

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#112]
version: * r3 4647552

On first installation there is no munge key present for the first virtual cluster. 

As a workaround: create a key like this:
[root@controller ~]# dd if=/dev/urandom bs=1 count=1024 >/cluster/vc-a/etc/munge/munge.key
[root@controller ~]# chmod 400 /cluster/vc-a/etc/munge/munge.key

**Comment by themisa** [comment]
* r3
7cb356e

Fixed
