### ISSUE TITLE
No host command on the OpenStack node

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#113]
**Software:**
* r3
4647552

**Component:**
OpenStack node

**Hardware:**
master/controller02/node003

**Bug description:**
There is no host command on the OpenStack node.
[root@openstack ~(keystone_demo)]# host controller
bash: host: command not found

**Comment by themisa** [comment]
[root@openstack munge(keystone_admin)]# host controller
controller.cluster has address 10.141.255.254
* r3
7cb356e
