### ISSUE TITLE
No trinity version file on the OpenStack node

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#114]
**Software:**
* r3
4647552
__Note: I took the version number from the xCAT controller__

**Component:**
OpenStack node

**Hardware:**
master/controller02/node003

**Bug description:**
The file /trinity/version is not present on the OpenStack node.
[root@openstack ~(keystone_demo)]# cat /trinity/version
cat: /trinity/version: No such file or directory

**Comment by hansthen** [comment]
Duplicate of #115.
