### ISSUE TITLE
openstack installation: need /trinity  and /cluster  mounted

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#115]
**Software:*** r3
4647552
**Component:** openstack installation
**Hardware:** node003, poweredge
**Test case:**
**Bug description:**
need /trinity and /cluster mounted on openstack node (for dashboard installation etc)

**Comment by hansthen** [comment]
To test: after openstack installation `psh node003 ls /cluster` and `psh node003 ls /trinity`

**Comment by themisa** [comment]
Still not mounted, 

node003: ls: cannot access /cluster: No such file or directory
node003: ls: cannot access /trinity: No such file or directory

version
* r3
7cb356e

**Comment by themisa** [comment]
5cead59
fixed
