### ISSUE TITLE
SLURM conf file points to incorrect user and node files

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#116]
**Software:**
* r3
4647552

**Component:**
slurm.conf

**Hardware:**
master/controller02/node003/virtual_login_node

**Bug description:**

[root@login ~]# service slurm status
scontrol: error: s_p_parse_file: unable to status file "/cluster/etc/slurm-nodes.conf"

[root@login ~]# cat /etc/slurm/slurm.conf
\# COMPUTE NODES
Include __/cluster/etc/slurm-nodes.conf__
\# Put default values here. Tenants can override these values
SwitchType=switch/none
TaskPlugin=task/none
MpiDefault=none
ReturnToService=2

Include __/cluster/etc/slurm-user.conf__

...

**Comment by hansthen** [comment]
Should point to /etc/slurm/slurm-nodes.conf and mm slurm-user.conf.

**Comment by themisa** [comment]
[root@login ~]# cat /etc/slurm/slurm.conf
# COMPUTE NODES
Include /etc/slurm/slurm-nodes.conf
# Put default values here. Tenants can override these values
SwitchType=switch/none
TaskPlugin=task/none
MpiDefault=none
ReturnToService=2

Include /etc/slurm/slurm-user.conf

# Put controlled values here. Tenants cannot override these values.  
ControlMachine=login
AuthType=auth/munge

* r3
ae94b4a
