### ISSUE TITLE
trinity dashboard: formatting inconsistent

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#121]
The trinity dashboard is "unstable". For the same installation procedure, sometimes the formatting is not correct

**Comment by abhimukh** [comment]
Manual hack for now:
     cd /usr/share/openstack-dashboard/static/dashboard/img
     cp logo.png logo.png.trinity
     cp logo-splash.png logo-splash.png.trinity
     cp logo.png.orig logo.png
     cp logo-splash.png.orig logo-splash.png
     service httpd restart

This will replace the Trinity logo with the OpenStack logo. But the rest should work.

**Comment by themisa** [comment]
the workaround works, but assigning back to @abhimukh for future permanent fix

**Comment by abhimukh** [comment]
Modifed the setup script for the dashboard to remove the trinity logos 
 9ea66b58c661c1bd7111553a18991cc0c764dfaf

**Comment by themisa** [comment]
Fixed in 
* r3
ae94b4a
