### ISSUE TITLE
xcat: virtual login node defs should be in a "login" group, not virtual cluster group

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#124]
Right now login-a is created in a group vc-a ( default virtual login node associated with default virtual cluster)

This is confusing for slurm, as it treated login-a as a node associated with the virtual cluster vc-a

**Comment by hansthen** [comment]
I am way ahead of you. Was fixed before you opened the bug. 301e47

**Comment by themisa** [comment]
[root@controller ~]# tabdump nodelist
#node,groups,status,statustime,appstatus,appstatustime,primarysn,hidden,updatestatus,updatestatustime,zonename,comments,disable
"controller","xcat",,,,,,,,,,,
"switch","xcat",,,,,,,,,,,
"login-a","login",,,,,,,,,,,

fixed in * r3
5cead59
