### ISSUE TITLE
Containers: force-reload containers does not "recreate" the containers. 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#126]
When we need to restart slurm (if we want to for example change a slurm config file). we need to restart the containers on each node.

This should be automated?

Manual procedure on each node: 
[root@node001 ~]# cp /etc/init.d/trinity ./
[root@node001 ~]# ./trinity restart
Stopping trinity trinity
Starting Trinity
Cannot find device "docker0"
bridge docker0 doesn't exist; can't delete it
c001.vc-a has address 172.16.0.1
trinity

**Comment by brunopereira81** [comment]
This is not necessary. For slurm you can use 'scontrol reconfigure' to
reload any changes done to the configuration file.

**Comment by themisa** [comment]
Docker should be restarted, not just trinity.

**Comment by hansthen** [comment]
No need to restart the whole of docker. However, when a node moves to a different virtual cluster, you will need to recreate the container. Otherwise, the container will keep running, but including all the volumes and networking configuration for the previous virtual cluster.

To recreate the container, you can perform the following:

docker stop trinity; docker rm trinity; service trinity restart

In 2506c8e0 I reimplemented the force-reload method, which will do all of this for you.

**Comment by themisa** [comment]
[root@node001 ~]# service trinity force-reload 
                                                           [  OK  ]
[root@node001 ~]# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS               NAMES
7cff6318770c        controller:5050/trinity:latest   "/usr/bin/supervisor   20 hours ago        Up 5 seconds                            trinity             



docker stop trinity; docker rm trinity; service trinity restart --> manually it works:
[root@node001 ~]# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS               NAMES
7fb50082855c        controller:5050/trinity:latest   "/usr/bin/supervisor   5 seconds ago       Up 5 seconds                            trinity             


BUT: scripted, it seems to only restart trinity, not remove

**Comment by hansthen** [comment]
@themisa 

Next time this happens, can you give the output of journalctl -xn etc?

Also it would help if you copied /etc/init.d/trinity and run it as a real script (instead of inside systemd). Systemd swallows some output that is helpful during debugging.

**Comment by themisa** [comment]
[root@node001 ~]# service trinity force-reload
                                                           [  OK  ]
[root@node001 ~]# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS               NAMES
ab7ae59590c0        controller:5050/trinity:latest   "/usr/bin/supervisor   3 hours ago         Up 6 seconds                            trinity             
[root@node001 ~]# journalctl -xn 
-- Logs begin at Wed 2015-03-25 12:52:36 CET, end at Wed 2015-03-25 15:48:51 CET. --
Mar 25 15:48:45 node001.cluster systemd[1]: Started docker container ab7ae59590c00889e7c6ae1e0d442ef2c53637360fcec261c20e03f5db096410.
-- Subject: Unit docker-ab7ae59590c00889e7c6ae1e0d442ef2c53637360fcec261c20e03f5db096410.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker-ab7ae59590c00889e7c6ae1e0d442ef2c53637360fcec261c20e03f5db096410.scope has finished starting up.
-- 
-- The start-up result is done.
Mar 25 15:48:45 node001.cluster docker[1085]: [63811cd9] -job start(trinity) = OK (0)
Mar 25 15:48:45 node001.cluster trinity[3497]: trinity
Mar 25 15:48:45 node001.cluster docker[1085]: [info] GET /v1.15/containers/trinity/json
Mar 25 15:48:45 node001.cluster docker[1085]: [63811cd9] +job container_inspect(trinity)
Mar 25 15:48:45 node001.cluster docker[1085]: [63811cd9] -job container_inspect(trinity) = OK (0)
Mar 25 15:48:45 node001.cluster systemd[1]: Reloaded LSB: start and stop trinity.
-- Subject: Unit trinity.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit trinity.service has finished reloading its configuration
-- 
-- The result is done.
Mar 25 15:48:51 node001.cluster docker[1085]: [info] GET /v1.15/containers/json
Mar 25 15:48:51 node001.cluster docker[1085]: [63811cd9] +job containers()
Mar 25 15:48:51 node001.cluster docker[1085]: [63811cd9] -job containers() = OK (0)

**Comment by themisa** [comment]
[root@node001 ~]# sh trinity force-reload
trinity
trinity
Stopping trinity Error response from daemon: No such container: trinity
2015/03/25 15:51:02 Error: failed to stop one or more containers
Starting Trinity
Cannot find device "docker0"
bridge docker0 doesn't exist; can't delete it
Host c001.vc-a not found: 3(NXDOMAIN)
c001.vc-b has address 172.17.0.1
Error: No such image or container: trinity
0d2e691aa1a036641c1cf222c45209170c6f99798e022ac5dc588b49375177cb

**Comment by themisa** [comment]
Note: i changed the title of the issue, since it boiled down to service force-reload trinity not behaving as expected.

The issue is fixed in * r3
feda38f 
(see also #131 )
