### ISSUE TITLE
user management on login nodes: add path to executable

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#127]
Right now, when a tenant created a login node, they need to be able to add users using obol. It would be nice for the command to be in their path.

[root@login obol]# pwd
/trinity/login/obol

**Comment by abhimukh** [comment]
there needs to be a setup script for the tool, or obol and ldapuser.py needs to be merged.

**Comment by hansthen** [comment]
I merged obol and ldapuser. It is now a single script called obol.

**Comment by abhimukh** [comment]
Now obol should be in the path on the login node
172aece6f6cab52e6dbc646197116502ea58b5c3

**Comment by themisa** [comment]
Fixed in * r3
feda38f
