### ISSUE TITLE
code compilation: modules point to the wrong directory

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#128]
Need to streamline programming environment in Trinity.

For example:

Currently Loaded Modulefiles:
  1) gcc/4.9.1                     2) mvapich2/gcc/64/qlogic/2.1a

[root@login C]# mpicc hello.c
/trinity/clustervision/apps/mvapich2/gcc/64/qlogic/2.1a/bin/mpicc: line 274: /cm/shared/clustervision/apps/gcc/4.9.1/bin/gcc: No such file or directory

**Comment by linuxstudio** [comment]
Created an example openmpi .rpm package with relocation in /trinity/clustervision/apps.
This is documented in a doc that was shared with the dev team.
By analogy the same can be done with other compiled packages
