### ISSUE TITLE
Trinity container: unable to do (passwordless) login from login node to container

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#129]
**Software:*** r3
5cead59

**Component:** trinity initialization/container
**Hardware:** node002 (SM)
**Test case:** 5.1.1 Users have passwordless access to containers
**Bug description:**
Users belonging to a virtual cluster do not have ssh access to containers in their virtual cluster, since after restarting the containers the appropriate cluster directory is not mounted on the containers. (the users don't "exist" on the containers associated with their virtual cluster)
**Steps to reproduce:**
From openstack node:
[root@login /]# ssh -Y john@login-b.vc-b
john@login-b.vc-b's password: 
Last login: Mon Mar 23 12:59:54 2015 from login-b.vc-b

-bash-4.2$ ssh john@c002.vc-b
The authenticity of host 'c002.vc-b (172.17.0.2)' can't be established.
RSA key fingerprint is fb:f0:34:12:5f:e9:5d:6a:4f:4d:b7:82:71:af:d7:13.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'c002.vc-b' (RSA) to the list of known hosts.
john@c002.vc-b's password: 
Permission denied, please try again
-bash-4.2$

**Comment by hansthen** [comment]
It turned out this were actually two bugs:

1. the login node did not mount /home
2. the container's DNS search domain pointed to vc-a instead of (in this case) vc-b.

**Comment by hansthen** [comment]
Assigning to abhi for solution

**Comment by abhimukh** [comment]
virtual home folders should now be created during cluster partition from the API.
c012d4b7dca0502ba7382940c3909b7a78e44ada

login nodes should be able to mount them

**Comment by themisa** [comment]
last part to accomplish passwordless ssh: for a user created by obol, id_dsa.pub should be copied to authorized_keys

**Comment by themisa** [comment]
[root@openstack ~(keystone_a)]# ssh john@login-a.vc-a
john@login-a.vc-a's password: 
Last login: Thu Mar 26 11:29:27 2015
-bash-4.2$ ls
-bash-4.2$ sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1  drain c002
-bash-4.2$ ssh c002
The authenticity of host 'c002 (172.16.0.2)' can't be established.
RSA key fingerprint is e3:e7:57:c4:3a:73:78:9f:3e:11:26:2e:bd:e7:a2:9a.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'c002,172.16.0.2' (RSA) to the list of known hosts.

Passwordless access to the containers of a cluster works. Still not messageless, but will file a different bug

**Comment by themisa** [comment]
This issue just reappeared:

-bash-4.2$ hostname
login.vc-b
-bash-4.2$ whoami
jane
-bash-4.2$ ssh c001
Warning: Permanently added 'c001,172.17.0.1' (RSA) to the list of known hosts.
jane@c001's password: 
Last login: Fri Apr 17 13:57:27 2015 from login-b.vc-b

* r3
3ffad27

**Comment by themisa** [comment]
Reopening bug invalid. User jane had stale ssh credentials.
