### ISSUE TITLE
Cluster Partition: old dns entries for containers are not removed 

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#130]
**Software:**
* r3
5cead59

**Component:**
xCAT controller

**Hardware:**
master/controller02

**Bug description:**
When a node is removed from a virtual cluster, its hostname should not resolve to an ip address.
However, currently its hostname to ip mapping survives

**Steps to reproduce:**
From the dashboard remove a container from a virtual cluster. 

**Expected output:**
Assume that the container that was removed is c001, and the virtual cluster from which it was removed is vc-a.  Then 
> host c001.vc-a 
should give an error

**Actual output:**
> host c001.vc-a 
gives an ip address of 172.16.0.1

**Comment by themisa** [comment]
Cluster vc-a has c002
Cluster vc-b has c001
From login-a.:
[root@login ~]# host c001
Host c001 not found: 3(NXDOMAIN)
[root@login ~]# host c002
c002.vc-a has address 172.16.0.2

Correct behavior in * r3
ae94b4a
