### ISSUE TITLE
Trinity container: DNS search domain is not updated (but points to the first VC)

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#131]
-bash-4.2$ cat /etc/resolv.conf 
search cluster. vc-a. cluster
nameserver 10.141.255.254

**Comment by hansthen** [comment]
To test: login to the container and cat /etc/resolv.conf

The search should be right.

**Comment by themisa** [comment]
not fixed in * r3
3443442


[root@c001 /]# cat /etc/resolv.conf 
nameserver 10.141.255.254
search vc-a

c001 belongs to vc-b
[root@c001 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
9: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 4e:a0:fd:87:70:07 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::4ca0:fdff:fe87:7007/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by themisa** [comment]
[root@node001 ~]# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS               NAMES
ab7ae59590c0        controller:5050/trinity:latest   "/usr/bin/supervisor   3 hours ago         Up 8 minutes                            trinity            

force-reload should have used a newer image

**Comment by themisa** [comment]
Today, service trinity force-reload gives the appropriate results:

root@node001 ~]# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED              STATUS              PORTS               NAMES
5ad919068b0d        controller:5050/trinity:latest   "/usr/bin/supervisor   About a minute ago   Up About a minute                       trinity             
[root@node001 ~]# docker-enter trinity
[root@c001 /]# hostname
c001.vc-b
[root@c001 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
9: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 56:74:7e:60:08:63 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5474:7eff:fe60:863/64 scope link 
       valid_lft forever preferred_lft forever

[root@c001 /]# cat /etc/resolv.conf
nameserver 10.141.255.254
search vc-b

**Comment by themisa** [comment]
Fix to #126 fixes this issue
