### ISSUE TITLE
controller installation: no route to default virtual login node

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#132]
**Software:** Trinity * r3
ae94b4a

**Component:** controller  installation
**Hardware:** SM
**Test case:** 1.2.10
**Bug description:**
Slurm not running on default virtual login node,
Reason: xCAT controller has no route to 172.16.0.0/12

**Comment by hansthen** [comment]
@themisa How can I reconstruct the error?

**Comment by themisa** [comment]
[root@controller ~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         master.cluster  0.0.0.0         UG    1024   0        0 eno1
10.0.0.0        0.0.0.0         255.255.0.0     U     0      0        0 docker0
10.141.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
10.148.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
172.16.0.0      0.0.0.0         255.240.0.0     U     0      0        0 eno2
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eno1

**Comment by hansthen** [comment]
That looks right to me:
172.16.0.0 0.0.0.0 255.240.0.0 U 0 0 0 eno2

**Comment by themisa** [comment]
cannot reproduce error. Route table correct for the latest controller installation
* r3
3443442
