### ISSUE TITLE
partition cluster: slurm not updating correctly

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#135]
After repartitioning the cluster a, (initially vc-a have c001-c002, after partitioning it has only c002)
slurm still reports a as having both nodes.

[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      2   idle c[001-002]

**Comment by abhimukh** [comment]
added additional functionality to tlntool:
> tlntool update <vc_name>

this will restart slurm on the login name.

**Comment by themisa** [comment]
Added procedure: After re-partitioning, the tenant x should run tlntool update vc-x

Then slurm gets restarted/updated properly
