### ISSUE TITLE
trinity containers: munge not started 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#137]
Munge not started on containers
[root@c002 /]# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 10:54 ?        00:00:03 /usr/bin/python /usr/bin/supervisord -c /usr/etc/supervisord.conf
root        11     1  0 10:54 ?        00:00:00 /usr/sbin/slurmd -D -f /cluster/etc/slurm/slurm.conf
root        12     1  0 10:54 ?        00:00:00 /usr/sbin/sshd -D
root        13     1  0 10:54 ?        00:00:00 /sbin/rsyslogd -dn
nslcd       18     1  0 10:55 ?        00:00:00 /usr/sbin/nslcd
root       180     0  0 13:03 ?        00:00:00 su -m root
root       181   180  0 13:03 ?        00:00:00 bash
root       199   181  0 13:03 ?        00:00:00 ps -ef

[possibly due to creation of virtual login node, but not tested independently]

**Comment by themisa** [comment]
After creation of default login-a:

On login node:
[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      0    n/a 

On container:
[root@c001 /]# sinfo
sinfo: error: If munged is up, restart with --num-threads=10
sinfo: error: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
sinfo: error: authentication: Socket communication error
slurm_load_partitions: Protocol authentication error

[root@c001 /]# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 08:57 ?        00:00:02 /usr/bin/python /usr/bin/supervi
root        10     1  0 08:57 ?        00:00:00 /usr/sbin/slurmd -D -f /cluster/
root        11     1  0 08:57 ?        00:00:00 /usr/sbin/sshd -D
root        12     1  0 08:57 ?        00:00:00 /sbin/rsyslogd -dn
nslcd       17     1  0 08:57 ?        00:00:00 /usr/sbin/nslcd
root       118     0  0 10:06 ?        00:00:00 su -m root
root       119   118  0 10:06 ?        00:00:00 bash
root       139   119  0 10:09 ?        00:00:00 ps -ef

**Comment by themisa** [comment]
Manual fix:  psh node001-node002 "service trinity force-reload"

**Comment by abhimukh** [comment]
Now the API creates a munge key at the time when HPC resources (containers) are assigned to the tenant for the first time.

**Comment by themisa** [comment]
* r3
c5a68e5

for vc-a this is still an issue

**Comment by abhimukh** [comment]
The login node configuration file leaves the cluster munge key (if it exists) untouched.

**Comment by themisa** [comment]
Not fixed in r3 - commit is on master

**Comment by themisa** [comment]
[root@c001 /]# su munge -c  "/usr/sbin/munged -F --key-file /cluster/etc/munge/munge.key"
munged: Notice: Running on "c001.vc-a" (172.16.0.1)
munged: Info: PRNG seeded with 1024 bytes from "/dev/urandom"
munged: Error: Keyfile is insecure: "/cluster/etc/munge/munge.key" should be owned by UID 1002

**Comment by abhimukh** [comment]
The munge key is getting created at the time of controller installation (cv_install_xcat):

dd if=/dev/urandom bs=1 count=1024 >/cluster/vc-a/etc/munge/munge.key
chmod 400 /cluster/vc-a/etc/munge/munge.key

which is why it is owned by root.

reassigning @hansthen

**Comment by hansthen** [comment]
Verified: 4bcce3c
