### ISSUE TITLE
partition cluster: allocated containers should know which vc they belong to

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#138]
Case: Allocated c001 to vc-b (from trinity dashboard)

[root@c001 /]# hostname
c001.vc-a

[root@controller xcatpost]# tabdump nodelist
#node,groups,status,statustime,appstatus,appstatustime,primarysn,hidden,updatestatus,updatestatustime,zonename,comments,disable
"controller","xcat",,,,,,,,,,,
"switch","xcat",,,,,,,,,,,
"login-a","login",,,,,,,,,,,
"node001","compute","booted","03-25-2015 11:52:44",,,,,,,,,
"node002","compute","booted","03-25-2015 11:53:01",,,,,,,,,
"node003","compute","booted","03-25-2015 12:49:06",,,,,,,,,
"c001","hw-FatNodes,vc-b",,,,,,,,,,,
"c002","hw-GenericNodes,vc-a",,,,,,,,,,,
"login-b","login",,,,,,,,,,,

**Comment by abhimukh** [comment]
This was happening because of #139. When the container starts it tries to find which cluster it belongs to by looking at dns entries which contains its name (and picks the first one it finds).  In this case the stale entry c001.vc-a results in the incorrect behaviour.

**Comment by themisa** [comment]
[root@c002 /]# hostname
c002.vc-b

fixed in * r3
c5a68e5
