### ISSUE TITLE
API server : Containers do not get started from the API server

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#140]
**Software:**
* r3
3443442

**Component:**
API server

**Hardware:**
master/controller02/node003 (OpenStack node)

**Bug description:**
The containers should be restarted from the API server during cluster repartitioning

**Comment by themisa** [comment]
Containers still not restarted during repartitioning.
* r3
feda38f

Manual fix: service trinity force-reload

**Comment by themisa** [comment]
fixed in * r3
c5a68e5
