### ISSUE TITLE
Login nodes: user ssh access to containers is not message-less

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#142]
**Software:** * r3
feda38f

**Component:** virtual login node + containers controlled by it
**Hardware:**openstack node (node003) + compute node (node002)
**Test case:** 3.3.5
**Bug description:**
When users ssh from a virtual login node to the container associated with their virtual cluster, the first "access" is not messageless:
**Steps to reproduce:**
- login as a user to virtual login node i.e. ssh john@login-a.vc-a)
- ssh to a container for 1st time (ssh c002  (if c002 in vc-a))

**Expected output:**
**Actual output:**
john@login-a.vc-a's password: 
Last login: Thu Mar 26 11:29:27 2015
-bash-4.2$ ls
-bash-4.2$ sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1  drain c002
-bash-4.2$ ssh c002
The authenticity of host 'c002 (172.16.0.2)' can't be established.
RSA key fingerprint is e3:e7:57:c4:3a:73:78:9f:3e:11:26:2e:bd:e7:a2:9a.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'c002,172.16.0.2' (RSA) to the list of known hosts.

**Comment by abhimukh** [comment]
This can be solved by unsetting the StrictHostKeyChecking in ssh_config (StrictHostKeyChecking no).
I will add this to the login node startup script.

**Comment by abhimukh** [comment]
@themisa : Now the users should be able to ssh from the __login node__ to the __container__ without any prompting (no need to press enter).
Question: do we also need users to be able to ssh from the __containers__ to the __login node__  or between __containers__?
In that case StrictHostKeyChecking will need to be turned off in the containers as well by @hansthen   

I think we need passwordless/messageless ssh only for SLURM (or MPI) to launch the process from the appropriate controller (our login node) to the worker nodes (our containers). Further communication between the processes uses a different protocol. In which case the current fix should be suficient.

**Comment by themisa** [comment]
[root@openstack ~(keystone_b)]# ssh john@login-b.vc-b
john@login-b.vc-b's password: 
Last login: Mon Mar 30 13:56:16 2015
-bash-4.2$ ssh c002
Warning: Permanently added 'c002,172.17.0.2' (RSA) to the list of known hosts.

@abhimukh 
is this first login message still undesirable?

**Comment by themisa** [comment]
ok this is fixed
* r3
c5a68e5
