### ISSUE TITLE
slurm: no slurm log files by default

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#143]
**Software:*** r3
feda38f

**Component:** slurm on virtual login nodes
**Hardware:** nodes001-003 (SM, dell)
**Test case:**
**Bug description:**
It would be helpful to have slurm log files, in order to debug any issues relating to slurm

**Actual output:**
[root@login modulefiles]# ls /var/log/slurm/
[root@login modulefiles]#

**Comment by hansthen** [comment]
I will add the required configuration to the template files.

**Comment by hansthen** [comment]
Assigning to abhi, to make sure the log file definitions are also created in the Partition Cluster use case.

**Comment by abhimukh** [comment]
/var/log/slurm is already created on the login node during the login node creation time. The slurm conf file on the new clusters are copies of that on vc-a.

**Comment by themisa** [comment]
[root@login home]# ls /var/log/slurm/
slurmctld.log

Fixed. Tested in * r3
78f4bc5
