### ISSUE TITLE
Controller installation: required netboot files were not generated after installation

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#145]
**version:** * master_installer
9a58554
?? master/create_repo_snapshot.sh

**systems:**
SM1 (controller), SM5 (master)

**expected output:**
[root@controller ~]# ls /tftpboot/xcat/xnba/nets/
10.0.0.0_16.elilo  10.141.0.0_16     10.141.0.0_16.uefi   10.148.0.0_16.elilo  127.0.0.0_8         127.0.0.0_8.uefi   192.168.1.0_24.elilo

**actual output:**
[root@controller ~]# ls /tftpboot/xcat/xnba/nets/1
127.0.0.0_8           127.0.0.0_8.elilo     127.0.0.0_8.uefi      192.168.1.0_24        192.168.1.0_24.elilo  192.168.1.0_24.uefi

The actual error shows up when netbooting the nodes. The nodes do get a (temporary) mac address, but they complain when downloading the genesis kernel that there is "no such file or directory" with error code "2d0c613b".

**Comment by hansthen** [comment]
Hypothesis: this happens when mknb is called during the setup script when the network cable is not yet attached.

**Comment by hansthen** [comment]
Workaround call `mknb x86_64` manually.

**Comment by hansthen** [comment]
Unable to reproduce. Assigning back to Themis for re-testing.

**Comment by themisa** [comment]
unable to reproduce on dtap * dtap
e953fd8

will close for now
