### ISSUE TITLE
Trinity: master and controller nodes need better hostnames

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#147]
Currently they are all called "master" or "controller". This can be confusing (and it messes up the DNS namespace). From the prompt it should be clear which node we are addressing and how it is hooked up.

**Comment by hansthen** [comment]
Solved by adding an identifying prompt.

**Comment by themisa** [comment]
**Version:** r5_fixes ec6bb63
**Environment:**

(amaster)
```
cat: /trinity/site: No such file or directory
[root@controller() ~]# 
```
