### ISSUE TITLE
Need shared directory for cluster-wide apps on virtual clusters

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#148]
Use case: 4.1.1 - The user uploads source-code, or a package in a shared directory 

Power users should be able to compile and write modulefiles for applications to be used by all users of a virtual cluster. Therefore we need a shared directory for such users to compile into, but one that is private for the virtual cluster the user belongs to.

**Comment by hansthen** [comment]
Should be /cluster/<cluster>/apps and modules and should be created by the login creation script.

**Comment by themisa** [comment]
[root@login home]# ls /cluster/
apps  etc  modules

Fixed, tested in * r3
78f4bc5
