### ISSUE TITLE
Controller installation: cv_install_docker fails to push the image without network cable

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#149]
**Version:** * master_installer
9a58554

The following error message is displayed.
`2015/03/28 09:41:32 Error: Invalid registry endpoint "http://controller:5050/v1/". HTTPS attempt: Get https://controller:5050/v1/_ping: dial tcp 10.141.255.254:5050: i/o timeout. HTTP attempt: Get http://controller:5050/v1/_ping: dial tcp 10.141.255.254:5050: i/o timeout`

**Comment by hansthen** [comment]
It seems like the interface is not configured when there is no cable attached.

Workarounds: 
1. plugin the cable
2. Manuall add an IP address to the device.

**Comment by hansthen** [comment]
Cause of this:
the script network-functions sets the variable $_use_nm to true. This causes ifup to use a network manager program `nmcli`.

**Comment by hansthen** [comment]
Please note: in master_installer branch.

**Comment by themisa** [comment]
Remove 2nd interface cable from master to controller and try it. In r4

**Comment by themisa** [comment]
Tested in r5 f178005


```
[root@controller ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
controller:5050/trinity   latest              641e145b2465        16 hours ago        696.3 MB
docker.io/centos          latest              7322fbe74aa5        12 days ago         172.2 MB
```
