### ISSUE TITLE
slurm: slurm should be aware of the number of cores in a node

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#150]
**Software:** trinity
**Component:** virtual login node: slurm
**Hardware:** SM
**Test case:** run job 5.
**Bug description:**
At the moment, slurm is configured to use only 1 cpu per node. We would like it to use all cpu's available on a node

**Actual output:**
[root@login testcode]# scontrol show partitions
PartitionName=container
   AllowGroups=ALL AllowAccounts=ALL AllowQos=ALL
   AllocNodes=ALL Default=YES
   DefaultTime=NONE DisableRootJobs=NO GraceTime=0 Hidden=NO
   MaxNodes=UNLIMITED MaxTime=UNLIMITED MinNodes=1 LLN=NO MaxCPUsPerNode=UNLIMITED
   Nodes=c002
   Priority=1 RootOnly=NO ReqResv=NO Shared=NO PreemptMode=OFF
   State=UP TotalCPUs=1 TotalNodes=1 SelectTypeParameters=N/A
   DefMemPerNode=UNLIMITED MaxMemPerNode=UNLIMITED

**Comment by abhimukh** [comment]
Trinity API now get the cpucount for all nodes from the xCAT database during startup, and uses that to populate the slurm conf file.

**Comment by themisa** [comment]
[root@login slurm]# more slurm-nodes.conf 
NodeName=c002 CPUS=8 State=UNKNOWN
PartitionName=container Nodes=c002 Default=Yes MaxTime=INFINITE State=UP

v. * r3 78f4bc5

Will keep open until i can run a multi-core job.

**Comment by themisa** [comment]
PartitionName=container
   AllowGroups=ALL AllowAccounts=ALL AllowQos=ALL
   AllocNodes=ALL Default=YES
   DefaultTime=NONE DisableRootJobs=NO GraceTime=0 Hidden=NO
   MaxNodes=UNLIMITED MaxTime=UNLIMITED MinNodes=1 LLN=NO MaxCPUsPerNode=UNLIMITED
   Nodes=c002
   Priority=1 RootOnly=NO ReqResv=NO Shared=NO PreemptMode=OFF
   State=UP TotalCPUs=8 TotalNodes=1 SelectTypeParameters=N/A
   DefMemPerNode=UNLIMITED MaxMemPerNode=UNLIMITED

(issues with running a multicore job with srun will be documented in another ticket)
