### ISSUE TITLE
Controller installation: access rights for shared directories

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#151]
The LDAP servers inside the login nodes should be created with a common group for power users, granting write access to only that group. The /cluster directories inside the NFS server should be created with those groups, allowing write access for the power users.

As an alternative, we could create a separate NFS server (with /cluster directories) on the virtual login node, instead of inside the physical nodes.

**Comment by hansthen** [comment]
Current problem is that the shared NFS directory just has numeric user and group id's. Since we use separate LDAP servers for each of the virtual clusters, these id's may overlap, causing (slight) security issues. 

Possible workarounds
1. we could create a default group inside each virtual LDAP server, with a standardized numeric group id. 
2. we could create a set of groups (one for each virtual cluster) inside each virtual LDAP server, with standardized numeric ids.

**Comment by themisa** [comment]
Manual workaround for now:
> chgrp -R power-users cluster
> chmod -R g+w cluster
> ls -ltr /cluster

**Comment by abhimukh** [comment]
I think this was fixed with the fix for #156 
Reassigning to @hansthen

**Comment by hansthen** [comment]
Yes #156 fixes this as well.

**Comment by themisa** [comment]
fixed. [root@login munge]# su jane
bash-4.2$ touch /cluster/apps/testfile
bash-4.2$
