### ISSUE TITLE
obol user management: adding users to groups error

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#153]
When creating a user with obol, there is an option of adding them to a group. This functionality doesn't work as expected:

[root@login ~]# obol group list
150 users
151 power-users
1050 john
1051 jane
1053 themis

the last 3 should be users not groups:

Also: 
[root@login ~]# obol user add --password 123 --cn Themis --sn Smith --givenName John --groups power-users themis
themis 1053
[root@login ~]# obol user show themis
{'uid': ['themis'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1053'], 'gidNumber': ['1053'], 'sn': ['Smith'], 'homeDirectory': ['/home/themis'], 'givenName': ['John'], 'cn': ['Themis']}

Even if i add user themis to group power-users, the gid remains the same as uid.

Also trying to add a user to a group after they are created doesn't work:
[root@login ~]# obol group addusers power-users themis
themis 1053
{'info': 'modify/add: memberUid: value #0 already exists', 'desc': 'Type or value exists'}
Traceback (most recent call last):
  File "/usr/sbin/obol", line 290, in <module>
    fun(**args_d)
  File "/usr/sbin/obol", line 162, in group_addusers
    conn.modify_s(dn, mod_attrs)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 357, in modify_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.TYPE_OR_VALUE_EXISTS: {'info': 'modify/add: memberUid: value #0 already exists', 'desc': 'Type or value exists'}

**Comment by hansthen** [comment]
@themisa Create two separate issues for this.

**Comment by hansthen** [comment]
Each user has a "private" group. This is a design practice common in UNIX systems. See https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/Reference_Guide/s1-users-groups-private-groups.html

To check if the user was added to the "extra" groups (power-users in this case) use 
obol group show power-users.
