### ISSUE TITLE
user management: groups created by obol don't propagate correctly

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#155]
[root@login ~]# obol group show power-users
{'objectClass': ['top', 'posixGroup'], 'memberUid': ['1051', '1053'], 'gidNumber': ['151'], 'cn': ['power-users']}

So user 1053 should be part of group power-users
but:
[root@login ~]# id themis
uid=1053(themis) gid=1053(themis) groups=1053(themis)

**Comment by hansthen** [comment]
It appears the memberUid of group should contain the user names, not numeric ids.

**Comment by hansthen** [comment]
Fixed:
[root@login ~]# obol group addusers power-users themis
[root@login ~]# getent group | grep power-users
power-users:*:151:themis,1051,1053
[root@login ~]# su - themis
-bash-4.2$ id
uid=1053(themis) gid=1053(themis) groups=1053(themis),151(power-users) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
-bash-4.2$ cd /cluster/apps
-bash-4.2$ cd apps/
-bash-4.2$ touch testfile
-bash-4.2$ ls
test  testfile

**Comment by themisa** [comment]
[root@login home]# obol group show power-users
{'objectClass': ['top', 'posixGroup'], 'memberUid': ['jane', 'john'], 'gidNumber': ['151'], 'cn': ['power-users']}
[root@login home]# id jane
uid=1051(jane) gid=1051(jane) groups=1051(jane),151(power-users)

**Comment by themisa** [comment]
Fixed. * r3
78f4bc5

[root@login munge]# su jane
bash-4.2$ touch /cluster/apps/testfile
bash-4.2$
