### ISSUE TITLE
Architecture: power users cannot write to /cluster filesystem

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#156]
[root@c002 cluster]# su - themis
uid=1053(themis) gid=1053(themis) groups=1053(themis)
-bash-4.2$ cd /cluster/
-bash-4.2$ ls -ln
drwxrwxr-x 2 0 151 17 Apr  2 11:38 apps
drwxrwxr-x 4 0 151 30 Mar 30 08:36 etc
drwxrwxr-x 2 0 151  6 Mar 31 08:12 modules
-bash-4.2$ getent group
power-users:*:151:1051,1053
-bash-4.2$ touch apps/test2
touch: cannot touch 'apps/test2': Permission denied

Problem is the group membership of themis is only defined on the login node. When writing to the NFS server, the NFS servers does it's own authentication checks. But here the test will fail because both user 1053 and group 151 are not defined on the NFS server.

**Comment by hansthen** [comment]
We can solve this by exporting the /cluster file system from the login node and not from the controller node. However, this introduces a few new problems, the main one is that the Partition Cluster use case will break, since the trinity-api will not have access to the slurm-nodes.conf for that server.

**Comment by hansthen** [comment]
Solution approach:

1. Before we allocate resources to a cluster, we must make sure there is a login node for the cluster. We can have the OpenStack admin create login nodes by making the admin temporarily member of the appropriate tenant group.
2. When allocating resources in the Partition Cluster use case, the api server will ssh into the API server to update the slurm-nodes.conf for that particular cluster.
3. The trinity startup script will have to be adapted to mount the virtual cluster directory from the login node (or mount it inside the container).

**Comment by abhimukh** [comment]
Step (2) will fail when modifying a cluster (adding or removing nodes) because the root password for the cluster could (and should) have been changed.

**Comment by abhimukh** [comment]
Another option:
1. Move the modules and apps folders from the cluster directory, and remove them completely.
2. If the root/tenant wants to have a clusterwide shared directory which is writeable by a subset of users (power-users) [note that currently, /home is shared clusterwide, but each user has write access to his/her own home dir.] then he/she can simply export that directory and mount it on all the nodes (using pdsh for example).

**Comment by hansthen** [comment]
Apparently, fixing #155 also fixed this issue.

**Comment by themisa** [comment]
This is fixed. 
* r3
78f4bc5
