### ISSUE TITLE
trinity image: need infiniband support

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#157]
We should have IB support with trinity image
yum install infiniband-diags
 yum -y groupinstall "Infiniband Support"

**Comment by themisa** [comment]
ibstatus
   29  exit
   30  ibstatus
   31  yum install infiniband-diags
   32  ibstatus
   33  yum groupinstall "Infiniband Support"
   34  lsmod 
   35  sysctl --help
   36  systemctl list
   37  systemctl --help
   38  systemctl 
   39  systemctl status rdma
   40  modprobe ib_umad
   41  ibstatus
   42  systemctl status opensm
   43  yum search opensm
   44  yum install opensm
   45  systemctl status opensm
   46  systemctl start opensm
   47  systemctl status opensm
   48  ibstatus
   49  ibv_devinfo 
   50  lspc
   51  lspci
   52  yum install pciutils
   53  lspci
   54  lspci | grep lanox
   55  lsmod | grep mlx
   56  modprobe mlx4_ib
   57  ibv_devinfo

**Comment by linuxstudio** [comment]
yum -y groupinstall "Infiniband Support"

doesn't install the subnet manager. On the trinity node:

   yum -y install opensm
   systemctl start opensm

**Comment by hansthen** [comment]
Where should opensm run? Up till now it ran on the controller, but that was just a personal custom. It is not scripted at the moment. I think it needs to run only once, so the controller would be a logical location, but that would require the controller to have an IB card. In that case the required adaptations need to be in cv_install_controller, under trinity/master/rootimg/install/postscripts.

**Comment by hansthen** [comment]
So the following is required:

We need add the following packages to the controller
Infiniband Support
opensm
infiniband-diags

Also the controller should start opensm.

This can all be added to cv_install_controller (in master_installer branch) or cv_install_xcat (on master).

**Comment by hansthen** [comment]
Turns out on the trinity node the mellanox driver is not loaded at startup. This can be solved manually by running:

modprobe mlx4_ib

However, this driver should have been loaded automatically.

**Comment by hansthen** [comment]
That works. Changed have yet to be committed to the git repo.
[root@node002 ~]# ibstatus
Infiniband device 'mlx4_0' port 1 status:
	default gid:	 fe80:0000:0000:0000:f452:1403:0022:4be1
	base lid:	 0x0
	sm lid:		 0x0
	state:		 2: INIT
	phys state:	 5: LinkUp
	rate:		 40 Gb/sec (4X QDR)
	link_layer:	 InfiniBand

**Comment by hansthen** [comment]
Verified:
**version:** 9f2fae3

**Tested:**
```[root@controller ~]# systemctl status opensm
opensm.service - Starts the OpenSM InfiniBand fabric Subnet Manager
   Loaded: loaded (/usr/lib/systemd/system/opensm.service; disabled)
   Active: active (running) since do 2015-04-09 16:07:17 CEST; 3 days ago
```

**Tested:**
```
[root@controller ~]# ibstat | grep "Port GUID"
		Port GUID: 0x0002c903000bbdb5
[root@controller ~]# ibping -S
[root@c001 ~]# ibping -G 0x0002c903000bbdb5
Pong from controller.cluster.(none) (Lid 1): time 0.134 ms
Pong from controller.cluster.(none) (Lid 1): time 0.191 ms
```
