### ISSUE TITLE
srun inside a container: segfaults when ran as user

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#159]
Case 1: root
[root@c001 ~]# srun -n 1 IMB-MPI1 pingpong
 benchmarks to run pingpong 
------------------------------------------------------------
    Intel (R) MPI Benchmarks 4.0 Update 1, MPI-1 part    
------------------------------------------------------------
 Date                  : Fri Apr  3 14:15:50 2015
 Machine               : x86_64
 System                : Linux
 Release               : 3.10.0-123.el7.x86_64
 Version               : #1 SMP Mon Jun 30 12:09:22 UTC 2014
 MPI Version           : 3.0
 MPI Thread Environment: 

 New default behavior from Version 3.2 on:

 the number of iterations per message size is cut down 
 dynamically when a certain run time (per message size sample) 
 is expected to be exceeded. Time limit is defined by variable 
 "SECS_PER_SAMPLE" (=> IMB_settings.h) 
 or through the flag => -time 
  

 Calling sequence was: 

 /trinity/clustervision/apps/imb/src/IMB-MPI1 pingpong

 Minimum message length in bytes:   0
 Maximum message length in bytes:   4194304

 MPI_Datatype                   :   MPI_BYTE 
 MPI_Datatype for reductions    :   MPI_FLOAT
 MPI_Op                         :   MPI_SUM  

 List of Benchmarks to run:

 PingPong

 !! Benchmark PingPong invalid for 1 processes !! 

 All processes entering MPI_Finalize

**Comment by themisa** [comment]
Case 2: user jane 

-bash-4.2$ module list
Currently Loaded Modulefiles:
  1) imb/4.0.2              2) openmpi/gcc/64/1.8.4
-bash-4.2$ ulimit -l
unlimited
-bash-4.2$ srun -n 1 IMB-MPI1 pingpong
srun: error: c001: task 0: Segmentation fault
-bash-4.2$ hostname
c001.vc-c

**Comment by linuxstudio** [comment]
This may be addressed either through use of the ulimit command in the /etc/sysconfig/slurm file or enabling PAM in SLURM.

https://computing.llnl.gov/linux/slurm/faq.html#rlimit

**Comment by hansthen** [comment]
@linuxstudio Can you make the appropriate changes and then assign them back to @themisa for testing?

**Comment by themisa** [comment]
As in 158, does not segfault anymore when ran as user
v. 78f4

**Comment by hansthen** [comment]
**Tested in:** 4bcce3c
