### ISSUE TITLE
controller installation: docker service not started

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#161]
**Software:** Trinity *r3 446bb9d
**Component:** controller installation
**Hardware:** SM controller02
**Test case:** 1.1.10
**Bug description:**
Docker service not started after controller installation
**Steps to reproduce:**
1) nodeset controller with install-controller image
2) ssh to controller02 and wait for postinstall scripts to finish
3) systemctl status docker.service
  - docker images 
**Expected output:**

**Actual output:**
[root@controller ~]# systemctl status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since Tue 2015-04-07 13:33:43 CEST; 7min ago
     Docs: http://docs.docker.com
 Main PID: 7950 (code=exited, status=127)

Apr 07 13:33:43 controller.cluster docker[7950]: time="2015-04-07T13:33:43+02:00" level="info" msg="+job serveapi(unix:///var/...sock)"
Apr 07 13:33:43 controller.cluster docker[7950]: /usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_w...erence
Apr 07 13:33:43 controller.cluster systemd[1]: docker.service: main process exited, code=exited, status=127/n/a
Apr 07 13:33:43 controller.cluster systemd[1]: Failed to start Docker Application Container Engine.
Apr 07 13:33:43 controller.cluster systemd[1]: Unit docker.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
[root@controller ~]# docker images
FATA[0000] Get http:///var/run/docker.sock/v1.18/images/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by hansthen** [comment]
Seems to be noted before in RH7 systems: https://access.redhat.com/solutions/1397523

**Comment by hansthen** [comment]
And here: http://stackoverflow.com/questions/27216473/docker-1-3-fails-to-start-on-rhel6-5

Workaround: yum update device-mapper-event-libs

**Comment by hansthen** [comment]
I will add this as a workaround to the cv_install_docker script.

**Comment by themisa** [comment]
Fixed * r3 78f4bc5

[root@controller ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
controller:5050/trinity   latest              abcc7af50c2f        8 minutes ago       724.2 MB
docker.io/centos          7                   9dbcac75201e        39 hours ago        215.6 MB
docker.io/centos          centos7             9dbcac75201e        39 hours ago        215.6 MB
docker.io/centos          latest              9dbcac75201e        39 hours ago        215.6 MB
