### ISSUE TITLE
trinity netboot: docker not running

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#162]
**Software:** Trinity 
**Component:*** r3
446bb9d

**Hardware:** node001, node002
**Test case:** 1.2.14
**Bug description:**
after we netboot a node with a trinity image, docker containers should be running. No containers running
**Steps to reproduce:**
on a trinity netbooted node:
- docker ps
-systemctl status docker.service
**Expected output:**
**Actual output:**
[root@node001 ~]# docker ps
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
[root@node001 ~]# systemctl status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           remote-fs.conf
   Active: failed (Result: exit-code) since Tue 2015-04-07 16:00:39 CEST; 40s ago
     Docs: http://docs.docker.com
  Process: 2128 ExecStart=/usr/bin/docker -d $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $ADD_REGISTRY $BLOCK_REGISTRY $INSECURE_REGISTRY (code=exited, status=127)
 Main PID: 2128 (code=exited, status=127)

Apr 07 16:00:39 node001.cluster docker[2128]: time="2015-04-07T16:00:39+02:00" level="info" msg="+job serveapi(unix:///var/run...sock)"
Apr 07 16:00:39 node001.cluster docker[2128]: /usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with...erence
Apr 07 16:00:39 node001.cluster systemd[1]: docker.service: main process exited, code=exited, status=127/n/a
Apr 07 16:00:39 node001.cluster systemd[1]: Failed to start Docker Application Container Engine.
Apr 07 16:00:39 node001.cluster systemd[1]: Unit docker.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by hansthen** [comment]
Workaround: (slightly different than the one from #161)

yum update device-mapper

**Comment by themisa** [comment]
Fixed in * r3
78f4bc5
