### ISSUE TITLE
openstack node installation: repo directory no longer valid

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#163]
**Software:** trinity
**Component:**openstack installation
**Hardware:**poweredge node003
**Test case:**1.2.5
**Bug description:**
On installation openstack node, openstack services should be running
**Steps to reproduce:**
nodeset node003 osimage=centos7.0-x86_64-install-openstack
tail -f /var/log/xcat/xcat.log
**Expected output:**
**Actual output:**
failure: repodata/repomd.xml from C7.0.1406-base: [Errno 256] No more mirrors to try.
http://vault.centos.org/7.0.1406/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
./cv_install_openstack: line 23: packstack: command not found
sed: can't read /etc/nova/nova.conf: No such file or directory
sed: can't read /etc/openstack-dashboard/local_settings: No such file or directory
Failed to issue method call: Unit openstack-nova-compute.service failed to load: No such file or directory.
Failed to issue method call: Unit openstack-nova-api.service failed to load: No such file or directory.
./cv_install_openstack: line 32: /root/keystonerc_admin: No such file or directory
./cv_install_openstack: line 33: nova: command not found
./cv_install_openstack: line 36: killall: command not found
Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.

**Comment by hansthen** [comment]
As a workaround we can delete /etc/yum.repos.d/CentOS-Vault.repo before running cv_install_openstack.

**Comment by hansthen** [comment]
Works for me in 618ba29.
