### ISSUE TITLE
docker containers: hostname command not available

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#166]
**Software:** trinity 
**Component:*** r3
78f4bc5
**Hardware:** 
**Test case:**2.1.7
**Bug description:**
hostname is not available anymore inside the containers
**Steps to reproduce:**
ssh node001
docker-enter trinity
hostname
**Expected output:**
c001.vc-a
**Actual output:**
[root@c001 /]# hostname
bash: hostname: command not found

**Comment by hansthen** [comment]
Will not fix this. Hostname is not required in the container and we want to keep it minimal. To test the container's membership you can cat /etc/resolv.conf and check the search domain.

**Comment by themisa** [comment]
Might be needed (exeter job scripts)

**Comment by hansthen** [comment]
Assigned to Themis for fixing (not testing).

**Comment by themisa** [comment]
fixed in * r3
0d12eb5
