### ISSUE TITLE
virtual login node: /cluster/modules should be renamed /cluster/modulefiles

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#167]
in /trinity/clustervision, we have directories /apps, and /modulefiles
For consistency, we would like /cluster to also follow the same naming scheme

currently:
-bash-4.2$ ls /cluster
apps  etc  modules

**Comment by themisa** [comment]
3ffad27
not fixed: 
[root@login cluster]# ls -ltr /cluster
total 0
drwxr-xr-x. 4 root root        30 Apr  8 07:57 etc
drwxrwxr-x. 2 root admin        6 Apr  8 14:36 modules
drwxrwxr-x. 2 root power-users 58 Apr  9 10:38 apps

**Comment by abhimukh** [comment]
This issue should have been fixed in an earlier commit. The /cluster directory needs to be cleaned at the time of reprovisioning. 
Reassigning @themisa

**Comment by themisa** [comment]
[root@login ~]# ls /cluster
apps  etc  modulefiles
