### ISSUE TITLE
Test procedures/cluster partitioning: access rights for /cluster/<vc>/

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#170]
For munge to be secure, the top level directories should not be group writeable.

So /cluster/<vc>/etc/slurm and ./munge should be owned by root:root and only be writeable by the user.
/cluster/<vc>/etc/slurm/slurm-user.conf should be group owned by power-users (or administrators) and group writable.
/cluster/<vc>/apps and ./modulefiles should be group-owned by power-users and group writeable.

**Comment by abhimukh** [comment]
@hansthen Should /cluster/etc/munge be owned by root:root or munge:munge?

**Comment by abhimukh** [comment]
This is the situation after a fresh munge install:
[root@openstack trinity]# ls -al /etc/munge
total 12
drwx------    2 munge munge    6 May 16  2014 .
drwxr-xr-x. 114 root  root  8192 Apr 10 10:23 ..

**Comment by hansthen** [comment]
@abhimukh 
/cluster/vc/etc/slurm should be executable (needed to open files inside that directory).

**Comment by abhimukh** [comment]
The /cluster/vc-<x>/etc/slurm directories should have identical permissions as the /cluster/vc-a/etc/slurm directory. They are first copied and then slurm-nodes.conf is edited.

**Comment by hansthen** [comment]
@abhimukh Do I need to change anything?

**Comment by abhimukh** [comment]
@hansthen Since the  /cluster/vc-\<x\>/slurm directory is initially a copy of /cluster/vc-a/slurm, the permissions on the former will be identical to the latter. If we want to change the perms on the former, then the easiest way to do that is to change them on the later (/cluster/vc-a/slurm).

**Comment by hansthen** [comment]
I checked against the source directory. The executable bit is set correctly there, so I guess the problem was introduced manually. Closing now.
