### ISSUE TITLE
Obol: generated user profiles are not quiet enough

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#172]
**version:** 78f4bc5
**steps to reproduce:**
```
[root@login ~]# su - jane
-bash-4.2$ mpirun -np 2 -host c001,c002 --mca btl self,openib IMB-MPI1 pingpong
```

**expected output**:
```
[root@login ~]# su - jane
-bash-4.2$ mpirun -np 2 -host c001,c002 --mca btl self,openib IMB-MPI1 pingpong
STUFF
```
**actual output**:
```
[root@login ~]# su - jane
-bash-4.2$ mpirun -np 2 -host c001,c002 --mca btl self,openib IMB-MPI1 pingpong
Warning: Permanently added 'c001,172.17.0.1' (RSA) to the list of known hosts.
Warning: Permanently added 'c002,172.17.0.2' (RSA) to the list of known hosts.
STUFF
```

**Comment by hansthen** [comment]
Access rights for .ssh/config are faulty.
```
---x-wx--T. 1 john john  80 10 apr 08:06 config
```

**Comment by themisa** [comment]
```
-rw-------. 1 john john  80 Apr 20 13:11 config

```

**Comment by themisa** [comment]
bash-4.2$ su jane
Password: 
bash-4.2$ ssh c001
Warning: Permanently added 'c001,172.17.0.1' (RSA) to the list of known hosts.
jane@c001's password: 

Fixed for group users, but users in power-user group no longer have passwordless access to containers.

Needs fixing.

**Comment by themisa** [comment]
above error due to fact that a home directory existed for user jane before.

Need to obol user delete jane, if user exists
