### ISSUE TITLE
Trinity container: remove root password and root login via sshd

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#177]
The trinity containers currently allow the root user to login via ssh.

This is a security flaw, as it gives the tenant user root access on the containers. If a user wants to access the container as root, they should use docker-enter.

**Comment by hansthen** [comment]
**version:** 3ffad27
```
-bash-4.2$ su - 
Password: 
su: Authentication failure
-bash-4.2$ ssh root@c001
root@c001's password: 
Permission denied, please try again.
```

**Comment by themisa** [comment]
[root@login home]# ssh c001
Warning: Permanently added 'c001,172.17.0.1' (RSA) to the list of known hosts.
root@c001's password: 
Permission denied, please try again.

So root cannot ssh into containers.
@hansthen- this is the desirable behavior, correct?
