### ISSUE TITLE
xCAT controller installation: examples assume one switch

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#18]
The xCat user manual and supporting templates all assume that we use a single switch to perform the installation. In most real installations we will use multiple switches. We should update the manuals and database templates to reflect this.

**Comment by hansthen** [comment]
To test this we need multiple switches.

**Comment by brunopereira81** [comment]
Or a project where this was already done. I can get you the switch database dump from EPFL.

**Comment by hansthen** [comment]
Thx, in fact I think I have the hosts and switch table from EPFL. However, that project uses a different naming convention for the nodes, if I remember correctly.

**Comment by hansthen** [comment]
The following definitions need to be added to the switches table:

"switchNN","switchNN","|\D+(\d+)|Eth1/($1-A)%B+($1-A)/B*C|"

Where:
A -> The first node attached to the switch -1
B -> The total number of nodes in a column of the rack
C -> The number of nodes per column attached to this switch

**Comment by hansthen** [comment]
I added a small tester script that can be used to test a regular expression:

/root/trinity/controller/usr/local/sbin/regextest '(($1-6)%36)+($1-6)/36*30' 36
node036 -> 30

This shows that using this regex, node036 will map to port 30.

**Comment by brunopereira81** [comment]
You are aware that not all switches report the same interface information right? `Eth` is not a norm and changes.

**Comment by hansthen** [comment]
Yes, I was aware of that, but thank you for pointing it out.

**Comment by hansthen** [comment]
xCAT manual updated and test file checked into R2 branch.
