### ISSUE TITLE
Login node creation: /etc/trinity/login.conf is executable

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#180]
Making files under /etc executable is somewhat unusual (apart from the init.d scripts). 

Especially since this file is also adapted for specific invocations and has a conf extension. In general it is recommended to split data from code (and I think systemd makes it mandatory). It is not urgent, but I think we need to come up with a general rule how to handle these types of files.

**Comment by abhimukh** [comment]
login.conf does not need to be executable. In 4bcce3c9dbd8dd3e176feb4a09fd1c12daff7049 it is not.

**Comment by abhimukh** [comment]
This issue should have been fixed. Reassigning @themisa

**Comment by themisa** [comment]
```
[root@openstack vc-a(keystone_b)]# ls -ltr /etc/trinity/
total 20
-rw-r--r-- 1 root root   714 Apr 21 13:25 trinity_api.conf
-rw-r--r-- 1 root root   411 Apr 21 13:25 trinity_client.conf
-rw-r--r-- 1 root root 10684 Apr 21 13:25 login.conf
```
* r3
f877aca
