### ISSUE TITLE
OpenStack installation: api + dash + login postscripts give error unmounting /tmp/trinity

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#183]
**version:** 618ba29
**steps to reproduce:** after an installation, check /var/log/xcat/xcat.log
**actual output:** You will see the following messages. umount.nfs4: /tmp/trinity: device is busy

**Comment by themisa** [comment]
./dashboards/project/hpc_overview/templates/hpc_overview/index.html’ -> ‘/usr/share/openstack-dashboard/openstack_dashboard/dashboards/project/hpc_overview/templates/hpc_overview/index.html’
‘./dashboards/project/hpc_overview/urls.py’ -> ‘/usr/share/openstack-dashboard/openstack_dashboard/dashboards/project/hpc_overview/urls.py’
‘./dashboards/project/hpc_overview/views.py’ -> ‘/usr/share/openstack-dashboard/openstack_dashboard/dashboards/project/hpc_overview/views.py’
‘./dashboards/project/hpc_overview/workflows.py’ -> ‘/usr/share/openstack-dashboard/openstack_dashboard/dashboards/project/hpc_overview/workflows.py’
‘./api/trinity.py’ -> ‘/usr/share/openstack-dashboard/openstack_dashboard/api/trinity.py’
./cv_install_dash: line 26: cd: HOME not set
umount.nfs4: /tmp/trinity: device is busy
Redirecting to /bin/systemctl restart  httpd.service
Tue Apr 28 16:18:47 CEST 2015 Running postscript: cv_install_login
mount.nfs: /tmp/trinity is busy or already mounted
umount.nfs4: /tmp/trinity: device is busy

**Comment by abhimukh** [comment]
This is related to issue #209. Fixed in ea2a0530f293dda6923482015161e3416f132cee

**Comment by themisa** [comment]
fixed in * r4
972ccbe
