### ISSUE TITLE
Trinity architecture: make tenant names / cluster names configurable

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#184]
Right now, virtual cluster names are hard-coded to be vc-a to vc-l. We should make that configurable, so they match whatever tenant names are chosen by the administrator.

I think the impact to api + dash code is negligible. The trinity startup script currently relies on hard-coded names to determine which cluster a booted node belongs to. However, we could simply enumerate the list of vc-*name*s inside the /cluster directory for that.

**Comment by abhimukh** [comment]
The API relies on the a-l naming scheme to determine the virtual cluster network.

**Comment by hansthen** [comment]
@abhimukh How did you do it before we made the cluster a-l scheming mandatory? One option would be to store the network in a file inside the /cluster filesystem. E.g. /cluster/vc-name/.network. The API could generate that file during partitioning. How do you like them apples?

**Comment by themisa** [comment]
@abhimukh - isn't this implements in r5?

**Comment by themisa** [comment]
This is implemented in r5/r5_fixes
