### ISSUE TITLE
Master_installer: cv_install_master

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#191]
**version:** * dtap a24e177

```
mkdir /trinity/iso
wget http://master:/trinity/iso/CentOS-7.0-1406-x86_64-Everything.iso -q -O /trinity/iso/CentOS-7.0-1406-x86_64-Everything.iso
copycds -o /trinity/iso/*.iso
```

This fragment does not work. If we install a master node from a controller, the `master` dns name does not point to anything.

**Comment by themisa** [comment]
Tested by HT - created pmaster using this.
