### ISSUE TITLE
slurm: submitting batch jobs fails

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#193]
As a user (john) submitting jobs via batch script fails.

```
bash-4.2$ hostname
login.vc-b
bash-4.2$ whoami
john
bash-4.2$ sbatch batch.runme
sbatch: error: s_p_parse_file: unable to status file "/etc/slurm/slurm.conf"


```

**Comment by abhimukh** [comment]
In order to reduce the dependency of the rest of the code on the first cluster (vc-a), the template directory is now called vc-0

**Comment by themisa** [comment]
* r3
f877aca

works.
