### ISSUE TITLE
trinity dashboard: hpc overview does not show nodes

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#194]
* r3
f877aca

After nodesetting an openstack node, the dashboard no longer displays nodes, or default cluster a.

On controller though, nodes are sorted in hardware groups, and assigned to vc-a

```

[root@controller ~]# tabdump nodelist
#node,groups,status,statustime,appstatus,appstatustime,primarysn,hidden,updatestatus,updatestatustime,zonename,comments,disable
"controller","xcat",,,,,,,,,,,
"switch","xcat",,,,,,,,,,,
"login-a","login",,,,,,,,,,,
"node001","compute","booted","04-21-2015 12:56:09",,,,,,,,,
"node002","compute","booted","04-21-2015 12:53:46",,,,,,,,,
"node003","compute","failed","04-21-2015 13:25:25",,,,,,,,,
"c001","vc-a,hw-FatNodes",,,,,,,,,,,
"c002","vc-a,hw-GenericNodes",,,,,,,,,,,

```

**Comment by abhimukh** [comment]
Manual workaround:

tabch key=xcat,username=trinity passwd.password=trinity

**Comment by abhimukh** [comment]
This is a problem with update_controller.sh. I have opened a new issue #195. I am closing this one.

**Comment by themisa** [comment]
issue #195 was marked as invalid. Should it be a procedure then, that if we use update controller we use a manual workaround?

**Comment by abhimukh** [comment]
@themisa If you run update_controller with the tables option, then you will need to add a manual step:

tabch key=xcat,username=trinity passwd.password=trinity
mkdef -t policy 6 name=trinity rule=allow
