### ISSUE TITLE
update_controller.sh does not update the xCAT tables properly  and does not clean the /cluster directory

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#195]
The purpose of the update_controller.sh script is to leave the controller node in a state which mimics a fresh install (but with the most recent version of the relevant portion of the repository) but without actually reprovisioning. 
It should thus:
(i) Leave untouched all changes made to the xCAT tables made during the controller installation (e.g. the passwd table is modified by cv_install_xcat_ws)
(ii) Remove all changes made after the controller installation (e.g. the nodegroup table is modified during cluster repartitioning)
(iii) Clean up the /cluster directory, leaving behind only the template directory (vc-0)

Currently it does not do (i)-(iii)

**Comment by hansthen** [comment]
That is not the purpose of the update_controller script. Its purpose is just to get the latest versions of all the files in controller ./rootimg. You can also get the latest versions of the tables, but that is not the default as it leaves the system in an undefined state. It is not possible to "merge" table definitions, or "undo" changes. If you want a pristine installation, you will have to reinstall.
