### ISSUE TITLE
xCAT postbootscripts: hostname -I gives multiple IPs as output

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#196]
We use the output hostname -I in cv_install_* scripts to dynamically get  IP address of the host in configuration files (e.g. packstack-answers.txt) . However for hosts with multiple IPs this breaks the installtion, e.g.

[root@controller ~]# hostname -I
192.168.1.2 10.141.255.254 10.148.255.254 

A quick workaround is to replace hostname -I with hostname -I | awk '{print $N}' where N=1,2,... depending on which IP address we want to use
[root@controller ~]# hostname -I | awk '{print $2}'
10.141.255.254

**Comment by hansthen** [comment]
hostname -i will work. It works via dns resolution of the hostname.

**Comment by hansthen** [comment]
hostname -i will work, but only if the hostname of the openstack node can be resolved via DNS. I created an even hackier workaround (check the IP address associated with ETH1).

**Comment by themisa** [comment]
fix for #277 updated this fix.

fixed in * r3
06c3594
