### ISSUE TITLE
No default password injection in current packstack installation

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#20]
When trying to boot instances (nova boot --flavor <flavor> --image <image> MYSERVER), an administrator password is generated (on console output). We should be able to use that  password to ssh into the instance. Currently not possible

**Comment by themisa** [comment]
Solution - edit  /etc/nova/nova.conf 
set: inject_password=true

This should be propagated to the openstack install script

**Comment by hansthen** [comment]
Turns out this is not necessary. password and key injection is a "developer convenience". In real life, this should be handled by the Image. This contains an application, CloudInit, which will call a metadata server to inject passwords and keys at runtime.

**Comment by hansthen** [comment]
Fixed with #28
