### ISSUE TITLE
monitoring: hosts reported

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#201]
Currently, check_mk reports all xcat hosts:
-controller
-switch
-node001-nodexxx
-login.vc-a
-c001-cxx

Only compute nodes have the monitoring agent installed, all other hosts are ping-checked.

Question: Do we want to keep all hosts visible? Or only compute (not containers)

**Comment by abhimukh** [comment]
Currently the monitoring installation tool will pick up everything that is defined as a node in the xCAT tables and add them to the monitoring server. Then during inventory (see RSA installation manual) it will try to find services to check. If the monitoring agent has been installed on the 'node' then it find a report services, else will simply show the pingability of the node. 
In the RSA installation manual we recommend that the agent be installed on the bare nodes only (they are mostly hardware checks) -- so nodes will have all kinds of checks while the containers (and switches) will be checked for pingability.

**Comment by abhimukh** [comment]
@hansthen Do we want to show only bare-metal nodes on the monitoring screen or containers (and switches) as well? (see, my previous comment)

**Comment by hansthen** [comment]
Question is more, in what situations do we want to be notified. I think it is not really useful to perform the exact same checks on trinity containers as on "real" nodes. However, I would like to see when a container is in a failure state. Second question: who can access the monitoring screen? Is that tenants or just the admin?

**Comment by abhimukh** [comment]
@hansthen Notification is different from what you see on the monitoring screen. The notification part can be fine tuned.
As far as what we see on the monitoring screen, you are absolutely right. Containers are not nodes, so most of the checks make no sense in the containers. In fact, right now the containers do not have the monitoring agent installed in them, so they can only be ping checked (so basically up/down).
The monitoring web interface is accessible to anyone who has access to the credentials (user/pass). However, the dashboard hook (not merged/not tested) allows the admin a loginless access to the web interface.

**Comment by abhimukh** [comment]
Will not fix this. This is not a bug. We simply need to make a decision on what should be shown on the monitoring screen (only physical nodes, or physical nodes + containers+switches etc). 

Assigning it back to @themisa to close if deemed proper.

**Comment by themisa** [comment]
Agreed. Will close. Can also be customized according to what customer wants. Ping tests on containers, login nodes etc is actually useful.
