### ISSUE TITLE
Dashboard: OpenStack dashboard is only accessible from the openstack node

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#206]
It needs to be accessible from the controller node as well.

**Comment by am-cra** [comment]
The dashboard should be accessible from any machine from which the openstack node is reachable.

**Comment by abhimukh** [comment]
dashboard is accessible from the controller by ip address, but not by hostname

[root@controller ~]# curl openstack/dashboard
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /dashboard was not found on this server.</p>
</body></html>
[root@controller ~]# curl 10.141.255.253/dashboard


<!DOCTYPE html>
<html lang="en" xml:lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    
    <title>Login - OpenStack Dashboard</title>
......

**Comment by abhimukh** [comment]
@themisa and @hansthen : I am not sure there is a bug here. As I mentioned in my previous comment, the dashboard __is__ accessible from the controller.

**Comment by abhimukh** [comment]
@themisa Could you please verify in the A env if the dashboard is accessible from the controller or not?

**Comment by themisa** [comment]
Yes, via ip ( not by hostname)
 [root@controller ~]# firefox 10.141.0.3/dashboard &

**Comment by themisa** [comment]
@hansthen Do we need this to work with hostname, or is ip ok?

**Comment by hansthen** [comment]
Needs to work with hostname as well:

firefox login.vc-a/dashboard & should work.

**Comment by abhimukh** [comment]
@hansthen Will not work with `firefox login.vc-a/dashboard`. The dashboard is hosted on the __physical__ openstack node, not in the login node (VM).  

Please see my comments under #359 . This should be closed.

**Comment by themisa** [comment]
should be openstack/dashboard.
