### ISSUE TITLE
Passwordless root login is possible from controller to container

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#208]
According to Hans, it should not be possible to do passwordless root login directly from the controller to the containers:

    [root@controller ~]# ssh c001.vc-a
    Last login: Mon May  4 13:51:09 2015 from controller.cluster
    [root@c001 ~]# ll
    total 0
    [root@c001 ~]# ll /trinity/clustervision/
    total 4
    dr-xr-xr-x 18 root root 4096 May  1 15:29 apps
    drwxr-xr-x  2 root root    6 May  1 15:29 modulefiles

This doesn't seem to be the case with the virtual login node though:

    [root@controller ~]# ssh login.vc-a
    root@login.vc-a's password:

Trinity version: 

    [root@controller ~]# cat /trinity/version 
    * exeter
    9f5a966

Best regards.

**Comment by hansthen** [comment]
From controller to container is not a problem. The user on controller is the "real root".
