### ISSUE TITLE
No default key injection in packstack installation (nova.conf)

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#21]
Still investigating whether this it the issue with launching instances with generated key-pair

**Comment by themisa** [comment]
Changed nova.conf 
# Inject the ssh public key at boot time (boolean value)
inject_key=true

rebooting nova-compute didn't help, but rebooting node did.

to ssh with key pair: 
nova keypair-add mykey > mykey.pem
chmod 600 mykey.pem

launch instance with key-pair : nova boot -- flavor <f> --key-name mykey --image <i> instancename
then ssh -i mykey.pem instancename 
voila!

**Comment by hansthen** [comment]
Maybe not necessary. See #28 for discussion. Needs verification.

**Comment by hansthen** [comment]
Fixed with #28
