### ISSUE TITLE
trinity_api requires all nodes to be in a hardware group

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#213]
If this is the case then we need to (automatically) create a default hw group, e.g. hw-all and make it possible for nodes to belong to multiple hardware groups. Otherwise, the trinity_api can just use all nodes named c\<nnn\>.

**Comment by abhimukh** [comment]
@hansthen and @themisa 
Assigning containers to unique hw groups is necessary for the current design to work. 
1. The pie charts which show free/allocated resources group containers by hw groups, if containers are assigned to multiple hw groups then this chart will be misleading
2. During repartitioning one needs to ask for number of containers per hw group. Again, multiple hw groups will break the logic here.

Using all node definitions named c<nnn> will not work for the same reason (the containers not assigned to any hw groups, have no logical place to show up in the dashboard).

One possible solution is to assign all the containers to a default group (say hw-GenericNodes), in the beginning. And then they can be reassigned later to more specialized hw groups.

**Comment by hansthen** [comment]
I am in favour of hw-GenericNodes. Where in the installation process should this be done?

**Comment by abhimukh** [comment]
When the containers are created in the xcat tables (nodeadd c<nnn>) they should be assigned to hw-GenericNodes.

nodeadd c<nnn> groups=hw-GenericNodes,vc-a

**Comment by hansthen** [comment]
I guess this is part of the installation/test procedures. Assigning to Themis for update of the procedures.

**Comment by themisa** [comment]
Modified test procedures:

As a generic installation procedure, assign all containers to hw-GenericNodes

mkdef -t group -o hw-GenericNodes
nodeadd c001-c002 groups=hw-GenericNodes

For testing:
 > mkdef -t group -o hw-FatNodes members=c001
 > mkdef -t group -o hw-GenericNodes members=c002
