### ISSUE TITLE
Docker on controller needs to be configured to use a different ip address

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#218]
Currently it uses an address in the range: 172.17.0.0. However, this conflicts with our own naming scheme.

**Comment by hansthen** [comment]
We can use: --bip=CIDR — supply a specific IP address and netmask for the docker0 bridge, using standard CIDR notation like 192.168.1.5/24.

See: https://docs.docker.com/articles/networking/#docker0

**Comment by themisa** [comment]
* r3
0d12eb5

on controller: (ip a)
```
: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 10.146.255.254/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
```
