### ISSUE TITLE
need to install xauth on compute nodes with nodeset

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#22]
no xauth right now on compute nodes using the current node installation.
Useful (openstack dashboard, graphical debuggers and profilers that need to be fired up directly from compute nodes etc)

**Comment by abhimukh** [comment]
Added the necessary package (xorg-a11-xauth) to the package list for trinity image. Trusted X11 Forwarding is enabled by default in Centos7. So, no change necessary in the ssh config file.

**Comment by themisa** [comment]
Need to install also on openstack and controller nodes. Or have a way to update pkglists with everything needed.

**Comment by themisa** [comment]
Fixed in * r3
74c8094

[root@node001 ~]# which xauth
/usr/bin/xauth

[root@openstack ~]# which xauth
/usr/bin/xauth
