### ISSUE TITLE
Login node creation: no home directory is created

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#221]
cloud-init[951]: mount.nfs: mounting 10.141.255.254:/home/vc-b failed, reason given by server: No such file or directory

**Comment by abhimukh** [comment]
@hansthen Could you please list the steps you took before running the tlntool create?
i.e., how was the installation done, what did you do from the dashboard etc?

**Comment by abhimukh** [comment]
@hansthen We did not encounter this issue during testing.

**Comment by abhimukh** [comment]
@hansthen The commit 96fba8f modifies (correctly) the yum installs in cv_install_xcat_ws to be non-interactive (in branch r4). I don't understand how it fixes this issue (#221). Maybe a typo?

**Comment by hansthen** [comment]
Yes typo. I meant fixes #222.

**Comment by abhimukh** [comment]
@hansthen Can we reproduce this bug in the A env? At least, in the r3 branch the cluster home directories /home/vc-<x> should be created by the API during cluster repartitioning.

**Comment by themisa** [comment]
cannot reproduce bug in A environment. The /home directories are created on repartitioning correctly...
[root@openstack ~(keystone_b)]# cd /home/
munge/   trinity/ vc-a/    vc-b/    

version: * r3
0d12eb5
