### ISSUE TITLE
Ldap: move to the old style ldap.conf configuration

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#222]
When setting up openldap, I used the slapd.d style configuration, as the old style slapd.conf is deprecated. However, most of the documentation and recipes on the internet still use old style slapd.conf.

**Comment by hansthen** [comment]
All required adaptations done. In cb5922e1 (r5_fix_222).

**Comment by themisa** [comment]
**Version:** r5_fixes 17e6458
**Environment:** amaster

```
[root@controller(unknown) testing]# more /etc/op
openldap/ opt/      
[root@controller(unknown) testing]# more /etc/openldap/slapd.conf 
include         /etc/openldap/schema/core.schema
include         /etc/openldap/schema/cosine.schema
include         /etc/openldap/schema/inetorgperson.schema
include         /etc/openldap/schema/nis.schema
include         /etc/openldap/schema/trinity.schema

pidfile         /var/run/openldap/slapd.pid

include         /etc/openldap/cv_local.conf
[root@controller(unknown) testing]# more /etc/openldap/slapd.d
/etc/openldap/slapd.d: No such file or directory
```

**Comment by themisa** [comment]
Note: in osimage, cv_install_slapd should come after cv_install_controller

**Comment by quentinleburel** [comment]
I know I am coming long after the battle, but we should have kept the
slapd.d style configuration.... RedHat will for sure drop the slapd.conf at
some point and then we will have to do this again....

On Thu, Aug 27, 2015 at 11:22 AM, themisa <notifications@github.com> wrote:

> Note: in osimage, cv_install_slapd should come after cv_install_controller
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clustervision/trinity/issues/222#issuecomment-135360746>
> .
>



-- 
[image: clustervision_logo.png]Quentin Le Burel
HPC Specialist
Engineering manager

Direct: +31 20 407 7550,271
Skype: quentin.leburel
quentin.leburel@clustervision.com
ClusterVision BV
Nieuw-Zeelandweg 15B
1045 AL Amsterdam
The Netherlands
Tel: +31 20 407 7550
Fax: +31 20 4077 551
www.clustervision.com

**Comment by hansthen** [comment]
I am aware of the risk. 

The reasons for moving into the deprecated area is that we wanted to do a large number of configuration changes to the LDAP (i.e. setup different backends, merge different directory trees etc.) Many of these are only documented properly using the old style of documentation. So for now it is simply easier to use the old style configuration.

We will move back to the new style configuration some time soon. In fact, if deprecation hits us hard, we can use a conversion tool to do the migration for us:

An existing slapd.conf(5) file can be converted to the new format using slaptest(8) or any of the slap tools:

        slaptest -f /usr/local/etc/openldap/slapd.conf -F /usr/local/etc/openldap/slapd.d

**Comment by themisa** [comment]
I will close this for now, as it has been merged in r6. We can reopen.
