### ISSUE TITLE
Trinity image: /etc/nslcd.conf 

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#223]
On the login node, we may need to remove a few spaces from the config file (at least it did not work until then), but adding the spaces had no effect afterwards.

We need to add `base group` etc to the nslcd.conf inside the trinity containers.

**Comment by hansthen** [comment]
nslcd.conf
# Customize certain database lookups.
base dc=cluster
base group  ou=Group,dc=cluster
base passwd ou=People,dc=cluster
base shadow ou=People,dc=cluster

**Comment by themisa** [comment]
confirmed changes in /trinity/compute
dtap
0e962cf
