### ISSUE TITLE
Docker creates an iptable rule on the compute node

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#224]
Docker creates an iptable rule on the compute nodes which should be removed, otherwise it can conflict with our network definitions.

[root@node001 ~]# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination

**Comment by hansthen** [comment]
I think a more proper way of phrasing the error is that the docker bridge should be created on a different IP address, one that will not conflict with our internal networks.

**Comment by hansthen** [comment]
This can be done using the --bip=CIDR and --fixed-cidr=CIDR options to docker startup. These can be set in /etc/sysconfig/docker, using the OPTIONS variable. I propose that we reserve the 192.168.10.*/8 address range for docker.

**Comment by abhimukh** [comment]
@hansthen This is a different issue. We need the docker bridge on the controller (which runs the docker registry), and there we indeed need to set up non-conflicting IP addresses. However, the issue I flagged had to do with the compute nodes. On the compute nodes we remove the docker bridge. however, a stale iptable rule remains. This rule should be removed.
I am reverting the title of this issue back to the original one, and opening a new issue related to the IP addresses used by the Docker bridge.

**Comment by hansthen** [comment]
Sorry, did not pay attention when closing this issue. The issue still remains. @abhimukh can you fix it?

**Comment by abhimukh** [comment]
Fixed in r3 : fb21063d1c1610b5d16822271ccc5abebfe5f4aa
Also, the docker bridge now removed in the trinity postinstall script, not in the container startup script.

**Comment by abhimukh** [comment]
@themisa you can test this in the following manner
[root@node002 ~]# iptables -nvL | grep -i docker
[root@node002 ~]# iptables -nvL -t nat | grep -i docker
[root@node002 ~]# ip a | grep docker

these commands should not give any output on the nodes.

**Comment by themisa** [comment]
* r3
0d12eb5
```
root@node002 ~]# iptables -nvL | grep -i docker
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
Chain DOCKER (1 references)
[root@node002 ~]# iptables -nvL -t nat | grep -i docker
   13  1055 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
Chain DOCKER (2 references)
[root@node002 ~]# ip a | grep  docker
7: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    inet 172.17.42.1/16 scope global docker0
```

Also, brctl is not available in the image anymore...#278

**Comment by themisa** [comment]
note: need to add cv_cleanup_networking as postbootscript. should this be done manually?
@hansthen, @abhimukh
