### ISSUE TITLE
Docker containers should have at least one decent editor

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#225]
Currently the containers come with the default OS supplied editor (vi). However, for any sort of text editing work they should have at least one 'smart' editor (vim or emacs or ..)

**Comment by hansthen** [comment]
I do not understand the requirement. The editor installed in the containers _is_ vim.

```
[root@c002 /]# rpm -ql vim-minimal | grep /usr/bin/vi
/usr/bin/vi
/usr/bin/view
```

**Comment by abhimukh** [comment]
vi != vim

[abhi@dmaster trinity]$ rpm -ql vim-minimal | grep vim
/usr/share/man/man1/vim.1.gz
[abhi@dmaster trinity]$ rpm -ql vim-enhanced | grep vim
/etc/profile.d/vim.csh
/etc/profile.d/vim.sh
/usr/bin/rvim
/usr/bin/vim
/usr/bin/vimdiff
/usr/bin/vimtutor
Will also need vim-common

**Comment by abhimukh** [comment]
"The vim-minimal package includes a minimal version of VIM, which is installed into /bin/vi for use when only the root partition is present."

**Comment by hansthen** [comment]
Why assign this to me?

**Comment by hansthen** [comment]
I think I accidentally fixed this.

**Comment by themisa** [comment]
[root@c001 /]# which vim
/usr/bin/vim

accidentally fixed :)

* dtap
e953fd8
