### ISSUE TITLE
creating users doesn't set default bash profile

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#228]
Noticed this when using a normal user created on the login node:

    [root@hokusai ~]# su - john
    Last login: Fri May  1 11:39:35 UTC 2015 from login-a.vc-a on pts/1
    -bash-4.2$ pwd
    /home/john
    -bash-4.2$ ls -la
    total 8
    drwxr-xr-x.  3 john john   37 May  1 13:00 .
    drwxr-xr-x. 10 root root 4096 May  6 11:42 ..
    -rw-------.  1 john john   50 May  1 13:01 .bash_history
    drwxr-xr-x.  2 john john   71 May  1 12:38 .ssh

This probably happens because at user creation the content of /etc/skel is not added to the user's home directory:

    [root@hokusai skel]# pwd
    /etc/skel
    [root@hokusai skel]# ls -la
    total 24
    drwxr-xr-x.  2 root root   59 Mar 31 12:21 .
    drwxr-xr-x. 80 root root 8192 May  6 10:15 ..
    -rw-r--r--.  1 root root   18 Mar  5 22:06 .bash_logout
    -rw-r--r--.  1 root root  193 Mar  5 22:06 .bash_profile
    -rw-r--r--.  1 root root  231 Mar  5 22:06 .bashrc

If I add manually those files in the user's home directory I have:

    -bash-4.2$ cp /etc/skel/.bash_logout .
    -bash-4.2$ cp /etc/skel/.bash_profile .
    -bash-4.2$ cp /etc/skel/.bashrc .
    -bash-4.2$ exit
    logout
    [root@hokusai ~]# su - john
    Last login: Fri May  8 08:09:36 UTC 2015 on pts/0
    [john@hokusai ~]$ 

This but was detected in the exeter branch

    [root@hokusai ~]# cat /trinity/version 
    * exeter
    9f5a966

**Comment by hansthen** [comment]
Fix for #228

**Comment by hansthen** [comment]
Assigned to themis for testing.

**Comment by themisa** [comment]
Fixed. tested in *r3 and *dtap

```
[root@login ~]# ssh -Y jane@login.vc-b
Warning: Permanently added 'login.vc-b,172.17.255.254' (ECDSA) to the list of known hosts.
jane@login.vc-b's password: 
Last login: Wed Jun  3 14:39:43 2015
[jane@login ~]$ 

jane@login ~]$ ssh c001
[jane@c001 ~]$ 
```
