### ISSUE TITLE
Docker containers: the macvlan should be created on the first __up__ ethernet interface

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#229]
Sometimes, the node may have multiple ethernet interfaces, but the first one may not be usable. 
The macvlan which is used to assign IP addresses to the docker containers, should be created on the first ethernet interface  which is __up__ on the bare metal node, not on the first available interface. Otherwise, the containers will not be reachable from outside the node.

**Comment by abhimukh** [comment]
One way to fix this this issue is to modify the trinity startup script: _/etc/init.d/trinity_

    # determine the ethernet device name
    ##  read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
    read IF1 IF2 IF3 IF4 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -4)
    for IF in ${IF1} ${IF2} ${IF3} ${IF4}; do
      if grep up /sys/class/net/${IF}/operstate; then
        ETH1=$IF
        break
      fi
    done

**Comment by themisa** [comment]
source code looks good. hard to test physically. Also, merge this branch into r3 + dtap.

**Comment by hansthen** [comment]
We can test this by connecting the compute nodes on their second interface.
