### ISSUE TITLE
Architecture: Remove the initial default virtual cluster (vc-a)

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#231]
Currently, during installation of the xCAT controller a nodegroup is created, called vc-a, and all the containers c<nnn> are allocated to it. However, at this time there is no OpenStack tenant called `a'. 
The tenant `a` (and the corresponding user `a') is created later, after the installation of the OpenStack controller. 
This creates a special case situation, reversed from the standard case where the tenant is created first from the dashboard, and the nodegroup is created automatically when HPC resources are allocated to the tenant for the first time.

The special case necessitates many manual workarounds (the alternative is spaghetti code!) and should be removed.

**Comment by hansthen** [comment]
I'm okay with the change, but I will want the installation procedure to be adapted so that as part of the tests we create a default cluster.

**Comment by hansthen** [comment]
We can migrate all our current "templates" and stuff to work with vc-0 as the template directory.

**Comment by hansthen** [comment]
I am having second thoughts about this proposal. What I want is the following:

At the end of use case 1.2 
1. a default cluster is created (vc-a) containing all nodes.
2. a default login node is created login-a

Engineers should be able to do this from the command line, without having to login to the OpenStack dashboard or having to partition the cluster. The target is that in as little steps as possible, we can create a simple default cluster. 

We may be able to rewriting use case 1.2 in the following manner:
1. Get all nodes into the genesis kernel on standby mode.
2. First provision the OpenStack node: automatically create tenant a and login-a.
3. Next provision all the trinity nodes and allocate them to vc-a.

**Comment by abhimukh** [comment]
in r5 the tenant and the login node for the default cluster is created during openstack node provisioning. 
Assigning to @themisa for further testing.

**Comment by themisa** [comment]
@hansthen : this is what happens now. (r5)

But: nodes sorted in hardware groups before provisioning.
Possible to also sort them after, just do service trinity_api restart on openstack node.

I think this enhancement can be closed.
