### ISSUE TITLE
The 'openstack' hostname should point correctly to the OpenStack controller in the entire cluster

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#232]
To setup setup stateless xCAT images for nova-compute and cinder we need to be able to point  correctly to the OpenStack controller, independent of the specifics of the installation. For this to work the hostname 'openstack' should resolve to the correct IP address of the openstack controller node.

**Comment by hansthen** [comment]
This is a procedure that should always be followed in any case. I installed it like that for the exeter cluster. Simply define the openstack node as a separate node in xCAT and create a corresponding host entry for it.

**Comment by hansthen** [comment]
Assigned to Themis for QA verification (and for updating the test procedures, so instead of using node003, we define an openstack node.

**Comment by themisa** [comment]
This procedure is on amaster:

Edit the hosts table to include an openstack entry:
```
"openstack","10.141.0.3","openstack","openstack-bmc:10.148.0.3",,
```

Edit switch table to add entry:
```
"openstack","switch","fa3",,,,
```

(switch port depends on environment)

makehosts and dns.

@hansthen, i propose to push these changes in git (default xcat tables)

**Comment by hansthen** [comment]
I largely agree:

A few small additions:
- hosts table: use a different ip address, so there will be no conflict with regular nodes 
-> e.g. use 10.141.255.250
- add a nodelist entry for openstack and make it member of compute
(if we do that we do not need to add entries to nodehm and ipmi)

**Comment by hansthen** [comment]
Reopening and assigning to Themis

**Comment by themisa** [comment]
Change hosts table to:
```
"openstack","10.141.255.250","openstack","openstack-bmc:10.148.255.250",,
```

(Note: first time rpower manually)

**Comment by themisa** [comment]
```
[root@controller(unknown) ~]# host openstack localhost
Using domain server:
Name: localhost
Address: 127.0.0.1#53
Aliases: 

openstack.cluster has address 10.141.255.250
```

**Comment by themisa** [comment]
```
[root@controller(unknown) testing]# ping openstack
PING openstack (10.141.255.250) 56(84) bytes of data.
64 bytes from openstack (10.141.255.250): icmp_seq=1 ttl=64 time=0.261 ms
64 bytes from openstack (10.141.255.250): icmp_seq=2 ttl=64 time=0.235 ms
^C
--- openstack ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.235/0.248/0.261/0.013 ms
[root@controller(unknown) testing]# ssh node001
Last login: Wed Sep  2 12:32:02 2015 from controller.cluster
[root@node001 ~]# ping openstack
PING openstack.cluster (10.141.255.250) 56(84) bytes of data.
64 bytes from openstack.cluster (10.141.255.250): icmp_seq=1 ttl=64 time=0.484 ms
64 bytes from openstack.cluster (10.141.255.250): icmp_seq=2 ttl=64 time=0.273 ms
64 bytes from openstack.cluster (10.141.255.250): icmp_seq=3 ttl=64 time=0.299 ms
64 bytes from openstack.cluster (10.141.255.250): icmp_seq=4 ttl=64 time=0.270 ms
^C
--- openstack.cluster ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 0.270/0.331/0.484/0.090 ms
```
