### ISSUE TITLE
All-in-one controller installation: ip address confusion

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#234]
**Software:** * allinone
8b79a29
**Component:** controller/openstack installation
**Hardware:** SM controller02
**Test case:** n/a
**Bug description:** 
When doing an all-in-one install, we get an error in /var/log/xcat/xcat.log:
ERROR : Failed handling answer file: Given host is not in IP address format: controller

The openstack services will not start, and the installation proceeds with xcat installation, without openstack up and running as it should
**Steps to reproduce:**
**Expected output:**
**Actual output:**

**Comment by abhimukh** [comment]
All in one is included in r6 (with dockerize). This should be closed.

**Comment by themisa** [comment]
Fixed in dockerize. All openstacks services run in containers on the xcat controller node. 
From r6.
