### ISSUE TITLE
cv_install_xcat  looking for non-existing file

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#237]
[root@controller ~]# cat /trinity/version
    * r3
    5f69dc2

The base installation completes successfully, however the xcat installation postscript is unable to complete and breaks the rest of the installation, because xcat commands are not available.
Seems that while trying to install packages from the `xcat-dep` repository, yum is unable to find one specific file.

Here is an excerpt from the `/var/log/xcat/xcat.log`

    Fri May 15 15:33:27 CEST 2015 Running postscript: cv_install_xcat
    CentOS-Base.repo
    CentOS-Debuginfo.repo
    CentOS-Sources.repo
    CentOS-Vault.repo
    local-repository.repo
    xCAT-core.repo
    xCAT-dep.repo
    Loaded plugins: fastestmirror
    https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh7/x86_64/repodata/6241f9c837d404441b6ee4abb13784b54e101e3a-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.

**Comment by linuxstudio** [comment]
I noticed that the xcat-dep repository gets modified explicitly by the cv_install_xcat postinstall script, which excludes the net-snmp-perl package.

There is however an update on this: (see changelog of the xcat-dep tarball)
* Tue, 28 Apr 2015 16:05:35 +0800 GONG Jie <gongjie@linux.vnet.ibm.com>
Package net-snmp-perl has been recompiled for RHEL 7.x on ppc64, ppc64le and
  x86_64.

**Comment by linuxstudio** [comment]
Seems really a problem with the sourceforge repository.
Did these steps manually, and get the same error:

    [root@controller ~]# wget downloads.sourceforge.net/project/xcat/yum/xcat-dep/rh7/x86_64/xCAT-dep.repo
    
    [root@controller ~]# diff /etc/yum.repos.d/xCAT-dep.repo xCAT-dep.repo 
    7d6
    < exclude=net-snmp-perl
    
    [root@controller ~]# cp xCAT-dep.repo /etc/yum.repos.d/xCAT-dep.repo
    cp: overwrite ‘/etc/yum.repos.d/xCAT-dep.repo’? y
    
    [root@controller ~]# yum clean all
    
    [root@controller ~]# yum install xCAT

**Comment by hansthen** [comment]
This sometimes happens when sourceforge is down. There are some other issues with the install script as we need to use xcat-dep rh7.0 repositories, but those should be in a different issue report.

**Comment by hansthen** [comment]
Since the problem is related to sourceforge stability, we'll not solve this.
