### ISSUE TITLE
postinstall.log may contain misleading info

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#238]
[root@controller ~]# cat /trinity/version
    * r3
    5f69dc2

I have found at least one case in which even if some post install script didn't complete successfully, this logfile was showing a very reassuring content:

    [root@controller xcatpost]# cat /var/log/postinstall.log 
    xcat installed
    slapd installed
    docker installed

See issue #237 

We should make sure that if a post_install script completes with errors, then the log file should report that. This in my opinion is a bug.

**Comment by hansthen** [comment]
Duplicate
