### ISSUE TITLE
Dashboard: create cluster not necessary

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#24]
The dashboard now has a separate notion of a HPC cluster, which can be created independently from a tenant. This is not right. The tenant or project is the entity that is created. HPC resources are simply allocated to that entity.

This means that the HPC screen should not show a list of "clusters", but a list of all tenants.

**Comment by hansthen** [comment]
Moved to M3.

**Comment by abhimukh** [comment]
Fixed. HPC overview now shows all tenants except for the 'services' tenant.
