### ISSUE TITLE
controller installation: copycds mount error

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#241]
**Software:** master_installer 6739973
**Component:** install controller
**Hardware:** SM controller02
**Test case:** 1.1.3
**Bug description:**
```
Error: copycds was unable to mount /tmp/trinity/iso/CentOS-7-x86_64-Everything-1503-01.iso to /var/run/xcat/mountpoint/1667e77bc458f0f585441d67c6894e6b.
```
**Steps to reproduce:**
```
nodeset controller02 osimage=centos7.0-x86_64-install-controller
rpower controller02 reset
ssh controller02
 cat /var/log/xcat/xcat.log | grep -i "error"
```
**Expected output:**
No error messages

**Comment by hansthen** [comment]
This was caused by an invalid *.iso file in /trinity/isos

**Comment by themisa** [comment]
Fixed by installing correct iso in master: /trinity/iso
