### ISSUE TITLE
openstack node installation: Fails. "infinite loop" provisioning

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#244]
**Component:** master_installer 
**Version:**6739973
**Hardware:** node003 (from amaster)
**Test case:** 1.2.5
**Bug description:**
When provisioning an openstack node from the controller, the installation goes on an infinite loop. (on a different occasion this was due to the inability to download the base image from the internet).

**Steps to reproduce:**
> nodeset node003 osimage="centos7.0-x86_64-install-openstack"
> rpower node003 reset
> watch nodestat node003
**Expected output:**
**Actual output:**
watch reports installing..., then installing post, then noping, and instead of going to sshd, goes right bach to installing,,, installing post, etc in an infinite loop

**Comment by themisa** [comment]
Could be related to fix for #163 ?
#FIXME: hack to fix #163. Should be removed when merging master_installer branch.
rm /etc/yum.repos.d/CentOS-Vault.repo || true
yum update

**Comment by themisa** [comment]
New theory:
[root@controller autoinst]# cat /proc/cmdline | grep http | head -n 1
returns null

**Comment by themisa** [comment]
From console:
cmdlineError: Missing package: openstack-nova-api

**Comment by hansthen** [comment]
>>> then installing post, then noping, and instead of going to sshd, goes right bach to installing,,, installing post, etc in an infinite loop

This means one of the postscripts failed. The suggested method of debugging:
1. remove all postscripts from the osimage/linuximage
2. run the postscripts one by one manually to see where exactly it fails

**Comment by themisa** [comment]
Remove all postbootscripts (slapd, openstack, api, dash, login). Still will not provision,
```
[root@controller ~]# lsdef -t osimage -o centos7.0-x86_64-install-openstack
Object name: centos7.0-x86_64-install-openstack
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.0-x86_64
    osname=Linux
    osvers=centos7.0
    profile=openstack
    provmethod=install
```

**Comment by abhimukh** [comment]
@hansthen I noticed that the openstack packages have been moved to openstack.pkglist in the the master_installer branch. Shouldn't they be in openstack.otherpkgs?

**Comment by themisa** [comment]
Commenting out all packages under openstack in: install/custom/install/centos/openstack.pkglist
```
#Please make sure there is a space between @ and group name
wget
ntp
nfs-utils
net-snmp
rsync
yp-tools
openssh-server
util-linux-ng
net-tools

# X fwding
xorg-x11-xauth
yum-utils
bind-utils

# OpenStack packages
#openstack-keystone
#python-keystoneclient
#openstack-glance
#python-glanceclient
#openstack-nova-compute
#sysfsutils
#openstack-nova-network
#openstack-nova-api
#openstack-dashboard
#httpd
#mod_wsgi
#memcached
#python-memcached
```

allowed the base image to be installed

**Comment by hansthen** [comment]
Yes, but I have no idea why that is. It is wrong anyway.

**Comment by themisa** [comment]
fixed in * master_installer
42c4bc2
