### ISSUE TITLE
PAM on login node should be configured to autocreate the /home directories for users

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#245]
This entails a bit more than just:
`session required pam_mkhomedir.so skel=/etc/skel/ umask=0022` to /etc/pam.d/sshd.

pam_mkhomedir is incompatible with selinux. So we need to either disable selinux inside the login node or install a special package oddjob-mkhomedir.

**Comment by hansthen** [comment]
Also, if that is the case, we need obol to not create home directories automatically.

**Comment by hansthen** [comment]
Fixed in da5f971e835

**Comment by themisa** [comment]
jane@login.vc-new's password: 
Creating home directory for jane.

Implemented. Tested in 
[jane@login ~]$ /trinity/report
**Version:** r5_fixes a48a1b7
**Environment:** dmaster
