### ISSUE TITLE
Partition cluster needs to create a default /cluster/etc/.modulespath

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#247]
I have updated the Trinity startup script to look for this file there. This makes it easy to update the modulespath without having to rebuild the compute image.

**Comment by hansthen** [comment]
To do this: place the .modulespath in /cluster/vc-0.

**Comment by hansthen** [comment]
Assign to Themis for testing.

**Comment by themisa** [comment]
@hansthen : so this should be a procedure?

**Comment by abhimukh** [comment]
Fix for #250 should also have fixed this.

**Comment by themisa** [comment]
fix for 250 fixes this. must confirm for r3. Closing for dtap
