### ISSUE TITLE
API and Dash install scripts : fails to mount /trinity from controller

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#249]
The cv_install_api and cv_install_dash files fail because /trinity cannot be mounted from the controller on the openstack node.
This is the error message:
mount.nfs: access denied by server while mounting controller:trinity

**Comment by abhimukh** [comment]
Fixed in r4. There was a typo in the cv_install_* scripts.

**Comment by themisa** [comment]
works in * r3
0d12eb5
