### ISSUE TITLE
modulespath incorrect on virtual login node

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#250]
The modulespath should point to both the global modules dir and the local one for the virtual cluster.
At the moment this is true for the containers, but not for the login node:

    [root@c001 init]# pwd
    /usr/share/Modules/init
    [root@c001 init]# cat .modulespath
    /usr/share/Modules/modulefiles  # Module pkg modulefiles (if no versioning)
    /etc/modulefiles                                # General module files
    #/usr/share/Modules/your_contribs                       # Edit for your requirements
    /trinity/clustervision/modulefiles
    /cluster/modulefiles

     [root@athena init]# pwd
    /usr/share/Modules/init
    [root@athena init]# cat .modulespath
    /usr/share/Modules/modulefiles  # Module pkg modulefiles (if no versioning)
    /etc/modulefiles                                # General module files
    #/usr/share/Modules/your_contribs                       # Edit for your requirements
    /trinity/clustervision/modulefiles

Notice that the container is nfs-mounting that file from the controller:

    [root@c001 ~]# mount
    controller:/cluster/vc-a/.modulespath on /usr/share/Modules/init/.modulespath type nfs

while the login node doesn't nfs-mount that file. It uses a local copy (maybe created by some installation script)

This issue was detected on the exeter branch:

    [root@athena ~]# cat /trinity/version 
    * exeter
    9f5a966

**Comment by abhimukh** [comment]
Fixed in R4

**Comment by themisa** [comment]
Cannot see module from /trinity/clustervision (or /cluster)

in * r3
0d12eb5

```
[root@login init]# module avail

------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles --------------------------------------------------------------------------------------
dot         module-git  module-info modules     null        use.own
```

**Comment by themisa** [comment]
there is no .modulespath in /cluster/vc-0/etc

```
[root@openstack ~(keystone_b)]# ls -al /cluster/vc-0/etc
total 0
drwxr-xr-x 3 root root 18 May 27 17:49 .
drwxr-xr-x 5 root root 64 May 27 17:49 ..
drwxr-xr-x 2 root root 68 May 27 17:49 slurm
```

**Comment by hansthen** [comment]
Yes it is, but it is in /cluster/vc-0 (as it should be).
```
[root@master vc-0]# ls -la
total 4
drwxr-xr-x 5 root root  64 May 26 16:03 .
drwxr-xr-x 4 root root  28 May 18 13:47 ..
drwxr-xr-x 2 root root  23 May 18 13:47 apps
drwxr-xr-x 3 root root  18 May 18 13:47 etc
drwxr-xr-x 2 root root  23 May 18 13:47 modulefiles
-rw-r--r-- 1 root root 289 May 26 16:03 .modulespath
```

**Comment by abhimukh** [comment]
Indeed, the symlink was pointing to the wrong file. Should be fixed in r3 now.

**Comment by themisa** [comment]
still not fixed in * r3
06c3594

```
[root@login home]# module avail

--------------------------------------------------------------- /usr/share/Modules/modulefiles ---------------------------------------------------------------
dot         module-git  module-info modules     null        use.own
```

**Comment by themisa** [comment]
fixed in * dtap
0e962cf
