### ISSUE TITLE
cluster partitioning: slurm reporting on containers not assigned to a virtual cluster

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#252]
**Software:** *exeter 9f5a966
**Component:** slurm
**Hardware:** 
**Test case:** 3.2.2
**Bug description:**
Made 2 partitions in cluster. One is the original vc-a, then added vc-d and assigned it 2 containers.
Slurm reports correctly on the containers of vc-d (c002, c003), but vc-a (athena) still "remembers" owning c002-c003, at least marking them as down. This has not been the case in other branches, where containers removed from a virtual cluster are not accounted for by slurm
```
root@athena ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      3  down* c[002-003,007]
compute*     up   infinite      4   idle c[001,004-006]
```

**Steps to reproduce:**
**Expected output:**
**Actual output:**

**Comment by hansthen** [comment]
Looks like this happens in partitioning. However, we may need to use "reservations" to make sure that nodes move from one cluster to another and not have to restart cluster nodes. This means that all clusters can "see" all nodes, even ones not allocated to them. I will write a TrIP.

**Comment by abhimukh** [comment]
@themisa Can you verify that this does not happen in r3? I which case, it could be an issue with the manual install.
@hansthen We do not move _nodes_, but _containers_ during partitioning. According to M3/M4 design containers contain the environment, when containers are taken away they should become invisible to slurm (upon restart). 
Resaaigning.

**Comment by hansthen** [comment]
Why assign this to me?

**Comment by themisa** [comment]
@abhimukh, this still happens in *r3.

I removed 2 containers from vc-a, and from login-a they are reported as down instead of invisible

[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      2  down* c[001-002]

**Comment by themisa** [comment]
when re-partitioning, tenant  needs to do a tlntool update, or restart slurm.
