### ISSUE TITLE
user authentication: fails when creating new virtual clusters

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#253]
Exeter branch.
Created new cluster vc-d. User authentication needs manual intervention. 

root@login.vc-d's password: 
Last login: Thu May 21 09:15:11 2015 from login-a.vc-a
[root@login ~]# systemctl restart nslcd
[root@login ~]# su - mds207
su: user mds207 does not exist
[root@login ~]# cp /cluster/etc/nslcd.conf /etc/
cp: overwrite ‘/etc/nslcd.conf’? y
[root@login ~]# systemctl restart nslcd
[root@login ~]# su - mds207
su: warning: cannot change directory to /cluster/data/home2/ISAD/mds207: No such file or directory

**Comment by hansthen** [comment]
Authentication does not fail, but this cluster does not have the correct /home directory mounted. Either change the /etc/nslcd.conf for this cluster, or update /etc/fstab to mount the /cluster/data directory.

**Comment by hansthen** [comment]
Probably best to  do the following:
on athena mount the storage currently under /cluster/data/home2/ISAD as /home.
change nslcd.conf (everywhere) to point to /home for the home directories. Rule of least suprise.

**Comment by hansthen** [comment]
This issue is only for one specific customer, and is not so much a bug as a configuration question.
