### ISSUE TITLE
Architecture: rewrite cv_install_controller so it can be run without a master node

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#258]
This is useful in case we need to install a controller from scratch.

**Comment by hansthen** [comment]
I created the "masterless" branch for this feature. Basically, it expects that someone installs a node from a USB key, downloads the trinity repository and then runs cv_install_controller manually. That script will check if it can find a master. If not, it will get the required files from the internet instead of from the master.

**Comment by hansthen** [comment]
Assigned to themis for testing that branch (as soon as the other branches are tested as well).

**Comment by themisa** [comment]
I will close this bug. Masterless branch has been created and tested.

Installed a controller without a master. A procedure has been created and a testing log exists for this branch.

Further bugs pertaining to this branch can be independently opened.
