### ISSUE TITLE
Dashboard: automatically create login node

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#26]
It is not possible or easy to create a login node from the dashboard. This should be automated somehow (e.g assign the login node to the slurm configuration)

Items to be considered:
- when should the login node be created? 
a) at cluster creation time?, but see the issue about cluster creation
b) when we first allocate resources to a cluster
c) manually

- how do we configure the login node?
a) (manually) create a custom image for it
b) use something similar to CloudInit and a metadata server
c) setup a container
d) use Puppet

**Comment by abhimukh** [comment]
I have created a tool for automated creation of login node.
Dashboard hook is not in scope for M3 
Assigning this to @themisa

**Comment by themisa** [comment]
tlntool - tool for creation of login node. Works .

**Comment by abhimukh** [comment]
Now, this has also been merged into r4 : ea2a0530f293dda6923482015161e3416f132cee

**Comment by themisa** [comment]
* r4
972ccbe

Now when resources are moved for first time into a virtual cluster, login node is automatically created for that cluster without tlntool setup/create.
