### ISSUE TITLE
controller: needs to have a reliable NTP source configured

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#260]
By default the controller has NTP activated and pointing to the DHCP server from which got it's external IP address (in this case the master, from which was installed):

    [root@controller ~]# cat /etc/ntp.conf 
    driftfile /var/lib/ntp/drift
    disable auth
    restrict 127.0.0.1
    server  127.127.1.0
    fudge   127.127.1.0 stratum 10
    server 192.168.1.254   # added by /sbin/dhclient-script

We should make sure that `/etc/ntp.conf` contains a reliable ntp source, like `pool.ntp.org`. 

We should also make sure that the ntp.service is active and running. 
This is e.g. not the case in Exeter:

    [root@controller ~]# systemctl status ntpd.service
    ntpd.service - Network Time Service
       Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled)
       Active: inactive (dead)

even if the `/etc/ntp.conf` is configured correctly (centos default):

    [root@controller ~]# cat /etc/ntp.conf | grep -e ^server
    server 0.centos.pool.ntp.org iburst
    server 1.centos.pool.ntp.org iburst
    server 2.centos.pool.ntp.org iburst
    server 3.centos.pool.ntp.org iburst

**Comment by themisa** [comment]
```
oot@controller clusterbats]# service ntpd status
Redirecting to /bin/systemctl status  ntpd.service
ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; enabled)
   Active: active (running) since Wed 2015-05-27 23:05:23 CEST; 10h ago
  Process: 5253 ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5254 (ntpd)
   CGroup: /system.slice/ntpd.service
           5254 /usr/sbin/ntpd -u ntp:ntp -g
```

```
[root@controller clusterbats]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 LOCAL(0)        .LOCL.          10 l  10h   64    0    0.000    0.000   0.000
*amaster.cluster LOCAL(0)        11 u  631 1024  377    0.161   -0.007   0.026
```

**Comment by linuxstudio** [comment]
This still points to the NTP source on amaster.cluster (the one which
assigned a dhcp address to the external interface).
Would be better that a controller, being a node that has to give reference
time to all the nodes in a cluster, refers directly to a reliable time
source, like pool.ntp.org.

If you leave it like this, you rely implicitly on the local dhcp server,
and are assuming that it is correctly configured with a reference to a
reliable time source. This is not always the case.

**Comment by linuxstudio** [comment]
I will fix manually the ntp on the controller node in Exeter, as per request from @hansthen

**Comment by themisa** [comment]
@linuxstudio could you also fix in r3?

**Comment by linuxstudio** [comment]
This issue affects also the openstack node:

```
[root@openstack ~]# systemctl status ntpd.service
ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled)
   Active: inactive (dead)

[root@openstack ~]# ntpq -p
ntpq: read: Connection refused
```

The origin of this for the openstack node seems to be in the packstack answers file:

```
[root@openstack ~]# cat /tmp/packstack-answers.txt | grep CONFIG_NTP_SERVERS
CONFIG_NTP_SERVERS=
[root@openstack ~]# cat /trinity/version 
* dtap
8373a27
```

**Comment by hansthen** [comment]
I do not see the seriousness of the problem. If the local dhcp server does not provide a stable ntp server (or if we cannot use dhcp) engineers can set the ntp server as required.

**Comment by hansthen** [comment]
If we do not want the dhclient to set the dhcp server, we can remove ntp.sh from /etc/dhclient.d/.

**Comment by hansthen** [comment]
Assigning to themisa for verification.

**Comment by hansthen** [comment]
Added a default ntp server and removed the dhcp based ntp server assignment.

**Comment by hansthen** [comment]
In r5_fixes now.

**Comment by themisa** [comment]
**Version:** r5_fixes 27d630c
**Environment:** amaster

```
[root@controller(amaster) ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
x192.168.1.254   LOCAL(0)        11 u  249  256  377    0.155  256832.  10.041
+pfsense01.steam 181.92.40.112    3 u  224  256  377    3.528   13.626  10.224
+elite7hackers.n 31.3.104.60      3 u  232  256  377    2.000   12.166  14.421
*metronoom.dmz.c .PPS.            1 u  223  256  377    4.179   10.424   5.821
-pfsense02.steam 216.239.34.15    3 u   95  256  377    3.471   12.726   2.630
```

**Comment by hansthen** [comment]
**Version:** r5_fixes ad0fa7e
**Environment:** unknown

```
[root@controller(unknown) ~]# tail -5 /etc/ntp.conf 

# Key file containing the keys and key identifiers used when operating
# with symmetric key cryptography.
keys /etc/ntp/keys
```

**Comment by themisa** [comment]
Fixed in:

root@controller(amaster) trinity]# /trinity/report
**Version:** r5_fixes c2dc5c0
**Environment:** amaster
```
[root@controller(amaster) trinity]# tail -5 /etc/ntp.conf 

# Key file containing the keys and key identifiers used when operating
# with symmetric key cryptography.
keys /etc/ntp/keys
```

```
[root@controller(amaster) trinity]#  ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+transporteer.al 195.13.1.153     3 u   28 1024  377    3.460    0.203   1.264
+skv-03.netvisit 193.79.237.14    2 u  829 1024  377    5.017   -1.240   6.036
+x.ns.gin.ntt.ne 82.95.215.61     2 u  415 1024  377    2.836    1.315   1.220
*services.freshd 213.136.0.252    2 u  945 1024  377    4.636    0.431   1.142
x192.168.1.254   LOCAL(0)        11 u  788 1024  377    0.173  263851.  54.528
```

**Comment by themisa** [comment]
needs to be merged in r6.

**Comment by themisa** [comment]
* r6
6859708

Even though it is merged 
```
[root@tmaster(tmaster) trinity]# ./includes c2dc5c0dc4b
git merge-base --is-ancestor c2dc5c0dc4b 6859708
included
```

i still don't get an "outside" ntp server on the controller

```
[root@controller(unknown*) ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l    6   64  377    0.000    0.000   0.000
[root@controller(unknown*) ~]# /trinity/report
cat: /trinity/site: No such file or directory
**Version:** r6 6859708
**Environment:** unknown
```

```
[root@controller(unknown*) ~]# cat /etc/ntp.conf 
driftfile /var/lib/ntp/drift
restrict default kod nomodify notrap nopeer noquery
restrict -6 default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict -6 ::1

# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (http://www.pool.ntp.org/join.html).
server 0.centos.pool.ntp.org iburst
server 1.centos.pool.ntp.org iburst
server 2.centos.pool.ntp.org iburst
server 3.centos.pool.ntp.org iburst

# Enable public key cryptography.
#crypto

includefile /etc/ntp/crypto/pw

# Key file containing the keys and key identifiers used when operating
# with symmetric key cryptography.
keys /etc/ntp/keys

```

**Comment by hansthen** [comment]
[root@controller-1(unknown*) ~]# systemctl restart ntpd.service
[root@controller-1(unknown*) ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*menotios.justfo 193.67.79.202    2 u    1   64    1    8.815   -1.275   0.000
 ntp1.edutel.nl  80.94.65.10      2 u    -   64    1    6.522   -0.961   0.000
 huggyshifters.c .INIT.          16 u    -   64    0    0.000    0.000   0.000
 x.ns.gin.ntt.ne .INIT.          16 u    -   64    0    0.000    0.000   0.000

**Comment by themisa** [comment]
**Version:** r6 8b08aa5
**Environment:** tmaster

ok, it works correctly after a restart. Should we automate that?

```
[root@controller(unknown*) ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*LOCAL(0)        .LOCL.          10 l   10   64  377    0.000    0.000   0.000

[root@controller(unknown*) ~]# service ntpd restart
Redirecting to /bin/systemctl restart  ntpd.service
[root@controller(unknown*) ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+elite7hackers.n 129.250.35.250   3 u    1   64    1    2.388    6.944   2.486
-ntp1.edutel.nl  80.94.65.10      2 u    1   64    1    6.436    5.772   3.779
*ntp1.trans-ix.n 211.207.249.90   2 u    2   64    1    2.832    6.985   0.257
+mirror.muntinte 193.190.230.66   2 u    2   64    1    2.043    8.057   0.131
```

**Comment by hansthen** [comment]
mwah we could but a restart is automatic when the controller is moved to the customers site.
