### ISSUE TITLE
trinity compute image: no docker 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#263]
* master_installer
e888119

From genimage stdout:

```
Enter the dracut mode. Dracut version: 033. Dracut directory: dracut_033.
sed: can't read /install/netboot/centos7.0/x86_64/trinity/rootimg/etc/sysconfig/docker: No such file or directory
```

Verified when ssh'ing into node:
[root@node002 ~]# docker images
-bash: docker: command not found

**Comment by themisa** [comment]
May need local repo for docker

**Comment by hansthen** [comment]
Missing otherpgks entry from the linuxmage table.

```chtab imagename=centos7.0-x86_64-netboot-trinity linuximage.otherpkglist=/install/custom/netboot/centos/trinity.centos7.otherpkgs```

**Comment by hansthen** [comment]
No code change required. Assigning to Themis.

**Comment by themisa** [comment]
also a problem in * r3
0d12eb5

**Comment by hansthen** [comment]
Strange: I verified this against the default linuximage tables. Can you make sure you specify --with-tables-please-I-really-need-it, next time you run update_controller.sh?

**Comment by themisa** [comment]
did update_master with-table

nodeset controller
tabdump linuximage
```
"centos7.0-x86_64-netboot-trinity",,,,"/install/custom/netboot/centos/trinity.centos7.pkglist","/install/centos7.0/x86_64","/install/custom/netboot/centos/trinity.centos7.otherpkgs","/install/post/otherpkgs/centos7.0/x86_64","/install/custom/netboot/centos/trinity.centos7.exlist","/install/custom/netboot/centos/trinity.centos7.postinstall","/install/netboot/centos7.0/x86_64/trinity",,,,,,,"755",,,,,,
```

**Comment by themisa** [comment]
* dtap
e953fd8

also *r3

Cannot reproduce issue, or was fixed: linuximage has otherpkgs directory. Also it may have been due to #272
