### ISSUE TITLE
Trinity compute: X11 forwarding may need t be enabled

### ISSUE THREAD

**Issue by MDSharma** [clustervision/trinity#265]
It looks like X11 forwarding does not work from the nodes. Here is what I did and how:

salloc a node for myself
`mds207@athena:~$ salloc -J mds_job_name -N 1 -w c007`
`salloc: Granted job allocation 10`

check that the node has been allocated
```
mds207@athena:~$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                10 container mds_job_   mds207  R       0:04      1 c007
```
check that commands are running on the correct node
`mds207@athena:~$ srun hostname
c007.vc-a`

SSH with X forward enabled as I will need to run a GUI program
```
mds207@athena:~$ ssh -X c007
Warning: Permanently added 'c007,172.16.0.7' (RSA) to the list of known hosts.
mds207@c007's password:
X11 forwarding request failed on channel 0
```

Might need to enable X11 forwarding in compute nodes?

**Comment by hansthen** [comment]
X forwarding needs xauth inside the container. This can be part of a local customization, by adding a RUN yum -y install xauth in the Dockerfile. I will mark it as a possible enhancement.

**Comment by themisa** [comment]
xauth seems not to be enough for x11 forwarding. more packaged needed.

**Comment by hansthen** [comment]
@themisa Can you be more specific? I think xauth is the only package required. If you need more, let me know which packages. 

Note that X forwarding will fail if you reprovision a node/container with the same ip address if that node is still in your known_hosts file. I have a hunch that this may be the underlying cause of X forwarding not working.

**Comment by abhimukh** [comment]
The package you need is __xorg-x11-xauth__  not xauth

**Comment by hansthen** [comment]
Assigned to themis for testing.

**Comment by hansthen** [comment]
**Version:** r4_fixes cdaf89b
**Environment:** master
```
[root@controller ~]# ssh -vX john@c001
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
...
john@c001's password: 
debug1: Authentication succeeded (password).
Authenticated to c001 ([172.16.0.1]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Requesting X11 forwarding with authentication spoofing.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
Last login: Thu Jul 23 15:39:31 2015 from controller.cluster
Could not chdir to home directory /home/john: No such file or directory
/usr/bin/xauth:  error in locking authority file /home/john/.Xauthority
```
