### ISSUE TITLE
Trinity compute: How to update docker file

### ISSUE THREAD

**Issue by MDSharma** [clustervision/trinity#266]
`cd /trinity/`
create a new folder to house your customisations
`mkdir compute-local`
copy the `/trinity/compute/Dockerfile` to this new folder
`cd compute-local`
`cp /trinity/compute/Dockerfile ./`

edit this file

` vi Dockerfile`

here is what the file looks like:
```
cat Dockerfile
FROM controller:5050/trinity:latest
RUN yum -y install hostname libXtst
```
make whatever changes you need to and then follow these commands:

`docker build -t controller:5050/vc-a `
This will build that image and tag it as controller:5050/vc-a The tag is just a name, but it will also explain that the image will be hosted in the registry under controller:5050.

` docker push controller:5050/vc-a`
This will push the image into the registry

To activate the new images without having to reboot the nodes
` xdsh node001-node007 systemctl force-reload trinity`

To build the clean Dockerfile you can either rename it or use the -f Dockerfile_clean as argument to the build.

**Comment by hansthen** [comment]
This should be added to our wiki / administrator manual.

**Comment by hansthen** [comment]
This material has been migrated to the wiki.
