### ISSUE TITLE
Trinity compute: split directories for node and container

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#267]
One would contain just the data required for the compute node (rootimg).
One would contain just the data required for the container (Dockerfile, rootimg).

**Comment by themisa** [comment]
This is in r3_fixes. or r3_fix_267.

Need to test, merge with r3 and dtap

**Comment by themisa** [comment]
Imprelmented correctly in * r3
7ac7a06

Merge with dtap

**Comment by themisa** [comment]
Implemented correctly in *r4, but in all branches the compute directory is "polluted" with stale files.
Follow that issue in #308. Will close this issue
