### ISSUE TITLE
controller unable to generate trinity images

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#269]
[root@controller ~]# cat /trinity/version 
    * r3
    87d217b

Going through test procedure 1.1.17 (or 1.1.16):

    [root@controller ~]# genimage -o centos7.0 -a x86_64 -p compute
      OS: centos7.0
      Profile: compute
    OPTIONAL: Which specific network interface will the image boot from? [<blank>]

(press enter)

      No interface specified.  The interface will be determined at network boot time.
    Generating image: 
    cd /opt/xcat/share/xcat/netboot/centos; ./genimage -a x86_64 -o centos7.0 -p compute --tempfile /tmp/xcat_genimage.46343
    The repository for /install/centos7.0/x86_64 should be created before running the genimge. Try to run [createrepo /install/centos7.0/x86_64].
    Need /install/centos7.0/x86_64/ available from a system that has ran copycds on centos7.0 x86_64
    
    [root@controller centos]# echo $?
    1
    
    [root@controller ~]# ls /install/centos7.0/x86_64
    ls: cannot access /install/centos7.0/x86_64: No such file or directory
    [root@controller ~]# ls /install/centos7.0
    ls: cannot access /install/centos7.0: No such file or directory
    [root@controller ~]# ls /install/ 
    custom  netboot  post  postscripts  prescripts  runimages  winpostscripts

**Comment by themisa** [comment]
@linuxstudio which system/hardware was this on?

**Comment by hansthen** [comment]
There will have been an earlier error message regarding the copycds.

**Comment by themisa** [comment]
I believe the error happens before postscripts are run. Same issue in : 
* r3
f4eec01

Error before the genimage error is:
```
Error: The management server was unable to find/read /tmp/trinity/iso//tmp/trinity/iso/CentOS-7-x86_64-Everything-1503-01.iso. Ensure that file exists on the server at the specified location.
```

On amaster:
```
[root@master iso]# ls /trinity/iso
CentOS-7-x86_64-Everything-1503-01.iso
```

```
[root@master iso]# ls /tmp/trinity/iso
CentOS-7-x86_64-DVD-1503-01.iso
```

**Comment by themisa** [comment]
see $271

**Comment by themisa** [comment]
Fixed in * r3
0d12eb5
