### ISSUE TITLE
Error message in cv_install_ldap

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#273]
**version**: 47bcd7b
**component**: cv_install_ldap
**platform**: openstack node
**HW**: D/I3

May be nothing, but need to check it out.

ldapmodify: invalid format (line 5) entry: "olcDatabase={2}hdb,cn=config"

**Comment by hansthen** [comment]
@themisa can you check if this error still shows up in the installation logs?

**Comment by themisa** [comment]
this error appears in the installation logs in

* r5_features
293a026

```
ldapmodify: invalid format (line 5) entry: "olcDatabase={2}hdb,cn=config"
```

This is on controller node and openstack node.
possibly more. will check other branches as well.

**Comment by hansthen** [comment]
It looks like the entries are created correctly, even with the error message:
```
olcRootPW:: c3lzdGVt
olcSuffix: dc=cluster
olcRootDN: cn=Manager,dc=cluster
```

**Comment by hansthen** [comment]
I propose to close this. Assigning to QA for verification.

**Comment by hansthen** [comment]
In absence of themis, I will close this.

**Comment by hansthen** [comment]
This was actually the same error as #399. The ldif files should not have trailing white spaces.
