### ISSUE TITLE
openstack installation: cv_install_openstack fails

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#277]
* r3
0d12eb5

amaster, node003

error: (in /var/log/xcat/xcat.log)
```
[root@openstack ~]# cat /var/log/xcat/xcat.log | grep "fail"
Error: Parameter source failed on Firewall[001 nova compute incoming nova_compute]: host_to_ip failed for , exception no address for  at /var/tmp/packstack/016f799f05c844a59363745061901db6/modules/packstack/manifests/firewall.pp:50
```

**Comment by hansthen** [comment]
It appears $(hostname -i) did not find an entry for openstack (the local hostname).

We need to either define openstack as a DNS name or find a more clever way to determine the IP address of the host. I have added the following line inside cv_install_openstack to work around this. 

```
IP=$(ip addr show dev eno1 | grep "inet " | awk '{print $2}' | awk -F/ '{print $1}')
sed "s/=127.0.0.1/=${IP}/g" //xcatpost/packstack-answers.txt > /tmp/packstack-answers.txt
```

**Comment by hansthen** [comment]
The error can be detected by looking at /tmp/packstack-answers and scanning for this line. (There are a few more like these). In /xcatpostinit/packstack-answers they will point to 127.0.0.1.

CONFIG_CONTROLLER_HOST=

**Comment by themisa** [comment]
tested in * r3
06c3594. 

Fixed.
