### ISSUE TITLE
Trinity images: add local customizations

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#280]
For Exeter I created a local customizations hook. At the end of the postinstall script we copy site-local customizations into the compute image. We should use this mechanism also in our main branches.

#-- copy local customizations
cp -r /trinity/site-local/compute/rootimg/* $installroot

This way we can also do away with locally adapted /etc/fstab files inside the postinstall. Please note that the path actually chosen in Exeter is slightly different.

**Comment by hansthen** [comment]
I found another solution for this problem. We can also define a synclist to customize the image. We can also use a postscript instead of changing the image. Have to evaluate the options in more detail. I propose to move this to R6.

**Comment by hansthen** [comment]
Assigning to themis for testing.

**Comment by themisa** [comment]
Need a test procedure: Create a site local addition. @hansthen

**Comment by themisa** [comment]
1. create a file in /trinity/site-local/compute/rootimg/ (e.g. themis_was_here.txt)
2.  do a genimage
 3. do an ./update controller
 4. delete /install/netboot/compute
 5. do a genimage again
 6. check if the compute nodes have themis_as_here

**Comment by themisa** [comment]
After going through steps 1 and 2:
3: ./update controller
root@controller(amaster) trinity]# ./update controller
This will update the current node using the from source code repository
using the profile: controller
Removing stale /trinity/cinder/rootimg
Removing stale /trinity/compute/rootimg
Removing stale /trinity/container/rootimg
Removing stale /trinity/login/rootimg
Removing stale /trinity/nova/rootimg
Removing stale /trinity/openldap/rootimg
Removing stale /trinity/openstack/rootimg
No site-local rootimg found
```
It says no site-local rootimg found.

On controller:
```
[root@controller(amaster) trinity]# ls /trinity/site-local/trinity/rootimg/
themis_was_here.txt
```

**Comment by hansthen** [comment]
The update script is too verbose. Ignore that message for now.

**Comment by themisa** [comment]
Needs to he /trinity not /compute in codde

**Comment by themisa** [comment]
confused - did this happen because we merged r6 into master?

**Comment by hansthen** [comment]
I think we can close this
