### ISSUE TITLE
slurm configuration: missing partitions

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#288]
**version: ** exeter
**hardware: ** dagobah/athena

slurm-nodes.conf is missing partitions

```
NodeName=c001 CPUS=16 State=UNKNOWN
NodeName=c004 CPUS=16 State=UNKNOWN
NodeName=c005 CPUS=16 State=UNKNOWN
NodeName=c006 CPUS=16 State=UNKNOWN
NodeName=c007 CPUS=64 State=UNKNOWN
NodeName=c008 CPUS=64 State=UNKNOWN 
```

**Comment by hansthen** [comment]
I think someone was messing with the system. I will close the bug here, unless we can corroborate the bug in our test setup. For tracking problems in live supported systems we will use RT, not github. (Although issues may be promoted from RT to github.)
