### ISSUE TITLE
slurm: moving containers does not update sinfo

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#289]
moved c002-c003 to athena,
not reflected in sinfo

```
[root@athena ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1 drain* c005
compute*     up   infinite      2  drain c[004,006]
compute*     up   infinite      3   idle c[001,007-008]
```

**Comment by hansthen** [comment]
This should be handled by the partitioning program.

**Comment by themisa** [comment]
In our braches (r3/r4 etc this does happen by default. I am not sure what the difference of exeter branch is. 
Could be the hostname "athena" as opposed to vc-a?

**Comment by hansthen** [comment]
If it only happens in Exeter we can close the bug here and investigate there. We use RT for bugs in live systems.
