### ISSUE TITLE
Github: Trinity repository needs a README file. 

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#29]

**Comment by hansthen** [comment]
I propose assigning this to Themis (as soon as she has accepted my developer invitation).

**Comment by linuxstudio** [comment]
The current README.md still references to FastCloud

**Comment by hansthen** [comment]
@linuxstudio What is the status on this? Can we close this?

**Comment by linuxstudio** [comment]
@hansthen It is fixed in branch r4_readme. Please verify for quality and merge back into r4. It needs to be also merged into master branch.

**Comment by themisa** [comment]
Added to master, r3 and r4.
Will have to periodically edit for content, but now its tracked on all major branches.
