### ISSUE TITLE
Trinity does not check if there is a newer image at startup

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#3]
Trinity currently will restart a container if it finds one in stopped state. This means that if a new image is created it will not be automatically started (not even after a new genimage, since images are stored in the permanent storage of a node). I have added the reload option to the trinity service which will remove the container, pull the latest containers and then restart a container, but it is kind of a hack.

**Comment by hansthen** [comment]
Docker pull gives us: 
Status: Downloaded newer image for controller:5050/trinity:latest

**Comment by themisa** [comment]
* r3
74c8094
Test: in controller /trinity/compute
edited dockerfile - small change
then:
docker build -t controller:5050/trinity .
docker push controller:5050/trinity
psh node001 systemctl restart trinity
 psh node001 docker ps

node001: CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS               NAMES
node001: 272c71631a37        controller:5050/trinity:latest   "/usr/bin/supervisor   25 minutes ago      Up 25 minutes                           trinity           
see if latest image is running after restart - it does.
Passes
