### ISSUE TITLE
update_profile.sh does not delete stale files

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#308]
```
[root@master ~]# ls /trinity/controller/rootimg/trinity/compute/rootimg/etc/
fstab  fstab-trinity  rc.d  security

[root@master ~]# cat /trinity/version 
* r4
6ddfa06

[root@master themis]# cd themis/trinity/
[root@master trinity]# ls controller/rootimg/trinity/compute/rootimg/etc/
rc.d  security
```

**Comment by themisa** [comment]
in dtap_fix_275

**Comment by themisa** [comment]
Also affects the new container / compute division. 
Compute still has Dockerfile, whereas it is supposed to be deleted.
see:
/trinity/controller/rootimg/trinity/compute

**Comment by hansthen** [comment]
Easiest fix is to make sure all rootimg files are cleared first, before we copy stuff over them. However, will need to discuss with Abhi, as he was also doing some work in #275 that went into the same directtion.

**Comment by abhimukh** [comment]
@hansthen It is difficult to ensure that. We copy from rootimg/ --> /. 
We obviously cannot delete the whole / before the copy. Which means that the only other option is to descend recursively into the rootimg/ and compare the contents of the lowest level directory. This will work in some cases, but not in all. Consider, the case of /etc/exports. There can be a site specific customization under /etc/exports.d/.  There is no generic logic which we can use to look in to the exports.d directory: since we will have <rootimg>/etc/exports we can compare that with /etc/exports, but there is no <rootimg>/etc/exports.d/ directory so no reason to look at /etc/exports.d. Thus contents under /etc/exports.d will not be cleaned up. 

One way to solve this is to provide a custom list of files and folders which the update script should look into and if necessary remove.

**Comment by hansthen** [comment]
The biggest problem (so far) is for items like compute nodes (e.g. genimage) container creation etc. 

What I propose is to simply add a "rm -rf /install/*/rootimg" to any updateprofile script. This means that when we do an update_master the master may still have stale files, but anything generated from master will not.

**Comment by abhimukh** [comment]
@hansthen You mean `rm -rf /trinity/*/rootimg` ?

I don't see how this solves our problem. We can, in principle, do `rm -rf /trinity/*` during update master. That will ensure that everything generated from the master will be updated, but not the master itself (tables, and the /install directory). 

But, this is not the main problem. What we want is to be able to update nodes at the customer site (controller, oepnstack etc). In that case this does not work. In particular, if we try the same thing for the controller (`rm -rf /trinity/*`); the /install, tables, /etc on controllers will not still contain stale files, and openstack and  login nodes will need to be reprovisioned.

**Comment by hansthen** [comment]
Assigning to Abhi.

**Comment by abhimukh** [comment]
Fixed in r5_fixes fab70189138147dce34942aa558e5a3cdb1c42bc.
Usage for the update script:

```
[root@dmaster trinity]# ./update --help

Usage:
  update <profile> [<options>]

  The following profiles are supported:
    master, controller, openstack, login, compute and container

  For profiles master, controller, openstack and login 
  run this script locally.

  For all other profiles, the script should be run from the controller.

  For profiles other than master and controller, this script should be 
  run after running update controller.

  The following options are supported:
    master | controller
      --tables : restore xCAT tables from repo

    openstack | login 
      --restart : restart services after update.
                  This includes
                   - openstack : API, httpd
                   - login : slurm
    compute | container 
      --reboot <node_range> : reboot the nodes ( for <profile> = compute ) 
                              or containers in the nodes (for <profile> = containers) 
                              with the new image
    

```

**Comment by abhimukh** [comment]
Assigning to @themisa for testing.

**Comment by themisa** [comment]
Fixed.  Tested in:
[root@controller(amaster) trinity]# /trinity/report
**Version:** r5_fixes c2dc5c0
**Environment:** amaster


There were stale files in /trinity
using ./update controller, now these are removed.
Before:
```
[root@controller(amaster) trinity]# cat /trinity/version
* r5_fixes
e5f4623
[root@controller(amaster) trinity]# ls /trinity
api+dash  cinder  clustervision  compute  container  login  nova  openstack  report  site  trinity_login  version
```

Then update_controller:

After:
```
[root@controller(amaster) trinity]# ls /trinity
cinder  compute  container  login  nova  openstack  report  version
```
