### ISSUE TITLE
Trinity compute: on bright installed nodes BMC setup fails

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#309]
xCAT BMC setup fails (partially) on nodes which were provisioned by bright before. 

```
[xCAT Genesis running on node001 /]# ipmitool user list 1
ID  Name	     Callin  Link Auth	IPMI Msg   Channel Priv Limit
1                    false   false      true       ADMINISTRATOR
2   root             false   true       true       ADMINISTRATOR
```
On other nodes (not provisioned by bright) Callin is set to true.

However, we cannot change this (even manually):
```
[xCAT Genesis running on node001 /]# ipmitool channel setaccess 1 2 callin=on
Set User Access (channel 1 id 2) failed: Invalid data field in request
```

It is unclear why this is the case.

**Comment by linuxstudio** [comment]
I need to have the exact model of hardware that you are using.
Can't reproduce this issue with a supermicro node with 

```
Base Board Information
	Manufacturer: Supermicro
	Product Name: A1SAM-2750F
```

That node was provisioned with Bright in the past.

**Comment by hansthen** [comment]
@themisa Can you check if this issue actually causes problems on any of our systems?

**Comment by themisa** [comment]
If we see again, will reopen
