### ISSUE TITLE
xCAT Controller: nameserver is set to master IP

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#314]
The nameserver on the xCAT controller is set to the IP address of the corresponding master
```
[root@controller ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search cluster cluster.
nameserver 192.168.1.254
```
This is incorrect.

**Comment by hansthen** [comment]
We need to re-think about how we want to serve DNS on the cluster.

1. use peerdns=yes on the controller
2. make the controller DNS server for itself, set the forwarders to the company DNS
3. any other options?

**Comment by hansthen** [comment]
Fixed (in r4_fixes). Assigning to Themis for testing.

**Comment by hansthen** [comment]
**Version:** * r5 34a01f3
**Environment:** pmaster
```
[root@controller ~]# cat /etc/resolv.conf 
domain cluster
search cluster
nameserver localhost
```

**Comment by quentinleburel** [comment]
Problem is back in R8

**Version:** r8 0807eef
**Environment:** 140781

```
[root@controller-1(140781) controller]# cat /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search cluster.
nameserver 192.168.1.254
```

**Comment by hansthen** [comment]
We changed this (in R7) to a postscript that needs to be run after you are done with the cluster. The controller needs to have been booted and tested on the customer network and then you need to call the following postscripts to "finish" the installation.

1. cv_update_nameservers
2. cv_controller_firewall
3. cv_handover

**Comment by brunopereira81** [comment]
- `cv_update_nameservers`: adds the assigned by DHCP DNS servers from a customer network as forwarders to local DNS service;
- `cv_controller_firewall`: blocks all traffic to the host this script runs, except for ssh;
- `cv_handover`: nothing to do with DNS.

Reading the desired behavior from you [comment]
(https://github.com/clustervision/trinity/issues/314#issuecomment-123471501) could you point us to the part where resolv.conf is updated accordingly?

Also the desired behavior seems that the controller is uses its own DNS service for local resolution of addresses, there is no reason to leave it to the end of an installation to enable this.

On a side note: your `cv_update_nameservers` lines 4,5 and 6 are badly commented out, which results in warnings when running the script:

```
/install/postscripts/cv_update_nameservers: line 4: to: command not found
/install/postscripts/cv_update_nameservers: line 5: This: command not found
/install/postscripts/cv_update_nameservers: line 6: tested: command not found
```
