### ISSUE TITLE
trinity containers: slurm errors

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#325]
**version**:  r5 dc69f82

```
[root@c001 /]# sinfo
sinfo: error: slurm_receive_msg: Zero Bytes were transmitted or received
slurm_load_partitions: Zero Bytes were transmitted or received
```

**Comment by themisa** [comment]
manual fix: system trinity restart

**Comment by themisa** [comment]
[root@c001 /]# sinfo
sinfo: error: slurm_receive_msg: Zero Bytes were transmitted or received
slurm_load_partitions: Zero Bytes were transmitted or received

@abhimukh 
still a problem. That's why we may need to add a service trinity restart at the end of login node creation? Or add as a procedure?

**Comment by themisa** [comment]
Also in  r5_gpu
ebb5b4d

**Comment by hansthen** [comment]
It looks like the login node creation recreates the munge key, even if it is already there for a particular cluster.

```
[root@c002 munge]# head /var/log/slurm/slurmd.log 
[2015-07-21T20:27:19.269] Node configuration differs from hardware: CPUs=8:8(hw) Boards=1:1(hw) SocketsPerBoard=8:1(hw) CoresPerSocket=1:8(hw) ThreadsPerCore=1:1(hw)

[root@c002 munge]# ls -l /etc/munge/munge.key      
-r-------- 1 munge munge 1024 Jul 21 20:54 /etc/munge/munge.key
```

So either login node creation should not recreate the munge key if it is already there, or it should restart the affected nodes after creation. My preference goes to 1.

**Comment by abhimukh** [comment]
@hansthen It is not clear to me from your comment, why you think that the munge key is recreated? 
In fact, the munge key is never recreated (or at least it is not meant to be recreated, unless there is a bug in the code).

**Comment by abhimukh** [comment]
@themisa 
1. Do you see this problem only for the default cluster? 
2. Is `service trinity restart` sufficient to fix it?

**Comment by abhimukh** [comment]
Assigning to @themisa for testing

**Comment by themisa** [comment]
@abhimukh. This happens for default cluster, yes. 
```
[root@controller() ~]# xdsh node001-node002 service trinity restart
node001: Restarting trinity (via systemctl):  [  OK  ]

node002: Restarting trinity (via systemctl):  [  OK  ]

node002: Warning: Permanently added 'node002,10.141.0.2' (ECDSA) to the list of known hosts.

[root@controller() ~]# ssh node001
Last login: Mon Aug  3 14:00:54 2015 from controller.cluster
[root@node001 ~]# docker-enter trinity
[root@c001 /]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      2   idle c[001-002]
```

Should i create a manual procedure? or add service trinity restart somewhere in the code.

**Comment by themisa** [comment]
I will close the bug.
Procedure is for openstack node to be installed first, then provision compute nodes.
In case the openstack node needs reinstalling, etc, we can restart trinity on computer nodes.

```
 xdsh node001-node002 service trinity restart
```
