### ISSUE TITLE
monitoring from openstack dashboard: does not work

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#327]
When clicking on the monitoring tab under the HPC panel on the openstack dashboard,
the monitoring page doesn't open.

After a manual hack, it opens, but doesn't accept the credentials.

This works from the controller node.

**Comment by abhimukh** [comment]
I have removed the monitoring hook from the dashboard for now.

**Comment by themisa** [comment]
@abhimukh, do you want to push it to r6?

**Comment by themisa** [comment]
Won't fix.
