### ISSUE TITLE
colander: after primary controller comes back on, /trinity not mounted

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#329]
* colander
6d5f544

After shutting down, then booting controller-1:

```
[root@controller-1 ~]# cat /trinity/version
cat: /trinity/version: No such file or directory
```

**Comment by hansthen** [comment]
After controller-1 becomes the passive node, the exported file systems are no longer accessible (they are only accessible on the active node). This is to avoid edits on both active and passive nodes at the same time.
