### ISSUE TITLE
GitHub: add versioning information to all components

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#33]
Each component in Trinity should have an easily discoverable version string that points back to the GitHub repository. Preferably in SHA format, so we can copy the version id into issue reports.

**Comment by abhimukh** [comment]
Added a new resource to the API which fetches the version information from the file /trinity/version
GET /trinity/v1/version
{
    "versionID (releaseBranch)": "97530a8 (r3)"
}

The dashboard (via client) first checks version info in its local file system, failing it makes an api call.
Version info is printed at the bottom of the HPC Overview panel under Admin/HPCPanel

**Comment by themisa** [comment]
@abhi : works for every node except openstack - is the version copied in another file?

**Comment by themisa** [comment]
Fixed in * r3
5cead59
