### ISSUE TITLE
r5_features:The skeleton cluster folder points to wrong directory

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#331]
* r5_features
070924f

The skeleton cluster folder still point to `vc-0` instead of `.skel` in `cv_install_openstack`

```
[root@openstack ~(keystone_a)]# view /xcatpost/cv_install_openstack
...
cp -r /cluster/vc-0/* /cluster/${FIRST_CLUSTER}/
...
```

**Comment by hansthen** [comment]
Do not take my comment seriously. I mistyped #331 for #311.

**Comment by themisa** [comment]
fixed in * r5_features
293a026
