### ISSUE TITLE
trinity containers: slurm sets containers to "drain"  during some partition cases

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#332]
When we remove resources from a virtual cluster, then do service slurm restart to update the containers belonging now to the cluster, the containers are set to "drain"

login.vc-a
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1  drain c001
[root@login ~]# 

In this case, the cluster vc-a was created with 2 containers, one was removed, slurm was restarted.

Examining the slurm log files;
```
[2015-07-01T12:05:26.963] read_slurm_conf: backup_controller not specified.
[2015-07-01T12:05:26.963] Running as primary controller
[2015-07-01T12:05:29.971] error: Node c001 appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.
[2015-07-01T12:05:29.971] error: Node c001 has low socket*core*thread count (1 < 20)
[2015-07-01T12:05:29.971] error: Node c001 has low cpu count (1 < 20)
[2015-07-01T12:05:29.971] error: _slurm_rpc_node_registration node=c001: Invalid argument
[2015-07-01T12:06:26.970] SchedulerParameters=default_queue_depth=100,max_rpc_cnt=0,max_sched_time=4,partition_job_depth=0
```

**Comment by abhimukh** [comment]
@themisa This is likely because when slurmctld starts up it finds a conflict between its last checkpointed state and the (new) conf file. I suggest the following steps. After cluster repartitioning 

 Restart slurm
``` 
[root@login ~]# service slurm restart
```
 If one or more of the nodes are in drain state, then try to update their status
```
[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1 drain* c001
[root@login ~]# scontrol update nodename=c001 state=resume
[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1  idle* c001

```
However, if this does not work, and the nodes are still in `drain` state, then force slurm to re-read the configuration files, 

```
[root@login ~]# scontrol reconfigure
[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1  idle* c001

```

However, if this still does not work then force slurm to do a clean start

```
[root@login ~]# service slurm stop
Stopping slurm (via systemctl):                            [  OK  ]
[root@login ~]# service slurm startclean
starting slurmctld:                                        [  OK  ]
[root@login ~]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1    idle* c001

```

Note that the last step will cause slurm to lose any checkpointed info (=> job queue info etc will be lost).

**Comment by themisa** [comment]
[root@login ~]# /trinity/report
**Version:** r5_fixes a06d57b
**Environment:** amaster


I moved containers from one cluster to another, and restarted slurm. I did not observe the drain issue again. However i will add the suggestions for a fix in a troubleshooting doc 

```
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      2   idle c[001-002]
[root@login ~]# service slurm restart
Restarting slurm (via systemctl):                          [  OK  ]
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1    unk c001
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1   idle c001
```
