### ISSUE TITLE
Ldap authentication: error messages

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#345]
-- Logs begin at vr 2015-07-10 09:56:56 UTC, end at vr 2015-07-10 11:49:18 UTC. --
jul 10 11:48:48 login-a.novalocal nslcd[901]: [5f007c] <group/member="root"> ldap_result() failed: Invalid DN syntax: invalid DN
jul 10 11:48:48 login-a.novalocal slapd[896]: conn=1001 op=96 ABANDON msg=96
jul 10 11:48:48 login-a.novalocal slapd[896]: conn=1001 op=97 do_search: invalid dn: "  shadow ou=People,dc=cluster"
jul 10 11:48:48 login-a.novalocal slapd[896]: conn=1001 op=97 SEARCH RESULT tag=101 err=34 nentries=0 text=invalid DN
jul 10 11:48:48 login-a.novalocal nslcd[901]: [5f007c] <group/member="root"> ldap_result() failed: Invalid DN syntax: invalid DN
jul 10 11:48:48 login-a.novalocal slapd[896]: conn=1001 op=98 ABANDON msg=98

**Comment by hansthen** [comment]
This seems to do no harm, but needs to be investigated. It occurred in Bristol installation.

**Comment by hansthen** [comment]
@themisa can you verify this is still valid?

**Comment by themisa** [comment]
@hansthen , could you tell me which log files this was from?

the login.novalocal seems to be a bug that was fixed. ( hostname = login. the novalocal addition appeared before the fix, the login nodes were rebooted.) 

In this case i think it is fixed now.

**Comment by themisa** [comment]
https://github.com/clustervision/trinity/issues/334

This was fixed aug 4th, after ticket was opened. I will close this.
