### ISSUE TITLE
Login node: after reboot hostname needs to be reset

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#347]
It needs to be login.vc-a

**Comment by abhimukh** [comment]
Duplicate of #334

**Comment by abhimukh** [comment]
Please see my comments for #334. Assigning to @themisa for testing.

**Comment by hansthen** [comment]
From what I understand, this problem did not go away. We need to find a solution so that after a reboot of the login node, customers do not need to set the hostname manually.

**Comment by abhimukh** [comment]
Fixed in r5_fixes : 68957b3
Please see my comments for #334. 
Reassigning to @themisa for testing.

**Comment by themisa** [comment]
See comments on #334. hostname on reboot is "login".
