### ISSUE TITLE
Master installer: repositories for extra packages not in the core distribution

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#35]
Right now we adapt the genimage repositories by adding extra files (rpms) to them. We should not do that. Instead we should download the required files intro a separate directory and run createrepo in there. We can then add an otherpkslist and otherpkgdir to the xCAT linuximage table.

**Comment by hansthen** [comment]
To create "other" repositories, put the rpm files under /install/post/otherpkgs/centos7.0/x86_64/<a_name>/*.rpm and then call createrepo on /install/post/otherpkgs/centos7.0/x86_64/. 

You can then create an "otherpackages" pkglist and add that to the linuximage table. We'll use the following convention for that: /install/custom/netboot/centos/<profile>.centos7.otherpkgs. 

This also solved the problem of not generating trinity images with docker included.

**Comment by hansthen** [comment]
Is testable. Please check if trinity images are generated _with_ docker.

**Comment by themisa** [comment]
version:ee93d17

[root@controller x86_64]# find /install/netboot/centos7.0/x86_64/trinity/rootimg/ -name "docker"
/install/netboot/centos7.0/x86_64/trinity/rootimg/etc/sysconfig/docker
/install/netboot/centos7.0/x86_64/trinity/rootimg/etc/docker
/install/netboot/centos7.0/x86_64/trinity/rootimg/var/lib/docker
/install/netboot/centos7.0/x86_64/trinity/rootimg/usr/bin/docker
/install/netboot/centos7.0/x86_64/trinity/rootimg/usr/share/bash-completion/completions/docker
/install/netboot/centos7.0/x86_64/trinity/rootimg/usr/libexec/docker

**Comment by themisa** [comment]
@hansthen 
can you confirm the above is the only check i need to close this issue?

**Comment by hansthen** [comment]
Yes
