### ISSUE TITLE
r5_gpu: gpu driver not downloaded?

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#350]
Commit  ebb5b4d1e8be3771636b0bf76d is supposed to get drivers needed for GPUs
I don't think that is the case - the driver never gets downloaded in /cluster and not run on the compute nodes.

**Comment by hansthen** [comment]
I kinda expected the engineers to do the downloading themselves.

**Comment by hansthen** [comment]
That's is going to be difficult. The driver depends on the actual GPU model chosen and you have to know the latest version. I'd have to do some serious screen scraping to determine the download location. I suggest that we force engineers to download the runfile into /cluster and take it from there.
