### ISSUE TITLE
xCAT policy file points to incorrect hostname on pmaster

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#353]
The xcat policy file on pmaster points to `mastermaster.cluster` instead of `pmaster.cluster`
```
[root@pmaster ~]# tabdump policy
#priority,name,host,commands,noderange,parameters,time,rule,comments,disable
"1","root",,,,,,"allow",,
"1.2","mastermaster.cluster",,,,,,"trusted",,
"2",,,"getbmcconfig",,,,"allow",,
"2.1",,,"remoteimmsetup",,,,"allow",,
"2.3",,,"lsxcatd",,,,"allow",,
"3",,,"nextdestiny",,,,"allow",,
"4",,,"getdestiny",,,,"allow",,
"4.4",,,"getpostscript",,,,"allow",,
"4.5",,,"getcredentials",,,,"allow",,
"4.6",,,"syncfiles",,,,"allow",,
"4.7",,,"litefile",,,,"allow",,
"4.8",,,"litetree",,,,"allow",,
```
Note that, simply changing the entry on this table is not sufficient, because this needs to propagate to many other places (certificates, credentials etc).

Workaround: regenerate the xCAT configuration

```
[root@pmaster ~]# xcatconfig -f 

```

**Comment by hansthen** [comment]
@abhimukh
What are results of this being misconfigured? Does it have any effects somewhere else as well? We may need to do the same on-site for the controller nodes.

Also:
Is xcatconfig -m not enough to resolve the situation?

**Comment by abhimukh** [comment]
@hansthen Essentially because of this misconfiguration, the mgt node can no longer be used to provision nodes (the permissions, credentials, keys are not correct).

I think `xcatconfig -m` will simply add the mgt node to the xCAT database. It will not recreate the credentials and so on. I am not sure if this is sufficient. Needs to be tested.

**Comment by hansthen** [comment]
Assigning to themis for inclusion in the clusterbats.

**Comment by themisa** [comment]
Also an issue on dmaster

**Comment by hansthen** [comment]
This is procedural. I think it is sufficient to just call `xcatconfig -u`.
