### ISSUE TITLE
Trinity openstack node: error in dashboard

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#360]
**Version:** r5 50b8019
**Environment:** Bristol is Open
```
ConnectionError at /project/hpc_overview/

HTTPConnectionPool(host='10.141.1.1', port=32123): Max retries exceeded with url: /trinity/v1/clusters (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

**Comment by abhimukh** [comment]
@hansthen Can you reproduce this bug?

**Comment by hansthen** [comment]
No. But I reinstalled the OpenStack node.

**Comment by abhimukh** [comment]
@hansthen I don't think I can fix this without further information. Usually, for errors related to the dashboard it is useful to have the contents of the trinity_api log file (`/var/log/trinity/trinity_api.log`). And, also the verbose error report

```
[root@openstack ~(keystone_a)]# vi /etc/openstack-dashboard/local_settings
...
DEBUG = True
...
[root@openstack ~(keystone_a)]# service httpd restart
```

**Comment by themisa** [comment]
Hmm i haven't seen this bug either. I will close, and reopen if it recurs
