### ISSUE TITLE
Trinity architecture: add an identifying prompt

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#361]
At the moment all nodes are called controller. It would be a big improvement if we could show the environment name as part of the prompt.

**Comment by hansthen** [comment]
Proposal:

Place a site identifier in /trinity/site.
Change the root prompt to:

PS1="[\u@\h($(cat /trinity/site)) \W]\$ "

**Comment by themisa** [comment]
Linked to #147 . 

**Version:** r5_fixes e5f4623
**Environment:**


On amaster:
[root@controller() ~]# cat /trinity/site
cat: /trinity/site: No such file or directory

**Comment by hansthen** [comment]
You need to set /trinity/site as part of the installation procedure. I have changed the affected scripts so that the prompt will be show "unknown" if site is not filled.

**Comment by themisa** [comment]
Fixed:

```
[root@controller(amaster) trinity]# /trinity/report
cat: /trinity/site: No such file or directory
**Version:** r5_fixes c2dc5c0
**Environment:** unknown
```

If i add a /trinity/site file:
[root@controller(amaster) trinity]#  vi /trinity/site
[root@controller(amaster) trinity]# /trinity/report
**Version:** r5_fixes c2dc5c0
**Environment:** amaster
