### ISSUE TITLE
Login node: error message on boot

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#367]
**Version:** r4_fixes cdaf89b
**Environment:** master

Check these.
```
[    2.694930] systemd-fstab-generator[328]: Failed to create mount unit file /run/systemd/generator/cluster.mount, as it already exists. Duplicate entry in /etc/fstab?
[    2.697314] systemd-fstab-generator[328]: Failed to create mount unit file /run/systemd/generator/trinity.mount, as it already exists. Duplicate entry in /etc/fstab?
[    2.699655] systemd-fstab-generator[328]: Failed to create mount unit file /run/systemd/generator/home.mount, as it already exists. Duplicate entry in /etc/fstab?
```

**Comment by abhimukh** [comment]
@hansthen 
Was this during login node creation, or reboot?
Did you check the contents of the /etc/fstab?

**Comment by hansthen** [comment]
I think it was during creation but I do not remember (after 25 days).

**Comment by abhimukh** [comment]
I won't try to fix this now (not enough info), but will keep this open. For any future recurrences, please report here.

**Comment by themisa** [comment]
I will close this since this hasn't reappeared since.
