### ISSUE TITLE
Master installer: error? message during discovery

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#37]
Jan 19 12:16:44 master dhcpd: DHCPDISCOVER from 08:00:27:03:84:81 via eno3: booting disallowed

**Comment by brunopereira81** [comment]
That is because you are using "mac" as a discovery interface and doing the discovery on another nic, or vice versa.

**Comment by hansthen** [comment]
Thanks. What do you mean "on another nic"?

**Comment by brunopereira81** [comment]
The nic that is doing the discovery is not the nic that booted, or there is no nic definition set for that nic, that nic is marked down in the DHCP server and you are not allowed to boot from it (PXE).

**Comment by hansthen** [comment]
Ah, yes. Needed to regenerate the dhcp config after adding an interface.

**Comment by brunopereira81** [comment]
Dont think that this sorts out the issue without further explanation of what is done.

**Comment by hansthen** [comment]
We added eno3 as a dhcp interface to the site table.
