### ISSUE TITLE
demo environment: new login nodes cannot connect to internet

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#374]
* r5
34a01f3

pmaster (demo)

When partitioning cluster and allocating resources to a new cluster an new login node is automatically created. In this case, the instance is launched, but slurm is not downloaded/installed. Network not reachable

```
[root@login ~]# ping google.com
PING google.com (74.125.206.100) 56(84) bytes of data.
```

**Comment by abhimukh** [comment]
The iptables on the openstack node is not setup properly. Everything that goes out of eno4 should be snat-ed

**Comment by hansthen** [comment]
Workaround, but we must remember this for when we have to attach the OpenStack node to the internet/company net as well.
```
iptables -A FORWARD -i eno1 -j ACCEPT
iptables -t nat -A POSTROUTING -o eno4 -j MASQUERADE
```

**Comment by hansthen** [comment]
Since this only happens on the demo environment, assigning it back to Themis for testing.

**Comment by themisa** [comment]
Now ok on demo. Closing.
