### ISSUE TITLE
masterless: controller installation: switched ip address in the middle of installation

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#378]
masterless d99ea6957
benchmark node

If i configure network to get ip from dchp instead of static, during the running of script cv_install_controller, when the network restarts it gets a new ip address

```
+ for file in '/etc/sysconfig/network-scripts/ifcfg-{$ETH2,$ETH3}'
+ sed -i /etc/sysconfig/network-scripts/ifcfg- -e 's/DEFROUTE=\(.*\)/DEFROUTE=no/'
sed: can't read /etc/sysconfig/network-scripts/ifcfg-: No such file or directory
+ rm /etc/dhclient.d/ntp.sh
rm: cannot remove ‘/etc/dhclient.d/ntp.sh’: No such file or directory
+ sed -i /etc/sysconfig/network-scripts/ifcfg-enp2s0f0 -e 's/DEFROUTE=\(.*\)/DEFROUTE=yes/' -e 's/PEERDNS=\(.*\)/PEERDNS=no/'
+ cat
+ ip a a 10.148.255.254/16 dev enp2s0f1
+ systemctl restart network
```

**Comment by hansthen** [comment]
Yes this may happen. It depends on the sanity of the dhcp server configuration, which is not under our control. 

To avoid problems, you can define the node with a static ip address. However, in many cases a static IP address may (not yet) be available. (Needs to be requested from a central department, takes a week etc.) In those cases, dhcp will usually be available on the internal network. 

Also, it is best to run the cv_install_controller script inside a screen session (or from the console). Can you update the procedure for that?

**Comment by themisa** [comment]
Updated procedure to assign static ip.

Otherwise, use screen, and reattach is ip switches midway
