### ISSUE TITLE
Master installer: xCAT doxcat patch fails 

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#38]
Restore of Database Complete.
patching file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/bmcsetup
Hunk #1 succeeded at 99 (offset 6 lines).
patching file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/doxcat
Hunk #1 FAILED at 6.
Hunk #2 FAILED at 103.
2 out of 2 hunks FAILED -- saving rejects to file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/doxcat.rej
patching file /opt/xcat/share/xcat/netboot/rh/genimage
Hunk #1 succeeded at 542 with fuzz 2 (offset 1 line).
Loaded plugins: fastestmirror

**Comment by hansthen** [comment]
That xCAT patch was based on an older xCAT version.

**Comment by hansthen** [comment]
To test: check the output of /var/log/xcat/xcat.log on a controller installation. Grep for the patches applied and check no patches fail (and no doxcat patch is performed).

**Comment by themisa** [comment]
```
[root@controller ~]# cat /var/log/xcat/xcat.log | grep "doxcat"
[root@controller ~]# 
```
```
[root@controller ~]# cat /var/log/xcat/xcat.log | grep "patch"
--> Processing Dependency: patch >= 2.5 for package: rpm-build-4.11.1-16.el7.x86_64
---> Package patch.x86_64 0:2.7.1-8.el7 will be installed
 patch               x86_64 2.7.1-8.el7     local-centos7.0-x86_64-x86_64 110 k
  Installing : patch-2.7.1-8.el7.x86_64                                   65/98 
  Verifying  : patch-2.7.1-8.el7.x86_64                                   19/98 
  patch.x86_64 0:2.7.1-8.el7                                                    
patching file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/bmcsetup
patching file /opt/xcat/share/xcat/netboot/rh/genimage
(63/74): python-jsonpatch-1.2-3.el7.centos.noarch.rpm      |  14 kB   00:00     
```
version: * r3
9f5a966
