### ISSUE TITLE
Login node: create a complete login node image

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#381]
Our login node now runs a customization script, which takes quite some time to complete. We would be able to develop much quicker if we created a pre-defined login node image.

**Comment by abhimukh** [comment]
Essentially, we need to split the current login/setup.sh script into two part. The part which contains actions necessary for all login nodes (installing packages etc) should be baked into the image, while the small remaining part (virtual cluster specific information) should be passed as userdata through the new, much smaller setup.sh.

The customized image can be created in two different ways:

(1) Snapshot a running login node instance
    This is a good reference http://www.sebastien-han.fr/blog/2012/12/10/openstack-perform-consistent-snapshots/
    I have checked that this works without any hitches
(2) Create a customized login node instance from the basic operating system image. You will need to use the tools : virt-builder (http://libguestfs.org/virt-builder.1.html) for this. The setup.sh script will need to be converted to a set of commands that this tool can understand. 
For even more customization you can use virt-install and guestfish.

**Comment by hansthen** [comment]
This was done by now.
