### ISSUE TITLE
Dashboard: needs installer (at least for Juno)

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#39]
The OpenStack dashboard plugin does not automatically install itself with our cv_install_openstack script. This needs to be added to the installer script.

**Comment by abhimukh** [comment]
The OpenStack controller, the dashboard, the xCAT API and the Trinity API can, in principle, run on different nodes. We should have four scripts: 
1. cv_install_openstack -- remains as is
2. cv_install_dashboard -- installs dashboard + trinity python client
3. cv_install_trinity -- changed to include the installation of the trinity API
4. cv_install_xcat -- changed to make the necessary changes to  install and start the  xCAT API server

**Comment by abhimukh** [comment]
Added an installer script : scripts/cv_install_api+dash. Note that trinity_api, trinity_client and trinity_dashboard already have their own installer scripts (distutils for api and client, bash script for dashboard). The script cv_install_api+dash calls these individual installers.
