### ISSUE TITLE
Controller: add git to allow for version tracking

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#395]
Currently we have no easy way to track (manual) changes to the system after installation. If we add git to all systems (only targeting a few specific directories) we can more easily track changes on the system over time.

**Comment by hansthen** [comment]
This has been implemented in 196bb7a2.

**Comment by themisa** [comment]
Note: this seems to be in a different branch with_git

**Comment by themisa** [comment]
@hansthen outline test procedure

**Comment by hansthen** [comment]
Test procedures can be found here. https://docs.google.com/a/clustervision.com/document/d/12grgFoNdmdNfg9LLFj8bK9N_a0qZg_0xh86qCjcO4Ec/edit?usp=sharing

**Comment by themisa** [comment]
works. tested in
[root@controller(dmaster*) ~]# /trinity/report
**Version:** r5_dockerize 1e9bf1e
**Environment:** dmaster


```
[root@controller(dmaster*) ~]# git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   ../etc/resolv.conf
#
no changes added to commit (use "git add" and/or "git commit -a")
```
