### ISSUE TITLE
Controller installation: points to the repository on master

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#397]
A master installed controller will have two entries in /etc/yum.repos.d that point to the installation repository on master. We should remove those.

**Comment by hansthen** [comment]
Problem with this is that we need to do this as the last postscript to avoid version conflicts.

**Comment by hansthen** [comment]
Upgrading to a bug.

**Comment by hansthen** [comment]
I decided to do this in cv_install_controller. This will make it possible that conflicting versions are installed "afterwards". But we will deal with that later.

**Comment by themisa** [comment]
changes undone in 3bde3ab302c64
