### ISSUE TITLE
GitHub: repository needs a cleanup

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#40]
E.g. 

We now have both an ha-xcat and an xcat version. That needs to be merged (and maybe split off into a feature branch).

The xcat directory contains a tools directory. I am not sure what all of that is and if we still need it.

Etc.

**Comment by hansthen** [comment]
This task is started inside the r2 branch.

**Comment by hansthen** [comment]
Is fixed with merging the master_installer into m3.

**Comment by themisa** [comment]
@hans - the merge hasn't happened yet, correct? and m3=r3?

**Comment by hansthen** [comment]
This issue is too vague to be tested. We will setup a review process. Just QA verify it as invalid.
