### ISSUE TITLE
obol: password is hard-coded

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#400]
The password from obol to the ldap server is hard coded.

**Comment by hansthen** [comment]
Added a -w flag. It is now also possible to change bind id -D and ldap url -H.

```
[root@controller(amaster) ~]# obol -w system user list
hans
hans2
hans3
hans4
hans5
```

**Comment by themisa** [comment]
[root@login ~]# obol user add  -w --password 123 jane
usage: obol [-h] [-D BIND DN] -w BIND PASSWORD [-H HOST] {user,group} ...
obol: error: argument -w is required


Now the passwd for the ldap server required. (BIND PASSWORD)

**Comment by themisa** [comment]
```
[root@login ~]# obol user list 
usage: obol [-h] [-D BIND DN] -w BIND PASSWORD [-H HOST] {user,group} ...
obol: error: argument -w is required
[root@login ~]# obol -w system user list 
jenny
```

Note: need to update procedures.
