### ISSUE TITLE
batch job submissions fail

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#408]
**Version:** r6_clusterbats 4b5ba60
**Environment:** amaster

   sbatch: error: Batch job submission failed: Requested node configuration is not available
Even though:
```
[jane@login ~]$ sbatch sbatch.runme
sbatch: error: Batch job submission failed: Requested node configuration is not available

[jane@login ~]$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      2   idle c[001-002]

```

Steps to reproduce:
From amaster 
ssh -Y node002 (controller)
cd /trinity/testing/clusterbats
bats run_mpi.bats

```
[root@controller(unknown) clusterbats]# bats run_mpi.bats 
 ✓ Can reach the virtual login node
 ✗ Create a user for the login node
   (in test file run_mpi.bats, line 9)
     `sshpass -p system ssh login.vc-a "' failed
   /tmp/bats.24475.src: line 9: obol: command not found
   {'desc': 'Already exists'}
   Traceback (most recent call last):
     File "/usr/sbin/obol", line 336, in <module>
       fun(**args_d)
     File "/usr/sbin/obol", line 44, in user_add
       conn.add_s(dn, add_record)
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 195, in add_s
       return self.result(msgid,all=1,timeout=self.timeout)
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
       resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
       resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
       resp_ctrl_classes=resp_ctrl_classes
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
       ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
     File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
       result = func(*args,**kwargs)
   ldap.ALREADY_EXISTS: {'desc': 'Already exists'}
 ✓ The user can login to login node
 ✗ The user can submit a batch script
   (in test file run_mpi.bats, line 22)
     `sshpass -p system ssh login.vc-a "' failed
   sbatch: error: Batch job submission failed: Requested node configuration is not available

4 tests, 2 failures
```

Ignore the failure of "Create a user for the login node"

**Comment by hansthen** [comment]
@themisa 
Can you attach the sbatch.runme file that triggers this error?

**Comment by themisa** [comment]
It is in /trinity/testing/clusterbats 

also:

```
#!/bin/bash
##SBATCH --get-user-env
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2

module load imb
module load openmpi/gcc/64/1.8.4

mpirun -np 2  --debug-daemons IMB-MPI1 pingpong
```

**Comment by hansthen** [comment]
```
NodeName=c001,c002 State=UNKNOWN
PartitionName=compute Nodes=c001,c002 Default=YES MaxTime=INFINITE State=UP
```

**Comment by themisa** [comment]
This script works:
```
[jane@login ~]$ more sbatch.sample 
#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1

module load imb
module load openmpi/gcc/64/1.8.4

mpirun -np 2  --debug-daemons IMB-MPI1 pingpong
```

CPUs are missing for default cluster. Otherwise everything works.

**Comment by abhimukh** [comment]
The problem is that none of the attribute CPUs, Sockets, CoresPerSocket are specified. So, Slurm simply assumes that the nodes have a single core each, and refuses to launch multiple processes per core. 

This is only a problem with the default cluster, in the subsequent clusters (created by the API) the cpucount is obtained from xCAT and entered correctly in the slurm-nodes.conf.

As a quick workaround I suggest the following for the default cluster.

On the controller:

```
[root@controller (dmaster) ]# lsdef compute -i cpucount
Object name: node001
    cpucount=8
Object name: node002
    cpucount=8
[root@controller (dmaster) ]# vi /cluster/vc-a/etc/slurm/slurm-nodes.conf
NodeName=c[001-002] CPUs=8 State=UNKNOWN                                                                                                                                                                                                                                                 
PartitionName=compute Nodes=c[001-002] Default=YES MaxTime=INFINITE State=UP 
```
You will have to add the `CPUs=<# of cpus>`  part using the information from the `lsdef` command. You may need to add multiple `NodeName` lines 

Now, ssh to the login node and restart slurm.

**Comment by abhimukh** [comment]
@hansthen To fix this issue without a manual workaround we have two options:

1. Fix it in the current version. Here the default cluster is still created by in the `cv_install_openstack` script. This will involve parsing JSON in a bash script and will make the script more complicated.

2. Fix it in the next version. Here we will need to rework the cluster creation workflow, so that even for the first cluster creation the script `cv_install_openstack` simply calls the API.

**Comment by hansthen** [comment]
@abhimukh This should not be assigned to QA until it is ready for testing.

**Comment by abhimukh** [comment]
@themisa This should be fixed in r5_dockerize. In this branch even for the first cluster the node allocation is done from the dashboard via the API. So the CPU count should be properly entered in the slurm-nodes.conf file.

**Comment by themisa** [comment]
**Version:** r6 ea67ae8

Note: now procedure changes - we don't allocate nodes initially, only sort them in hardware groups. (because in dockerize the openstack node is provisioned first, with the controller).
Then we restart the trinity_api 

For cluster a:
[root@login ~]# cat /etc/slurm/slurm-nodes.conf 
NodeName=c001 CPUS=32 State=UNKNOWN
PartitionName=container Nodes=c001 Default=Yes MaxTime=INFINITE State=UP
