### ISSUE TITLE
LDAP: Trinity LDAP server does not generate unique IDs for posixGroups

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#41]
We use the scheme described here: http://www.rexconsulting.net/ldap-protocol-uidNumber.html to support auto-incrementing numbers inside LDAP. However, currently we only have the userid numbers autoincremented. We should also add unique IDs for groups.

**Comment by themisa** [comment]
[root@login ~]# obol group list
150 power-users
151 admin
1050 john
152 users
1053 jane
