### ISSUE TITLE
Compute nodes: RPM database does not get flushed

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#411]
The rpm database in the compute nodes is stored in `/var/lib/rpm`.  The directory `/var` is mounted from a logical volume created on the local disk by the postbootscript `cv_configure_storage`. This script always preserves the contents of the `/var` on the local disk (either an existing logical volume is simply mounted or the contents of /var are copied over)

This results in stale state information being preserved (for example from previous deployments). This leads to inconsistencies, and in some cases failures, see e.g. #364

**Comment by hansthen** [comment]
As discussed. Items in /var/ that need to be stateless, we'll move to the memory filesystem during gemimage and make a symlink from /var to the other directory.

**Comment by abhimukh** [comment]
Assigning to @themisa for testing

**Comment by themisa** [comment]
seems fixed in 
**Version:** r5_fixes 29dcaf8
**Environment:** amaster

see also #364
