### ISSUE TITLE
xCAT controller installation: BMC setup fails for some hardware.

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#42]
FATAL: Module ipmi_si not found.
rm: cannot remove '/tmp/ipmicfg.xml':No such file or directory 
/bin/bmcsetup: line 45: 2182 Terminated                     allowcred.awk

Maybe we need a better procedure how to debug this type of issues.

See the below quotes from the xCAT mailing list.

've been able to successfully get bmcsetup to support several various 
hardware platforms with a little bit of tweaking in the bmcsetup script. 
If you look in the script you will see where it looks for model / vendor 
id and performs different functions based on those ID's. Figure out what 
it sees is that model's ID and create some if statements to get it to 
"talk" to the hardware the way it's expecting.

On 9/23/2014 8:05 AM, Jarrod B Johnson wrote:
>
> I would suggest ssh into the node, set -x in /bin/bmcsetup, and see 
> where it fails.  Consider skipping that step.  Unfortunately user 
> management is not the best part of the IPMI spec, and it isn't nicely 
> consistent vendor to vendor.
>

**Comment by hansthen** [comment]
These are not so much failures are mismatches between xCAT and kernel versions. E.g. rumour has it newer kernels come with ipmi_si built in.

**Comment by brunopereira81** [comment]
You are confusing 2 things here:

1 - the ipmi_si error, is normal, it happens while trying to load a kernel module that has beend replaced in recent kernels.

2 - the failure to read the ipmi conf file that should have been sent from the controller to the node right after the discovery packages ended.

**Comment by hansthen** [comment]
@brunopereira81 You are missing the point. On none of the nodes so far did the BMC setup actually fail. The error messages do not seem to indicate a hardware related failure. So it does not seem right to keep this bug open.

**Comment by hansthen** [comment]
@themisa 

If you do not experience any issues with BMC setup, we can QA verify this issue.
