### ISSUE TITLE
Controller's default partitioning scheme is not optimal

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#421]
The default partitioning scheme used during a node deployment is not optimal.

Normally anaconda will reserve something like 10% of the disk for / and the remaining space is used for /home which in a cluster environment does not make sense.

Current situation:
Controller is deployed
/ uses part of the full size available
/home uses the remaining space

eg:

[root@controller cvsupport]# df -h
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/rhel_controller-root   50G   33G   18G  65% /
devtmpfs                          7.7G     0  7.7G   0% /dev
tmpfs                             7.7G     0  7.7G   0% /dev/shm
tmpfs                             7.7G   18M  7.7G   1% /run
tmpfs                             7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/mapper/rhel_controller-home  407G  2.1G  405G   1% /home
/dev/sdi1                         497M  194M  303M  39% /boot

Optimal situation:
Controller is deployed;
/ uses full free space
no separate /home

More advanced configuration could use a separate /home, but unless there is a way of setting that up easy having no /home in a separate partition is better than having it occupy 90% of the disk.

**Comment by hansthen** [comment]
This controller was manually partitioned by a nitwit (me). The default partitioning scheme is as @brunopereira81 suggested.
