### ISSUE TITLE
colander: node001 fails to start pcs

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#425]
**Version:** colander c991fbc
**Environment:** amaster

In the colander branch, when node001 (controller-1) is shut off, then turned back on (so it would become the secondary controller), pcs status returns an error (cluster not available)

**Comment by hansthen** [comment]
See my explanation for #426. Can you test this again?

**Comment by themisa** [comment]
**Version:** colander c991fbc


Still failing - controller-1 is now secondary node, after services passed to controller-2.
But controller-1 not syncing. 

[root@controller-1(unknown) ~]# pcs status
Error: cluster is not currently running on this node
[root@controller-1(unknown) ~]# cat /proc/drbd
version: 8.4.6 (api:1/proto:86-101)
GIT-hash: 833d830e0152d1e457fa7856e71e11248ccf3f70 build by phil@Build64R7, 2015-04-10 05:13:52

(

**Comment by themisa** [comment]
manual workaround: pcs cluster start

**Comment by hansthen** [comment]
@Marc69 Can you test this again?

**Comment by Marc69** [comment]
**Version:** r6 6859708
**Environment:** unknown

Still not working

**Comment by Marc69** [comment]
**Version:** r6 10cffc2
**Environment:** amaster

Looks fine now

**Comment by Marc69** [comment]
Works fine in
**Version:** r6 aa08d39
**Environment:** amaster
