### ISSUE TITLE
Version mismatch between drbd kernel and utils

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#433]
**Version:** colander c991fbc
**Environment:** amaster

```
[root@controller-1(amaster) ~]# drbdadm | tail -4 
Version: 8.9.3 (api:1)
GIT-hash: b06f4b40acc56206f411612cc4df56f4c511756c build by mockbuild@, 2015-08-15 12:06:02

No command specified
[root@controller-1(amaster) ~]# cat /proc/drbd
version: 8.4.6 (api:1/proto:86-101)
GIT-hash: 833d830e0152d1e457fa7856e71e11248ccf3f70 build by phil@Build64R7, 2015-04-10 05:13:52

 1: cs:SyncSource ro:Primary/Secondary ds:UpToDate/Inconsistent C r---a-
    ns:39299964 nr:0 dw:40010044 dr:39257 al:1909 bm:0 lo:739 pe:1452 ua:0 ap:2048 ep:1 wo:f oos:94991724
	[====>...............] sync'ed: 29.3% (92764/131064)M
	finish: 1:56:43 speed: 13,556 (10,832) K/sec (stalled)
```

**Comment by Marc69** [comment]
**Version:** r6 10cffc2
**Environment:** amaster

Still the same:

[root@controller-2(amaster*) ~]# drbdadm | tail -4
Version: 8.9.2 (api:1)
GIT-hash: de9236084d57a09160b366e5fdf5b481c5cc163d build by mockbuild@, 2015-05-16 11:37:39

No command specified
[root@controller-2(amaster*) ~]# cat /proc/drbd
version: 8.4.6 (api:1/proto:86-101)
GIT-hash: 833d830e0152d1e457fa7856e71e11248ccf3f70 build by phil@Build64R7, 2015-04-10 05:13:52

 1: cs:Connected ro:Primary/Secondary ds:UpToDate/UpToDate C r-----
    ns:393804 nr:0 dw:38012 dr:722441 al:23 bm:0 lo:0 pe:0 ua:0 ap:0 ep:1 wo:f oos:0

**Comment by themisa** [comment]
**Version:** r6 cc03c73
**Environment:** amaster

Not fixed.

```
[root@controller-1(unknown*) ~]# drbdadm | tail -4 
Version: 8.9.2 (api:1)
GIT-hash: de9236084d57a09160b366e5fdf5b481c5cc163d build by mockbuild@, 2015-05-16 11:37:39

No command specified
[root@controller-1(unknown*) ~]# cat /proc/drbd
version: 8.4.6 (api:1/proto:86-101)
GIT-hash: 833d830e0152d1e457fa7856e71e11248ccf3f70 build by phil@Build64R7, 2015-04-10 05:13:52

 1: cs:SyncSource ro:Primary/Secondary ds:UpToDate/Inconsistent C r-----
    ns:59194164 nr:0 dw:59217268 dr:122377 al:2892 bm:0 lo:0 pe:0 ua:0 ap:0 ep:1 wo:f oos:679500956
        [>...................] sync'ed:  8.1% (663572/721288)M
        finish: 86:40:15 speed: 2,164 (11,100) K/sec
```

**Comment by themisa** [comment]
Actually we want versions to be 8.9.2 ( as opposed to 8.9.3)  and 8.4.6, so this is actually fixed.

**Comment by jonathanselea** [comment]
![2015-11-21 14_26_13-192 168 1 3 - putty](https://cloud.githubusercontent.com/assets/10996038/11318699/4d557702-905d-11e5-8c2d-1eaab6aae41f.png)
