### ISSUE TITLE
Controller installation: IPMI userid and password not set

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#44]
Needs to be added to the ipmi table:

e.g: "compute","/\z/-bmc/","0","root","system",,,,

**Comment by brunopereira81** [comment]
> node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable

node: node
bmc: node-bmc
bmcport: 0
taggedvlan: root
bmcid: system
username: ""
password: ""
comments: ""
disable: ""

[root@controller ~]# tabdump ipmi
#node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable
"compute","/\z/-bmc/","0","root","system",,,,

**Comment by hansthen** [comment]
The table is a few commas off.
"compute","/\z/-bmc/","0",,,"root","system",,
