### ISSUE TITLE
Installing controller should be more verbose in log files

### ISSUE THREAD

**Issue by linuxstudio** [clustervision/trinity#45]
Suppose that you are installing a controller, and have reached the stage where xcat.log says:

Complete!

Then it's not said that the controller installation has already finished.

To check the actual status we should look at the file:

/var/log/postinstall.log 

but at the moment that file is not verbose enough to give an idea of the current stage of the installation.

I would expect something like:

[root@controller ~]# tail -400f /var/log/postinstall.log 
slapd installed
copying now module xyz....
copying now module xyz....DONE
finalizing installation...
finalizing installation...DONE
Controller installation complete!

**Comment by hansthen** [comment]
Yes, we should add a better logging framework. However, it is not trivial. The question is largely how can we detect and assess failures. We need to check each bash command for its status. Can we do that generically? What types of error messages can we ignore?

**Comment by linuxstudio** [comment]
Another thing that should be nice to have, for a future milestone, is that:
1) the console of the just installed controller (/etc/issue) should show something like:

"Installation still in progress: please check /var/log/xcat/xcat.log"

2) whenever someone logs in via ssh, he should get a message (/etc/motd) that says a similar thing as the above:

"Installation still in progress: please check /var/log/xcat/xcat.log"

It's just a matter of doing:

    [root@c7build ~]# vim /etc/issue
    \S
    Kernel \r on an \m
    
    Installation still in progress: please check /var/log/xcat/xcat.log

and

    vim /etc/motd

**Comment by linuxstudio** [comment]
Further on this point, the current `postinstall.log` contains misleading output:

    [root@controller xcatpost]# cat /var/log/postinstall.log 
    xcat installed
    slapd installed
    docker installed

The above output was taken from a controller which had the `cv_install_xcat` not completed correctly, due to not being able to access the repositories.
I will create a separate bug for this.

**Comment by hansthen** [comment]
The procedure to check for errors this is to scan /var/log/xcat/xcat.log. We are currently not in a position to (easily) report on all possible failures, so we rely on engineers to interpret the contents of that log file. 

We could of course balk when an error occurs, but this has severe disadvantages for development. When an xCAT postscript return a non-zero state the installation will fail and in some cases even go into an installation loop. In many cases it is more convenient to log into the system for debugging purposes.

The "xcat/slapd/docker installed" messages are simply there for convenience, so you can see which of the postscripts actually completed.

**Comment by themisa** [comment]
@hansthen, should we close this bug?

**Comment by hansthen** [comment]
Yes.
