### ISSUE TITLE
r5_dockerize: login-a not reachable 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#457]
**Version:** r5_dockerize af84cae
**Environment:** dmaster

(disclaimer: this was after a node reset)

The login-a, was not reachable. After makedns it became reachable again.

**Comment by abhimukh** [comment]
@themisa The commit message had a typo. Could you reproduce this issue?

**Comment by themisa** [comment]
Not seen in **Version:** r6 ea67ae8
