### ISSUE TITLE
limits do not seem to be correctly set in newly installed xcat compute nodes

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#459]
In statefull nodes right after provisioning there seems to be bad limits settings in the nodes compared with the controller, limits need to be set correctly in all nodes to avoid issues when running jobs in the cluster:

[root@node01 ~]# ulimit -l
64

[root@controller ~]# ulimit -l
unlimited

[root@controller ~]# cat /etc/security/limits.d/21-trinity-limits.conf
\# To avoid segfault when running OpenMPI applications as non-root user
*   -   memlock     unlimited

[root@controller ~]# lsdef node01
Object name: node01
    addkcmdline=selinux=0
    arch=x86_64
    bmc=node01.ipmi
    bmcpassword=ucd150192
    bmcusername=admin
    chain=runcmd=bmcsetup,osimage=rhel7.1-x86_64-install-compute
    cpucount=48
    cputype=Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
    currchain=boot
    currstate=boot
    disksize=sda:500GB
    groups=compute
    initrd=xcat/osimage/rhel7.1-x86_64-install-compute/initrd.img
    kcmdline=quiet repo=http://!myipfn!:80/install/rhel7.1/x86_64 ks=http://!myipfn!:80/install/autoinst/node01 ksdevice=44:a8:42:3b:ec:a7
    kernel=xcat/osimage/rhel7.1-x86_64-install-compute/vmlinuz
    mac=44:a8:42:3b:ec:a7
    memory=128960MB
    mgt=ipmi
    netboot=xnba
    nicips.ib0=10.149.0.1
    nicnetworks.ib0=ibnet
    nictypes.ib0=ethernet
    os=rhel7.1
    postbootscripts=otherpkgs,cv_dub_compute,setup-gpfs
    postscripts=syslog,remoteshell,syncfiles,confignics,setupntp,cv_setup-ldap
    power=ipmi
    primarynic=mac
    profile=compute
    provmethod=rhel7.1-x86_64-install-compute
    serial=29WW762
    status=booted
    statustime=09-25-2015 10:18:53
    supportedarchs=x86,x86_64
    updatestatus=synced
    updatestatustime=09-25-2015 09:56:25

[root@controller ~]# lsdef -t osimage rhel7.1-x86_64-install-compute
Object name: rhel7.1-x86_64-install-compute
    exlist=/install/custom/install/rhel/compute.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhel7.1-x86_64
    osname=Linux
    osvers=rhel7.1
    otherpkgdir=/install/post/otherpkgs/rhel7.1/x86_64
    otherpkglist=/install/custom/install/rhel/compute.otherpkgs
    permission=755
    pkgdir=/install/rhel7.1/x86_64
    pkglist=/install/custom/install/rhel/compute.pkglist
    postbootscripts=cv_dub_compute
    postinstall=/install/custom/install/rhel/compute.postinstall
    profile=compute
    provmethod=install

**Comment by hansthen** [comment]
This bug is only valid for the Dublin install, which is a pure xCAT based install (though very much like Trinity) done by Antony.
