### ISSUE TITLE
r6: /trinity/clustervision not copied

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#463]
**Version:** r6 ea67ae8
**Environment:** dmaster

/trinity/clustervision is empty (and hence no modulefiles/apps)

```
[root@node001 clustervision]# ls /trinity/clustervision
[root@node001 clustervision]# 
```

**Comment by themisa** [comment]
Not fixed in: r6 fd7ea53

```
[root@node001 ~]# ls /trinity/clustervision
ls: cannot access /trinity/clustervision: No such file or directory
```
the apps, modulefiles got copied directly under /trinity, not /trinity/clustervision

```
[root@node001 ~]# ls /trinity
apps  cinder  compute  container  glance  horizon  keystone  login  mariadb  modulefiles  nova  nova_controller  openldap  openstack  rabbitmq  report  testing  version
```

**Comment by hansthen** [comment]
Can you quote the full output of /trinity/report?

**Comment by themisa** [comment]
[root@controller(amaster*) ~]# /trinity/report
**Version:** r6 fd7ea53
**Environment:** amaster

**Comment by themisa** [comment]
[root@controller(unknown*) ~]# /trinity/report
cat: /trinity/site: No such file or directory
**Version:** r6 8b08aa5
**Environment:** unknown
[root@controller(unknown*) ~]# ls /trinity/clustervision
ls: cannot access /trinity/clustervision: No such file or directory

**Comment by themisa** [comment]
**Version:** r6_fixes d272d08
**Environment:** tmaster

This has been fixed. 

```
[root@controller ~]# ls /trinity/clustervision/apps
gcc  hpcc  imb  intel  mvapich2  openmpi
```
