### ISSUE TITLE
Question about HPC and Docker part!

### ISSUE THREAD

**Issue by mmrezaie** [clustervision/trinity#464]
This is a question for me. Maybe I am missing some documentation. The question is: 

- when I allocate myself couple of nodes from the HPC part of the interface. Do I get couple of nodes the way SLURM gives them after you do salloc in SLURM? 

- Further If it is, then are all the nodes that I have got running in a container or only the login node that is assigned to me is in docker container?

**Comment by hansthen** [comment]
It is roughly comparable to salloc, but with a few important differences.

Typically, from the HPC part of the interface, the administrator of the cluster as a whole will allocate HPC resources to a "tenant"  (also called "project"). The tenant will have a private virtual HPC cluster, with a private administrator account, a private login node, private user accounts and their own compute resources. Each virtual cluster will have a private slurm scheduling daemon, which will schedule only on the compute nodes allocated to that cluster.

All the "compute nodes" for the virtual cluster are running in a container (so "compute containers" would be a more appropriate term). The login node for a virtual cluster runs inside a Virtual Machine.

**Comment by mmrezaie** [comment]
I had some problems when I was running CUDA applications inside docker containers, because of the incompatibilities between the libraries in the container and driver at the host. How you address this in Trinity. I imagine users won't be able to chose the operating system in the HPC compute containers. Right?

 Also do you support fine grained resource allocations too? Inside the virtual HPC cluster and as a whole? In know SLURM supports it but resource interference can be issue.

**Comment by mmrezaie** [comment]
Also about those hpc compute containers,

Are they launched using lxc or libcontainer?

**Comment by hansthen** [comment]
In case of incompatibilities between the container and the host driver, we would advise to do either one of the following:
1. match the OS version of the container to the host OS.
2. push the user space libraries that depend on specific versions of the host OS into the modules environment.

At the moment we do not support fine grained resource allocations for the cluster as a whole. Nodes are uniquely allocated to a virtual cluster. For fine grained resource allocation inside a virtual cluster, we use whatever SLURM offers. For completeness, Trinity also supports a deployment scenario in which several tenants share a single cluster (and a single SLURM scheduler). 

Compute containers are launched using libcontainer. We are evaluating lxd at the moment, but do not expect it any time soon.

**Comment by mmrezaie** [comment]
Thank you very much for all the information and your time.

It may not related to Trinity's vision but do you think to manager the virtual cluster something like Mesos or Kubernetes would also be a very good option? For data analytics groups usually the system utilization is not comparable to what HPC groups are getting (It's way lower). Do you think having this option - Mesos instead of Slurm as resource manager - to control the virtual clusters, can be one of the feasible and valuable next steps for Trinity. I would think the underlying physical cluster still should be Slurm.

**Comment by hansthen** [comment]
Yes it is an option. I think that currently that is possible in OpenStack liberty, with the introduction of OpenStack magnum. So once we upgrade to OpenStack liberty, that feature will be available automatically.
