### ISSUE TITLE
pmaster has no working switch configuration

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#466]
switch in pmaster is present and has an assigned ip, but pmaster has no interface in that range: switch is not pingable.

[root@pmaster ~]# ifconfig | egrep "inet|flags"
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.181.2  netmask 255.255.0.0  broadcast 10.1.255.255
        inet6 fe80::f21f:afff:fed4:2f07  prefixlen 64  scopeid 0x20<link>
em2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.254  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::f21f:afff:fed4:2f08  prefixlen 64  scopeid 0x20<link>
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>

[root@pmaster ~]# host switch
switch.cluster has address 192.168.192.168

[root@pmaster ~]# cat /trinity/version 
* (detached from vMagdeburg)
269bf23

**Comment by hansthen** [comment]
Seems okay to me (and anyway is not part of trinity itself).
```
[root@pmaster ~]# ip a show dev em2
3: em2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether f0:1f:af:d4:2f:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.254/24 brd 192.168.1.255 scope global em2
       valid_lft forever preferred_lft forever
    inet 192.168.8.254/24 brd 192.168.8.255 scope global em2
       valid_lft forever preferred_lft forever
    inet 192.168.192.1/24 brd 192.168.192.255 scope global em2:switch
       valid_lft forever preferred_lft forever
    inet6 fe80::f21f:afff:fed4:2f08/64 scope link 
       valid_lft forever preferred_lft forever

[root@pmaster ~]# ping -q -c3 switch
PING switch (192.168.192.168) 56(84) bytes of data.

--- switch ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.959/0.968/0.975/0.026 ms
```
