### ISSUE TITLE
New deployed controller node has invalid NFS mount

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#469]
mount | grep nfs
192.168.1.254:/trinity on /tmp/trinity type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.1,local_lock=none,addr=192.168.1.254)

And in /var/log/messages:
Oct  8 12:26:35 controller kernel: nfs: server 192.168.1.254 not responding, timed out
Oct  8 12:34:55 controller kernel: nfs: server 192.168.1.254 not responding, timed out
Oct  8 12:37:56 controller kernel: nfs: server 192.168.1.254 not responding, timed out
Oct  8 12:41:03 controller kernel: nfs: server 192.168.1.254 not responding, timed out

This should be umounted after a deployment.

[root@controller(unknown*) ~]# cat /trinity/version 
* (detached from vMagdeburg)
269bf23

**Comment by brunopereira81** [comment]
And yes, umounting it manually works, or a reboot, but it should not be there anyways.

**Comment by hansthen** [comment]
@brunopereira81 
You are right. However, we use the "stale mount" for debugging purposes during development. The idea is that if we ship the controller it will reboot and the mount will be gone. 

I agree it would be cleaner to remove it.
Can I ask you for now (and in the near future) to manually remove the mount if you think that is required?

**Comment by brunopereira81** [comment]
@hansthen yes, we can umount it before removing the uplink to the controller that was deploying, still think it should be cleanly umount if not used during your scripts.
