### ISSUE TITLE
Switch configuration is broken, no networks, no routes and no interfaces configuration after deployment

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#471]
### Issue

If I have a switch that I need to configure to match the defined configuration in my controller's xCAT I would not be able to reach that switch even if I configured the switch correctly

**List of present interfaces in the controller:**

`[root@controller(unknown*) ~]# ifconfig | egrep "inet|flags"
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.146.255.254  netmask 255.255.0.0  broadcast 0.0.0.0
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.180.142  netmask 255.255.0.0  broadcast 10.1.255.255
        inet6 fe80::ec4:7aff:fe69:b586  prefixlen 64  scopeid 0x20<link>
eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.141.255.254  netmask 255.255.0.0  broadcast 10.141.255.255
        inet6 fe80::ec4:7aff:fe69:b587  prefixlen 64  scopeid 0x20<link>
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>``

**Network configuration files not present:**

`[root@controller(unknown*) ~]# cat /etc/sysconfig/network-scripts/ifcfg-eno3
cat: /etc/sysconfig/network-scripts/ifcfg-eno3: No such file or directory
[root@controller(unknown*) ~]# cat /etc/sysconfig/network-scripts/ifcfg-em3
cat: /etc/sysconfig/network-scripts/ifcfg-em3: No such file or directory`

**Defined network for the switches in the the controller:**

`[root@controller(unknown*) ~]# tabdump networks | grep switch
"switch_net","192.168.192.0","255.255.255.0","em3",,,,,,,,,,,,,,,`

**Hostname and IP address of the defined switch in the system:**

`[root@controller(unknown*) ~]# host switch
switch.cluster has address 192.168.192.168`

**Fix**

A interface needs to be in the same network as the network for the switches, eg:

eno2 is connected to my internal network: 

`[root@controller(unknown*) ~]# ifconfig eno2 | grep inet
        inet 10.141.255.254  netmask 255.255.0.0  broadcast 10.141.255.255
        inet6 fe80::ec4:7aff:fe69:b587  prefixlen 64  scopeid 0x20<link>
[root@controller(unknown*) ~]# tabdump networks | grep inter
"internal_net","10.141.0.0","255.255.0.0","eno2","10.141.255.254","10.141.255.254","10.141.255.254","10.141.255.254",,,"10.141.230.1-10.141.239.254",,,,,,,,`

My internal network is connected to the same port the the switch management interface, so we create an alias using that interface that allows us to reach that network:

**Before**

`[root@controller(unknown*) ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.1.101.101    0.0.0.0         UG    0      0        0 eno1
10.1.0.0        0.0.0.0         255.255.0.0     U     0      0        0 eno1
10.141.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
10.146.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
10.148.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eno1
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 eno2
172.16.0.0      0.0.0.0         255.240.0.0     U     0      0        0 eno2`

**Fix**

`[root@controller(unknown*) ~]# ifconfig eno2:ipmi 192.168.255.254/24`

**After**

`[root@controller(unknown*) ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.1.101.101    0.0.0.0         UG    0      0        0 eno1
10.1.0.0        0.0.0.0         255.255.0.0     U     0      0        0 eno1
10.141.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
10.146.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
10.148.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eno2
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eno1
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 eno2
172.16.0.0      0.0.0.0         255.240.0.0     U     0      0        0 eno2
192.168.255.0   0.0.0.0         255.255.255.0   U     0      0        0 eno2`

**Comment by hansthen** [comment]
We expect engineering to configure the switch(es) in the xCAT tables. We have no way of determining what switches are there and what IP addresses they will have. 

The example switch entry is simply that: an example.
