### ISSUE TITLE
After deploying a controller we have "unknown" in our bash prompt

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#474]
### Issue

After deploying the cluster our bash prompt looks like `[root@controller(unknown*)`.

This comes from your .bashrc file:

> if hash git 2> /dev/null ; then
    PS1="[\u@\h(\$(cat /trinity/site 2> /dev/null || echo "unknown" | head -1)\$([ \$(git status -s 2> /dev/null | wc -l) == 0 ] || echo '*')) \W]\\$ "
    if [ -f /home/$(logname)/.gitconfig ]; then
        export GIT_AUTHOR_EMAIL=$(cat /home/$(logname)/.gitconfig | grep "email =" | awk -F= '{print $2}')
        export GIT_AUTHOR_NAME=$(cat /home/$(logname)/.gitconfig | grep "name =" | awk -F= '{print $2}')
        export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
        export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
    fi
else
    PS1="[\u@\h($(cat /trinity/site > /dev/null || echo "unknown" | head -1)) \W]\\$ "
fi

Can I suggest that if there is not a file in that path that the unknown is dropped by default and if there is a file there that this information is added to our bash prompt?

**Comment by hansthen** [comment]
We want engineers to add the site name to the prompt. This can be done using 
```
echo 12456 > /trinity/site
```
