### ISSUE TITLE
containers: slurm/munge issues

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#477]
* r6
fd7ea53
 M controller/rootimg/install/postscripts/cv_install_dockerize

After allocating containers to vc-a,  starting slurm on login.vc-a and service trinity force-reload on containers , we get following slurm errors:

```
[root@c001 /]# sinfo
sinfo: error: slurm_receive_msg: Zero Bytes were transmitted or received
slurm_load_partitions: Zero Bytes were transmitted or received
[root@c001 /]# 
```

**Comment by abhimukh** [comment]
From` /var/log/slurm/slurmctld.log`
```
[2015-10-09T08:50:15.259] error: Munge decode failed: Invalid credential
[2015-10-09T08:50:15.259] error: authentication: Invalid credential
[2015-10-09T08:50:15.259] error: slurm_receive_msg: Protocol authentication error
[2015-10-09T08:50:15.269] error: slurm_receive_msg: Protocol authentication error
```
Manual workaround

restart Munge and Slurm on the login node and then force-reload Trinity on the compute nodes

```
[root@login ~]# service munge restart
Redirecting to /bin/systemctl restart  munge.service
[root@login ~]# service slurm restart
Restarting slurm (via systemctl):                          [  OK  ]
[root@node001 ~]# service trinity force-reload
[root@node002 ~]# service trinity force-reload
[root@node002 ~]# docker-enter trinity
[root@c002 /]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      2   idle c[001-002]
```

**Comment by abhimukh** [comment]
These are the steps I followed

1. Provision the controller with r6 (dockerized version). 
    a. At the end when the controller was up and running, I had all the openstack controller services in docker containers. 
    b. The login node for the first cluster had been created.
    c. Slurm on the login node cloud not start because the slurm-node.conf was empty (this is expected) 
2. I added node[001-002] to the group compute, and ran makehosts and makedns for them.
3. I added the container c[001-002] to the group hw-generic. DID NOT run makehosts or makedns for them.
4. Restarted the trinity_api
5. Fired up the dashboard, logged in as admin and allocated one node to vc-a. This node happens to be c001. 
6. I checked on node001 that the container had been started.
7. Restarted slurm on the login node. Now slurm cloud start but 
```
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1   unk* c001
```
8. I checked the munge log file /var/log/munge/munge.log

```
[root@login ~]# cat /var/log/munge/munged.log   
2015-10-12 17:19:45 +0200 Notice:    Running on "login-a.vc-a" (172.16.255.254)
2015-10-12 17:19:45 +0200 Info:      PRNG seeded with 1024 bytes from "/dev/urandom"
2015-10-12 17:19:45 +0200 Info:      Updating supplementary group mapping every 3600 seconds
2015-10-12 17:19:45 +0200 Info:      Enabled supplementary group mtime check of "/etc/group"
2015-10-12 17:19:45 +0200 Notice:    Starting munge-0.5.11 daemon (pid 12390)
2015-10-12 17:19:45 +0200 Info:      Created 2 work threads
2015-10-12 17:19:45 +0200 Info:      Found 2 users with supplementary groups in 0.007 seconds
2015-10-13 12:04:07 +0200 Info:      Invalid credential
2015-10-13 12:04:08 +0200 Info:      Invalid credential
```
Looks like the problem is that ntp takes a while to stabilize (note that we point it to the controller as the ntp server in the cloud-init script). This ends up confusing munge.

9. I restarted munge. This ends up "solving" the problem

```
[root@login ~]# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
container*    up   infinite      1   idle c001
```

**Comment by themisa** [comment]
Note: this is only for login-a. Subsequent login nodes created after a partition don't need munge restarted.

**Comment by themisa** [comment]
* make creation of vc-a part of clusterbats

**Comment by themisa** [comment]
Either clusterbats or cron job.

**Comment by themisa** [comment]
**Version:** r7_login_image cdb1e43
**Environment:** dmaster


creation of vc-a is now part of clusterbats.

```
[root@login ~]# sinfo
PARTITION   AVAIL  TIMELIMIT  NODES  STATE NODELIST
containers*    up   infinite      1  down* c002
containers*    up   infinite      3   idle c[001,003-004]
```
