### ISSUE TITLE
hosts table in a controller assumes pre-defined hostnames for compute nodes

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#478]
Having a look at the hosts table we can find the line:

`"compute","|\D+(\d+)$|10.141.((($1-1)/255)).(($1-1)%255+1)|","|\D+(\d+)$|node($1)|","|\D+(\d+)$|node($1)-bmc:10.148.((($1-1)/255)).(($1-1)%255+1),node($1)-ib:10.149.((($1-1)/255)).(($1-1)%255+1)|",,`

which assumes that the hostname of our nodes is **node**, this regex needs to be cleaned a bit in a way that we can use more flexible hostnames in our setup.

**Comment by hansthen** [comment]
Node names are fixed. This is by design. This is required at multiple locations in our code, and we are not going to fix this at any short notice.
