### ISSUE TITLE
networks table has bad configuration on bmc_net.nameserver

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#479]
### Issue:

> [root@controller(magdeburg*) ~]# host n001
n001.cluster has address 10.141.0.1
[root@controller(magdeburg*) ~]# host n001-bmc
Host n001-bmc not found: 3(NXDOMAIN)

In the networks table bmc_net.nameserver=10.148.255.254, this prevents `makedns -n` from populating DNS with the n-bmc entries (hostname addresses for the bmc interfaces in the nodes):

`makedns -n`
>Handling n003-bmc in /etc/hosts.
Ignoring host n003-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.

### Fix:

Removing the nameserver entry from the networks table allows proper DNS to be populated:

>[root@controller(magdeburg*) network-scripts]# makedns -n
Handling n002 in /etc/hosts.
Handling c003 in /etc/hosts.
Handling switch01 in /etc/hosts.
Handling n004-ib in /etc/hosts.
Ignoring host n004-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling n004-bmc in /etc/hosts.
Handling n001 in /etc/hosts.
Handling n003-ib in /etc/hosts.
Ignoring host n003-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling n004 in /etc/hosts.
Handling c002 in /etc/hosts.
Handling openstack in /etc/hosts.
Handling login-a in /etc/hosts.
Handling openstack-bmc in /etc/hosts.
Handling n002-ib in /etc/hosts.
Ignoring host n002-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling controller in /etc/hosts.
Handling c004 in /etc/hosts.
Handling n003-bmc in /etc/hosts.
Handling c001 in /etc/hosts.
Handling n002-bmc in /etc/hosts.
Handling n001-bmc in /etc/hosts.
Handling localhost in /etc/hosts.
Handling switch04 in /etc/hosts.
Handling n003 in /etc/hosts.
Handling n001-ib in /etc/hosts.
Ignoring host n001-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling switch03 in /etc/hosts.
Handling switch02 in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
[root@controller(magdeburg*) network-scripts]# host n001-bmc
n001-bmc.cluster has address 10.148.0.1

**Comment by hansthen** [comment]
This is by design. We do not want the bmc addresses in DNS. We only want them accessible from the controller host.

**Comment by brunopereira81** [comment]
Hi, I disagree that this should be closed.

To explain you better what is happening here is a log, it starts with a fixed system, I then add the nameserver that was present before I fixed it and remake my hosts file (just to show off, you can see it has no differences from the previous one) and re-populate my named with that information:

> [BEGIN] 10/13/2015 4:33:28 PM
[root@controller(magdeburg*) ~]# echo fixed
fixed
[root@controller(magdeburg*) ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"internal_net","10.141.0.0","255.255.0.0","eno2","10.141.255.254","10.141.255.254","10.141.255.254","10.141.255.254",,,"10.141.230.1-10.141.239.254",,,,,,,,
"bmc_net","10.148.0.0","255.255.0.0","eno2","10.148.255.254",,,,,,,,,,,,,,
"vc_a_net","172.16.0.0","255.255.0.0","eno2","<xcatmaster>",,,,,,,,,,,,"vc-a",,
"switch_net","192.168.192.0","255.255.255.0","eno2",,,,,,,,,,,,,,,
[root@controller(magdeburg*) ~]# host node001-bmc
node001-bmc.cluster has address 10.148.0.1
[root@controller(magdeburg*) ~]# edit networks
-bash: edit: command not found
[root@controller(magdeburg*) ~]# tabedit networks
[root@controller(magdeburg*) ~]# cat /etc/hosts
127.0.0.1 localhost
10.141.0.1 node001 node001.cluster n001
10.148.0.1 node001-bmc node001-bmc.cluster 
10.149.0.1 node001-ib node001-ib.cluster 
10.141.0.2 node002 node002.cluster n002
10.148.0.2 node002-bmc node002-bmc.cluster 
10.149.0.2 node002-ib node002-ib.cluster 
10.141.0.3 node003 node003.cluster n003
10.148.0.3 node003-bmc node003-bmc.cluster 
10.149.0.3 node003-ib node003-ib.cluster 
10.141.0.4 node004 node004.cluster n004
10.148.0.4 node004-bmc node004-bmc.cluster 
10.149.0.4 node004-ib node004-ib.cluster 
10.141.255.1 openstack openstack.cluster 
10.148.255.1 openstack-bmc openstack-bmc.cluster 
192.168.192.168 switch01 switch01.cluster 
192.168.192.169 switch02 switch02.cluster 
192.168.192.170 switch03 switch03.cluster 
192.168.192.171 switch04 switch04.cluster 
10.141.255.254 controller controller.cluster 
172.16.0.1 c001 c001.vc-a 
172.16.0.2 c002 c002.vc-a 
172.16.0.3 c003 c003.vc-a 
172.16.0.4 c004 c004.vc-a 
172.16.255.254 login-a login.vc-a 
[root@controller(magdeburg*) ~]# makehosts -n
[root@controller(magdeburg*) ~]# cat /etc/hosts
127.0.0.1 localhost
10.141.0.1 node001 node001.cluster n001
10.148.0.1 node001-bmc node001-bmc.cluster 
10.149.0.1 node001-ib node001-ib.cluster 
10.141.0.2 node002 node002.cluster n002
10.148.0.2 node002-bmc node002-bmc.cluster 
10.149.0.2 node002-ib node002-ib.cluster 
10.141.0.3 node003 node003.cluster n003
10.148.0.3 node003-bmc node003-bmc.cluster 
10.149.0.3 node003-ib node003-ib.cluster 
10.141.0.4 node004 node004.cluster n004
10.148.0.4 node004-bmc node004-bmc.cluster 
10.149.0.4 node004-ib node004-ib.cluster 
10.141.255.250 openstack openstack.cluster 
10.148.255.250 openstack-bmc openstack-bmc.cluster 
192.168.192.168 switch01 switch01.cluster 
192.168.192.169 switch02 switch02.cluster 
192.168.192.170 switch03 switch03.cluster 
192.168.192.171 switch04 switch04.cluster 
10.141.255.254 controller controller.cluster 
172.16.0.1 c001 c001.vc-a 
172.16.0.2 c002 c002.vc-a 
172.16.0.3 c003 c003.vc-a 
172.16.0.4 c004 c004.vc-a 
172.16.255.254 login-a login.vc-a 
[root@controller(magdeburg*) ~]# makedns -n
Handling node002 in /etc/hosts.
Handling c003 in /etc/hosts.
Handling switch01 in /etc/hosts.
Handling node004-ib in /etc/hosts.
Ignoring host node004-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling node004-bmc in /etc/hosts.
Ignoring host node004-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling node001 in /etc/hosts.
Handling node003-ib in /etc/hosts.
Ignoring host node003-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling node004 in /etc/hosts.
Handling c002 in /etc/hosts.
Handling login-a in /etc/hosts.
Handling node002-ib in /etc/hosts.
Ignoring host node002-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling controller in /etc/hosts.
Handling openstack-bmc in /etc/hosts.
Ignoring host openstack-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c004 in /etc/hosts.
Handling node003-bmc in /etc/hosts.
Ignoring host node003-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c001 in /etc/hosts.
Handling openstack in /etc/hosts.
Handling node002-bmc in /etc/hosts.
Ignoring host node002-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling node001-bmc in /etc/hosts.
Ignoring host node001-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling localhost in /etc/hosts.
Handling switch04 in /etc/hosts.
Handling node003 in /etc/hosts.
Handling node001-ib in /etc/hosts.
Ignoring host node001-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling switch03 in /etc/hosts.
Handling switch02 in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
[root@controller(magdeburg*) ~]# host node001-bmc
Host node001-bmc not found: 3(NXDOMAIN)
[root@controller(magdeburg*) ~]# host node001-bmc.cluster
Host node001-bmc.cluster not found: 3(NXDOMAIN)
[root@controller(magdeburg*) ~]# echo broken!
broken!
[END] 10/13/2015 4:36:01 PM

As you can see adding the nameserver to the networks table treats the bmc network as using an external DNS and prevents the hostname from being resolved.

This breaks bmcsetup since xCAT requires DNS to translate the node's bmc entry declared in its definitions:

[root@controller(magdeburg*) ~]# lsdef node001 -i bmc
Object name: node001
    bmc=node001-bmc

**Comment by brunopereira81** [comment]
Hi, this is still closed and easily testable, could you please review this bug?

**Comment by brunopereira81** [comment]
This is still present in R7:

```
[root@controller(150280*) ~]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable
"internal_net","10.141.0.0","255.255.0.0","eno2","10.141.255.254","10.141.255.254","10.141.255.254","10.141.255.254",,,"10.141.230.1-10.141.239.254",,,,,,,,
"bmc_net","10.148.0.0","255.255.0.0","eno2","10.148.255.1",,,"10.141.255.254",,,,,,,,,,,
"vc_a_net","172.16.0.0","255.255.0.0","eno2","<xcatmaster>",,,,,,,,,,,,"vc-a",,
"switch_net","192.168.192.0","255.255.255.0","em3",,,,,,,,,,,,,,,
```

```
[root@controller(150280*) ~]# host node001-bmc
Host node001-bmc not found: 3(NXDOMAIN)
[root@controller(150280*) ~]# makedns -n
Handling node002 in /etc/hosts.
Handling c003 in /etc/hosts.
Handling node001 in /etc/hosts.
Handling switch in /etc/hosts.
Handling node003-ib in /etc/hosts.
Ignoring host node003-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c002 in /etc/hosts.
Handling login-a in /etc/hosts.
Handling node002-ib in /etc/hosts.
Ignoring host node002-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling storage02 in /etc/hosts.
Handling controller in /etc/hosts.
Handling node003-bmc in /etc/hosts.
Ignoring host node003-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c001 in /etc/hosts.
Handling node002-bmc in /etc/hosts.
Ignoring host node002-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling node001-bmc in /etc/hosts.
Ignoring host node001-bmc, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling localhost in /etc/hosts.
Handling node003 in /etc/hosts.
Handling node001-ib in /etc/hosts.
Ignoring host node001-ib, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
```
