### ISSUE TITLE
Containers: docker-enter or exec takes a long time

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#486]
```
[root@node055 ~]# cat /trinity/version
* r5
34a01f3
```
Sometimes docker-enter trinity or docker exec trinity <command> takes a long time.  
```
[root@node055 ~]# time docker exec trinity echo "In the container"
In the container

real	0m20.142s
user	0m0.021s
sys	0m0.009s
[root@node055 ~]# 
[root@node055 ~]# docker-enter trinity
[root@c055 /]# ip route show
default via 172.25.255.254 dev eth1 
172.25.0.0/16 dev eth1  proto kernel  scope link  src 172.25.0.55 
[root@c055 /]# ping -c1 172.25.255.254
PING 172.25.255.254 (172.25.255.254) 56(84) bytes of data.
64 bytes from 172.25.255.254: icmp_seq=1 ttl=62 time=0.697 ms

--- 172.25.255.254 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.697/0.697/0.697/0.000 ms
[root@c055 /]#                        

```
I have noticed this in other versions too. It is usually fixed by force-reloading the container.

**Comment by hansthen** [comment]
In my experience this happens when the login node is down or otherwise not accesible. In other words, this is a procedural error. Can you check to see if this is the case?

**Comment by themisa** [comment]
I have not been able to reproduce this. Now if a container does not belong to a virtual cluster, no image is running on it, so point is moot.

All other times when containers are assigned to virtual clusters, login nodes are up and docker-enter is very fast.

Closing now, and if i come across the issue again i can reopen.
