### ISSUE TITLE
Colander: services not found after failover

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#489]
**Version:** r6 6859708
**Environment:** unknown

After switching off the active controller:

[root@controller-2(unknown*) ~]# pcs status
Cluster name: ha_cluster
Last updated: Thu Oct 15 16:32:16 2015
Last change: Wed Oct 14 19:02:55 2015
Stack: corosync
Current DC: controller-2.cluster (2) - partition with quorum
Version: 1.1.12-a14efad
2 Nodes configured
15 Resources configured

Online: [ controller-2.cluster ]
OFFLINE: [ controller-1.cluster ]

Full list of resources:

 ip	(ocf::heartbeat:IPaddr2):	Started controller-2.cluster 
 ip_bmc	(ocf::heartbeat:IPaddr2):	Started controller-2.cluster 
 Master/Slave Set: ms_drbd [drbd]
     Masters: [ controller-2.cluster ]
     Stopped: [ controller-1.cluster ]
 Resource Group: grp_drbd
     fs_drbd	(ocf::heartbeat:Filesystem):	Started controller-2.cluster 
     symlinks_xCAT	(ocf::tummy:drbdlinks):	Started controller-2.cluster 
 Resource Group: grp_xCAT
     httpd	(systemd:httpd):	Stopped 
     dhcpd	(systemd:dhcpd):	Stopped 
     named	(systemd:named):	Stopped 
     mysqld	(systemd:mysqld):	Stopped 
     docker	(systemd:docker):	Stopped 
     docker-registry	(systemd:docker-registry):	Stopped 
     slapd	(systemd:slapd):	Stopped 
     xCAT	(lsb:xcatd):	Stopped 
     nfs-server	(systemd:nfs-server):	Stopped 

Failed actions:
    mysqld_start_0 on controller-2.cluster 'not running' (7): call=87, status=complete, exit-reason='none', last-rc-change='Thu Oct 15 15:33:02 2015', queued=2001ms, exec=3ms

PCSD Status:
  controller-1.cluster: Online
  controller-2.cluster: Online

Daemon Status:
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled

**Comment by hansthen** [comment]
I removed mysql as a resource. Colander now works with a sqllite database, which should also work.

**Comment by Marc69** [comment]
Solved in
**Version:** r6 aa08d39
**Environment:** amaster
