### ISSUE TITLE
Error adding users to virtual clusters

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#495]
**Version:** r6_fixes fd4dfcc
**Environment:** dmaster

When trying to add users to a virtual cluster, i encounter the following error. 
```
[root@login sbin]# obol -w system user add --password 123 --cn Jane --sn Smith  --groups power-users jane
Error adding jane to power-users: {'matched': 'ou=Group,dc=local', 'desc': 'No such object'}
```

**Comment by hansthen** [comment]
Unable to reproduce in r6
**Version:** r6 10cffc2
**Environment:** amaster
```
[root@login ~]# obol -w system user add --password 123 --givenName Janet --cn "Smith, Janet" --sn Smith  --groups power-users janet
```

**Comment by themisa** [comment]
**Version:** r6_fixes b8c25e1
**Environment:** tmaster
cannot be reproduced.

[root@login ~]# obol -w system user list
jane
