### ISSUE TITLE
Slurm has max locked memory limits very low

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#498]
>[root@login ~]# ps aux | grep slurm
root     12287  0.0  0.5 594440  9892 ?        Sl   14:42   0:00 /usr/sbin/slurmctld
root     12401  0.0  0.0 112644   960 pts/0    R+   14:53   0:00 grep --color=auto slurm

>[root@login ~]# cat /proc/12287/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            unlimited            unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7226                 7226                 processes 
Max open files            4096                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7226                 7226                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us     

[root@login ~]# cat /trinity/version 
* (detached from vMagdeburg)
269bf23

This will not allow jobs to run properly in a production cluster.

**If you are testing this:** mpirun is not the same as batch a job and make it run, the applications implied are not the same nor share the same limits. This needs to be unlimited for bigger jobs.

**Comment by hansthen** [comment]
As far as I know the memlock settings are only relevant on the compute nodes not the login nodes.
