### ISSUE TITLE
Controller installation: no connection to docker registry server

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#50]
During controller installation, there was no path to connect to the docker registry:

.Use case: The controller node hosts a docker registry with a trinity image

 > curl -X GET http://controller:5050/v1/search?q=trinity
  >>curl: (7) Failed connect to controller:5050; No route to host 

(eno2 interface down)

**Comment by themisa** [comment]
this is also the case on controller03 from newmaster.

**Comment by hansthen** [comment]
Unable to reproduce. May occur when no second network cable attached to the controller node. Reassign to Themis for further testing.

**Comment by themisa** [comment]
Connects to docker registry , version * r3
ee93d17


[root@controller ~]# curl -X GET http://controller:5050/v1/search?q=trinity
{"num_results": 0, "query": "trinity", "results": []}[root@controller ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
controller:5050/trinity   latest              f840dc9d80f5        23 minutes ago      762.4 MB
centos                    7                   dade6cb4530a        2 weeks ago         224 MB
centos                    centos7             dade6cb4530a        2 weeks ago         224 MB
centos                    latest              dade6cb4530a        2 weeks ago         224 MB
