### ISSUE TITLE
Reference to obsolete runimages

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#508]
**Version:** r6 cc03c73
**Environment:** dmaster

From xcat.log:
 ls: cannot access /install/runimages: No such file or directory

**Comment by themisa** [comment]
Fixed in:

**Version:** r6 1ecbf63
**Environment:** tmaster

[root@controller(unknown) ~]# grep -i "runimages" /var/log/xcat/xcat.log 
[root@controller(unknown) ~]#
