### ISSUE TITLE
Trinity compute node netboot image has mismatching kernel versions

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#509]
```
[root@node001 ~]# uname -a
Linux node001.cluster 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
[root@node001 ~]# rpm -qa | grep kernel
kernel-3.10.0-229.el7.x86_64
kernel-3.10.0-229.4.2.el7.x86_64
kernel-headers-3.10.0-229.4.2.el7.x86_64
```

This messes up installation of packages that require reading the kernel version of the running system for the reason of compiling kernel modules, for example: Beegfs, Cuda.

**Comment by hansthen** [comment]
From the xCAT source code:

```
# Default to the first kernel found in the install image if nothing specified explicitly.
# A more accurate guess than whatever the image build server happens to be running
# If specified, that takes precedence.
# if image has one, that is used
# if all else fails, resort to uname -r like this script did before
# Kernel name for s390x should be the same: vmlinuz-2.6.18-164.el5

my @KVERS= <$rootimg_dir/boot/vmlinuz-*>;
foreach (@KVERS) {
    s/vmlinuz-//;
}

@KVERS= <$rootimg_dir/lib/modules/*> unless (scalar(@KVERS));

$basekernelver = basename(shift @KVERS) if (scalar(@KVERS));
$basekernelver = `uname -r` unless ($basekernelver);

$kernelver = $basekernelver unless ($kernelver);

```

So if multiple kernels are possible, xCAT will just pick one (at random). 

If you want to fix a specifc kernel you can define an explicit kernelver (and kerneldir) in the linuximage table.

**Comment by hansthen** [comment]
Since this is an xCAT issue, we will not fix it.

**Comment by brunopereira81** [comment]
Hello Hans,

Either it seems that the message did not go through or maybe it was misunderstood.

I also don't see how the process of selecting a kernel by xCAT is "random". It actually seems very logical and easy to follow, but definitely not random.

Focusing on the issue and the fix:

**Kernel version was forced in to the Linux image:**
```
[root@controller(magdeburg*) cvsupport]# lsdef -t osimage centos7-x86_64-netboot-trinity -i kernelver
Object name: centos7-x86_64-netboot-trinity
    kernelver=3.10.0-229.el7.x86_64
```

**`yum-utils` was added to the package list:**
```
[root@controller(magdeburg*) cvsupport]# tail /install/custom/netboot/centos/trinity.centos7.pkglist
dmidecode
#Fix for 210
lvm2
#added for magdeburg
@ Development Tools
#kernel-headers
#kernel-devel
yum-utils
```

**Clean up of kernels was added to the post script:**
```
[root@controller(magdeburg*) cvsupport]# tail /install/custom/netboot/centos/trinity.centos7.postinstall 
if [ -d /trinity/site-local/compute/rootimg/ ]; then
    cp -LrT /trinity/site-local/compute/rootimg/ $installroot
fi
#-- Fix for #411 : create a stateless var
rm -rf $installroot/.var
mkdir -p $installroot/.var/lib/
mv -f $installroot/var/lib/rpm $installroot/.var/lib/rpm
package-cleanup -y --oldkernels --count=1
```

**`genimage` and `packimage` ran, node rebooted:**
```
[root@controller(magdeburg*) cvsupport]# ssh node001
Last login: Sun Nov 22 18:01:36 2015 from controller.cluster
[root@node001 ~]# uname -a
Linux node001 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Kernel versions mismatch is present between running kernel and installed `kernel-headers` as it was before:**
```
[root@node001 ~]# rpm -qa | grep kernel
kernel-3.10.0-229.el7.x86_64
kernel-headers-3.10.0-229.4.2.el7.x86_64
kernel-3.10.0-229.4.2.el7.x86_64
```

The issue seems to be coming from a ***updates*** folder added to trinity at `/install/post/otherpkgs/centos7/x86_64/xcat-otherpkgs0/updates/Packages/`, removing the rpm from there avoids the mismatch so this was definitely introduced at some stage by trinity.

Now we can finally focus on something else and continue working on the cluster since we can now install GPU and BeeGFS kernel modules.

Could you make sure to verify this again and re-open this ticket until the kernel version, kernel headers and possibly kernel devel packages match in a trinity node?

**Comment by themisa** [comment]
test proc: uname -a 
rpm -qa | grep kernel

should give latest kernel versions

**Comment by themisa** [comment]
not fixed in:
[root@node001 ~]# /trinity/report
**Version:** r6 962f467
**Environment:** tmaster


[root@tmaster(tmaster) trinity]# ./includes f3eb8348043
git merge-base --is-ancestor f3eb8348043 962f467
included


```
[root@node001 ~]# uname -a
Linux node001.cluster 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@node001 ~]# rpm -qa | grep kernel
kernel-3.10.0-229.el7.x86_64
kernel-headers-3.10.0-229.14.1.el7.x86_64
kernel-3.10.0-229.14.1.el7.x86_64
```

**Comment by hansthen** [comment]
The postinstall fix does not work, as xCAT determines kernel version before running the postinstall. The best way to fix this for now seems to be to patch xCAT itself.

```
my @KVERS= sort { -M $b <=> -M $a } <$rootimg_dir/boot/vmlinuz-*>;
foreach (@KVERS) {
    s/vmlinuz-//;
}
@KVERS = sort { -M $b <=> -M $a } <$rootimg_dir/lib/modules/*> unless (scalar(@KVERS));
```

**Comment by brunopereira81** [comment]
This is not necessary, removing you patch and using the xCAT way of installing the kernel works out of the box.

The problem is introduced when the initial kernel installed mismatches the updated packages you have set on your update repo, then a more recent kernel is installed, kernel headers and kernel devel, but genimage uses the first kernel detected (not a random one).

What needs to be done is either remove the updated kernel version from your repo, or if you do want to use them then use the -k option for genimage.

Since this process is automated during the controller installation the last part would need to be automated to create the initial trinity netboot image.

**Comment by brunopereira81** [comment]
This can easily fixed by adding your updates repo as a package repo for the installer. That way when `genimage` starts it will read the packages from the copied DVD and the updates and decide what is best using either the most recent kernel or the forced kernel in the `kernelver` option:

All you need to do is add the updates repo to the pkgdir option using the copied DVD as the first option, eg: from:

```
pkgdir=/install/centos7/x86_64
```

to

```
pkgdir=/install/centos7/x86_64,/install/post/otherpkgs/centos7/x86_64
```

You also avoid dependency hell once the image is up and you try running `genimage` again and your update repo broke packages that are not available in the DVD repo.

**Comment by themisa** [comment]
**Version:** r7 4dc20f7
**Environment:** dmaster


```
[root@node001 ~]# uname -a
Linux node001.cluster 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@node001 ~]# rpm -qa | grep kernel
kernel-3.10.0-327.el7.x86_64
kernel-headers-3.10.0-327.3.1.el7.x86_64
kernel-3.10.0-327.3.1.el7.x86_64
```

**Comment by themisa** [comment]
Not fixed in

**Version:** r7_login_image 14a418e
**Environment:** dmaster


```
[root@node001 ~]# uname -a
Linux node001.cluster 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@node001 ~]# rpm -qa | grep kernel
kernel-headers-3.10.0-327.3.1.el7.x86_64
kernel-3.10.0-327.el7.x86_64
kernel-3.10.0-327.3.1.el7.x86_64
```
