### ISSUE TITLE
Cuda 7.0 installation not possible because of kernel headers

### ISSUE THREAD

**Issue by ADiEmme** [clustervision/trinity#510]
Hi Guys,

the centos7-x86_64-netboot-trinity has wrong kernel packages:
[root@node002 ~]# rpm -qa | grep kern
kernel-3.10.0-229.el7.x86_64
kernel-3.10.0-229.4.2.el7.x86_64
kernel-devel-3.10.0-229.el7.x86_64
kernel-headers-3.10.0-229.4.2.el7.x86_64
kernel-devel-3.10.0-229.4.2.el7.x86_64

while it is using this kernel version:
[root@node002 ~]# uname -r
3.10.0-229.el7.x86_64

It is a problem, since when i try to install the kernel-headers-3.10.0-229.el7.x86_64, it will not install this package, because it recognize that there is a newer version installed.

So it is necessary to remove all unused kernel-* to make it work.

yum remove -y kernel-3.10.0-229.4.2.el7.x86_64
yum remove -y kernel-headers-3.10.0-229.4.2.el7.x86_64

After this, i can install required packages (kernel-headers for my kernel version also) and then i can compile everything without errors.

Thank you!
Andrea

**Comment by themisa** [comment]
Same as #509?

**Comment by ADiEmme** [comment]
similar, but those unused kernels, should be removed

**Comment by hansthen** [comment]
@ADiEmme 
Same as for #509. If xCAT will find multiple kernels inside the image, it will select a random kernel to boot. You can force a specific kernel by selecting it in the `linuximage` using the `kernelver` parameter. You will also need to make the `kerneldir` parameter point to `/install/post/otherpkgs/centos7/`.  

I have not yet found a way to reliably remove older kernel versions during xCAT image generation, so I suggest you use the workaround I described above.

**Comment by hansthen** [comment]
Since this seems to be an xCAT problem (and we have a workaround), I am putting this to wontfix.
