### ISSUE TITLE
Add package: vim

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#517]
vim needs to be available on compute nodes, docker image, controller, openstack

**Comment by hansthen** [comment]
```[root@controller(dmaster*) ~]# vi --version | head -1
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 10 2014 06:56:12)
[root@node001 ~]# vi --version | head -1
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 10 2014 06:56:12)
[root@c001 /]# vi --version | head -1                                                
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 10 2014 06:56:12)
```

**Comment by dchirikov** [comment]
```
[root@login ~]# vim
-bash: vim: command not found
[root@controller(magdeburg*) ~]# rpm -qf `which vi`
vim-minimal-7.4.160-1.el7.x86_64
[root@controller(magdeburg*) ~]# rpm -qf `which vim`
vim-enhanced-7.4.160-1.el7.x86_64
```

**Comment by hansthen** [comment]
Added vim-enhanced to login image and controller image. It is already in the trinity docker image. I will not add it to the compute image as it is 23M and it would increase the compute image with 5% in size.

**Comment by themisa** [comment]
**Version:** r7_login_image cdb1e43
**Environment:** dmaster

Vim has been installed on controller, but not on the login node. 

[root@controller(dmaster) ~]# which vim
/usr/bin/vim

[root@login ~]# which vim
/usr/bin/which: no vim in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by themisa** [comment]
Need to run cv_build_master again

**Comment by themisa** [comment]
Fixed in:
**Version:** r7_login_image 660733d
**Environment:** tmaster

[root@login ~]# which vim
/usr/bin/vim
