### ISSUE TITLE
ssh key autorization from the login nodes to cXXX

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#518]
not available for now, ssh ask for password if you are trying to connect from login node to cXXX

**Comment by themisa** [comment]
This happens when the user is root. Users created with obol can ssh

**Comment by dchirikov** [comment]
If we want to make it more user-friendly, decrease entry level of the Trinity, we should fix that. At least for diagnosis purposes if one suspects some issues on it, when you drain the node and cannot use slurm on it directly.
