### ISSUE TITLE
pdsh/xdsh on login nodes should be installed by default

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#523]

**Comment by hansthen** [comment]
Why? For parallel execution one can use slurm.

**Comment by dchirikov** [comment]
If we want to make it more user-friendly, decrease entry level of the Trinity, we should fix that. At least for diagnosis purposes if one suspects some issues on it, when you drain the node and cannot use slurm on it directly.

**Comment by hansthen** [comment]
@dchirikov pdsh and xdsh are xCAT tools and I'd prefer not to install xCAT on the login nodes. Would another parallel shell (e.g. pssh) be acceptable?

**Comment by dchirikov** [comment]
xdsh is included in xcat distribution, yes, but pdsh can be installed as a separate rpm.

**Comment by themisa** [comment]
Not fixed in:

**Version:** r7_login_image 660733d
**Environment:** tmaster



[root@login ~]# which whatsup
/usr/bin/whatsup

[root@login ~]# which pdsh
/usr/bin/which: no pdsh in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by hansthen** [comment]
Cedric is leading the review to collect all packages that could be added to the system.
