### ISSUE TITLE
Startup config of the trinity docker should be offloaded from the trinity-start script

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#525]
I do believe, that it is not the right place to specify which device should be accessible from docker: for example /dev/ipath or /dev/nvidia. Or which shares (/home, /scratch, etc) should be visible in docker environment.
Other words trinity user should not edit this script if he needs to add a new share or device.

**Comment by hansthen** [comment]
You are right. At present we do not have a good method for storing user supplied configuration. Instead of building an ad-hoc solution now, as part of Ironman we will implement `consul` as a centralized configuration database for this type of configuration.

**Comment by hansthen** [comment]
Closing for now, as this will be picked up on one of our regular releases.
