### ISSUE TITLE
/var/log/messages is growing too fast

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#528]
Every 5 second new set of messages from each docker container:
```
Nov 29 22:45:16 openstack container-replicator: Beginning replication run
Nov 29 22:45:16 openstack container-replicator: Replication run OVER
Nov 29 22:45:16 openstack container-replicator: Attempted to replicate 0 dbs in 0.00198 seconds (0.00000/s)
Nov 29 22:45:16 openstack container-replicator: Removed 0 dbs
Nov 29 22:45:16 openstack container-replicator: 0 successes, 0 failures
Nov 29 22:45:16 openstack container-replicator: no_change:0 ts_repl:0 diff:0 rsync:0 diff_capped:0 hashmatch:0 empty:0
Nov 29 22:45:17 gpu03 trinity: Host gpu03.vc-a not found: 3(NXDOMAIN)
Nov 29 22:45:17 gpu03 trinity: Host gpu03.vc-new not found: 3(NXDOMAIN)
Nov 29 22:45:17 gpu03 trinity: Could not determine cluster membership for this node. Sleeping now.
```
Could sleeping be performed without logging? User can use 'grep nodename" to find at root cause of the issue.

2 weeks bring 6.5 GB of /var/log/messages.

**Comment by hansthen** [comment]
Logrotate should automatically rotate these logfiles on a weekly basis. Can you check if this is the case? We can remove logging statements but they are quite useful for diagnostic purposes. If you need a quick workaround open controller:/usr/sbin/trinity-start and remove some echo statemements, pipe stdout, stderr into /dev/null and/or increase the sleep statements.

**Comment by hansthen** [comment]
Also, normally I would not expect an installation to take weeks before the nodes are allocated to a cluster. This should happen on the same day the nodes are booted.

**Comment by dchirikov** [comment]
It is hardly depends of the size of the cluster, and number of requested roles of the nodes.
logrotate could not help to avoid a nose in logs, when tiy need to filter out tousands of th lines to find the only string you need for the node where user suspect failure.

**Comment by hansthen** [comment]
Okay, I will remove the messages around the sleep statements

**Comment by themisa** [comment]
Fixed. Tested in:

**Version:** r6 aa08d39
**Environment:** tmaster


Removed a container from all clusters.

Output from /var/log/messages:

```
Dec  4 14:18:32 controller named[3836]: client 10.141.255.254#42076/key xcat_key: signer "xcat_key" approved
Dec  4 14:18:32 controller named[3836]: client 10.141.255.254#42076/key xcat_key: updating zone 'vc-a/IN': deleting an RR at c002.vc-a A
Dec  4 14:18:32 controller named[3836]: client 10.141.255.254#42076/key xcat_key: updating zone 'vc-a/IN': deleting rrset at 'c002.vc-a' TXT
Dec  4 14:18:32 controller named[3836]: client 10.141.255.254#42076/key xcat_key: updating zone 'vc-a/IN': deleting rrset at 'c002.vc-a' A
Dec  4 14:18:34 controller xCAT[7685]: xCAT: Allowing xdsh to node002 docker stop trinity; docker rm trinity for trinity from localhost
Dec  4 14:18:36 controller xCAT[7709]: xCAT: Allowing lsdef -t group for trinity from localhost
Dec  4 14:18:36 controller xCAT[7712]: xCAT: Allowing lsdef -t group -o hw-Generic,vc-a -i members for trinity from localhost
```

No more "sleeping statements"
