### ISSUE TITLE
netboot very slow

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#53]
netbooting  images is very slow (> 30 min).
with these parameters:

>tabdumb nodehm
#node,power,mgt,cons,termserver,termport,conserver,serialport,serialspeed,serialflow,getmac,cmdmapping,consoleondemand,comments,disable
"compute","ipmi","ipmi",,,,,"1","115200","hard",,,,,

**Comment by themisa** [comment]
These parameters make netboot fast as expected.

> tabdump nodehm
#node,power,mgt,cons,termserver,termport,conserver,serialport,serialspeed,serialflow,getmac,cmdmapping,consoleondemand,comments,disable
"compute","ipmi","ipmi",,,,,,,,,,,,

**Comment by hansthen** [comment]
Subsumed under #27. Closing here.
