### ISSUE TITLE
Munge and Slurm do not need a /home

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#530]
```
[root@login ~]# ll /home
total 0
drwxr-xr-x. 4 cvsupport cvsupport 84 Nov 29 17:56 cvsupport
drwx------. 3 munge     munge     70 Oct  8 14:38 munge
drwx------. 3 slurm     slurm     70 Oct  8 14:38 slurm
```

Services Munge and Slurm require a user to run them, but they do not require a /home in the cluster, this should be cleaned up.

**Comment by hansthen** [comment]
This is fairly difficult to do in an environment where we have pam_mkhomedir enabled. slurm and munge may not need a home directory, but it can also do little harm.
