### ISSUE TITLE
Trinity has no baremetal validation and configuration tools for benchmarks and validation of hardware.

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#532]
Trinity containers will only be as fast as the underlying hosts, for that engineers need to do several adjustments and require tools and a stable environment to test baremetal before moving to container performance.

Trinity lacks that environment.

As a basic requirement each cluster we install will need:

* shared storage;
* user management on the controller and trough the deployed nodes;
* slurm;
* Environment modules pointing to a shared location;
* A clean xcat image that we can use for testing nodes without many changes introduced to it.

Without this and for each installation we will not be able to produce decent results or do testing in our network or Infiniband fabric and setting this up is time consuming and troublesome for each time.

We need this setup and we should be doing this by hand every time.

**Comment by hansthen** [comment]
This was proposed in december 2014 as well, but we did not get funding for it. It would mean that we'd have to support two types of installations. However, you can do the same testing as on a proposed cluster inside a virtual cluster.

**Comment by brunopereira81** [comment]
> shown that running inside Trinity does not cause performance loss compared to running baremetal

This might be true, not doubting it, but that is not what I am saying.

One thing is to setup docker and run on a system that you know will get close 100% of your theoretical performance, the other thing is not to be getting that performance in baremetal and need to do adjustments to get there and then let it run on docker.

> However, if for the next installation you re-order the work (first do the trinity installation and then do performance validation), it will not be necessary to setup a parallel baremetal environment.

This is not really what happens: once your benchmarks do not show that you are getting the performance needed docker or you are getting errors while running your benchmarks you will want to remove docker form the picture, test, adjust, test until you get the performance right.

That last cycle will take a lot of time, if we count on having the task repeated for each cluster, to setup if you don't have the right tools in place.

> It would mean that we'd have to support a traditional cluster installation

This is not really hard to do and you don't need a lot of resources, my request is that its done once during the setup of a trinity cluster instead of over and over again for each cluster.

**Comment by themisa** [comment]
Discussion of this issue moved to a different forum .

**Comment by brunopereira81** [comment]
I don't understand why this is closed.
