### ISSUE TITLE
No docker registry on controller

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#540]
**Version:** r6 ae666be
**Environment:** amaster
[root@controller-1(amaster) ~]# docker images
REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
<none> <none> 5738d11a3a9f 31 minutes ago 226.7 MB
docker.io/centos latest ce20c473cd8a 8 weeks ago 172.3 MB

From /var/log/xcat/xcat.log:

cp: cannot stat ‘/var/lib/docker-registry’: No such file or directory

find: ‘/var/lib/docker-registry’: No such file or directory

Error renaming "/var/lib/docker-registry.drbdlinks" to "/var/lib/docker-registry": [Errno 2] No such file or directory

**Comment by themisa** [comment]
fixed in: r6 18d4ba5
amaster
