### ISSUE TITLE
cv_install_moncon: not restartable

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#546]
The cv_install_moncon script can only be ran once. This is especially annoying if we have to add new nodes to the system later.

**Comment by hansthen** [comment]
Ideally we'd not only like to run this from the controller but have the nodes identify themselves to the moncon api somehow. Maybe this can be done as part of genesis?

**Comment by hansthen** [comment]
I think I fixed this in R7.

**Comment by themisa** [comment]
Fixed in:
**Version:** r7_login_image 660733d
**Environment:** tmaste

```
root@controller(tmaster) xcatpost]# ./cv_install_moncon 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[u'node001', u'node002']
node001,node002
ALL HOSTS: Added host node001
Generating configuration for core (type nagios)...OK
Validating Nagios configuration...OK
Precompiling host checks...OK
Restarting monitoring core...OK
```

This is second time this was run. Did not duplicate entries. Restartable
