### ISSUE TITLE
Openstack installation: Puppet run fails

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#549]
**Version:** r6 18d4ba5
**Environment:** amaster

From xcat.log:

ESC[0;31mERROR : Error appeared during Puppet run: 10.141.0.3_prescript.pp
Error: Could not find data item DEFAULT_EXEC_TIMEOUT in any Hiera data file and no default supplied at /var/tmp/packstack/346a2a2d11f24b9c94eec61385cc8775/manifests/10.141.0.3_prescript.pp:1 on node openstack.clusterESC[0m
You will find full trace in log /var/tmp/packstack/20151222-095323-G6Ennr/manifests/10.141.0.3_prescript.pp.logESC[0m
Please check log file /var/tmp/packstack/20151222-095323-G6Ennr/openstack-setup.log for more information
Additional information:
 * File /root/keystonerc_admin has been created on OpenStack client host 10.141.0.3. To use the command line tools you need to source the file.
 * To access the OpenStack Dashboard browse to http://10.141.0.3/dashboard .
Please, find your login credentials stored in the keystonerc_admin in your home directory.
 * To use Nagios, browse to http://10.141.0.3/nagios username: nagiosadmin, password: 7515fcbccc5c49bf
sed: can't read /etc/nova/nova.conf: No such file or directory
sed: can't read /etc/openstack-dashboard/local_settings: No such file or directory
./cv_install_openstack: line 35: openstack-config: command not found
Failed to issue method call: Unit openstack-nova-compute.service failed to load: No such file or directory.
Failed to issue method call: Unit openstack-nova-api.service failed to load: No such file or directory.
./cv_install_openstack: line 38: /root/keystonerc_admin: No such file or directory
./cv_install_openstack: line 39: nova: command not found
./cv_install_openstack: line 42: killall: command not found

(...)

./cv_install_openstack: line 132: glance: command not found
./cv_install_openstack: line 156: keystone: command not found
./cv_install_openstack: line 157: keystone: command not found
./cv_install_openstack: line 158: nova: command not found

etc.

**Comment by hansthen** [comment]
Looks like an environment problem. I forgot to run copycds with centos 7.2 on the amaster.

**Comment by Marc69** [comment]
Has not been signalled since.
