### ISSUE TITLE
clusterbats: test 1.1.8 is incorrect for colander setup

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#550]
**Version:** r6_fixes b8c25e1
**Environment:** amaster

In a colander scenario the hostnames will be controller-1.cluster and controller-2.cluster.
```
not ok 6 1.1.8 Hostname is set correctly
# (in test file t1.1.bats, line 32)
#   `[ $s1 = $s2 ]' failed
```

```
@test "1.1.8 Hostname is set correctly" {
   s1=$HOSTNAME
   s2='controller.cluster'
   [ $s1 = $s2 ] 
}
```

**Comment by Marc69** [comment]
Solved in https://github.com/clustervision/clusterbats/commit/fbb6eb12653bb2934a9f76f81159767412f38813#diff-cd38cc31efed232e233cc559196aa689
