### ISSUE TITLE
omd not found

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#559]
**Version:** r7 f5985fb
**Environment:** amaster

[root@controller-1(amaster) /]# systemctl -l status omd
● omd.service - Dockerized Omd
   Loaded: loaded (/usr/lib/systemd/system/omd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since ma 2015-12-28 16:39:18 CET; 1h 14min ago
  Process: 27075 ExecStop=/usr/bin/docker stop -t 2 glance (code=exited, status=0/SUCCESS)
  Process: 27070 ExecStart=/usr/bin/docker start -a glance (code=exited, status=1/FAILURE)
 Main PID: 27070 (code=exited, status=1/FAILURE)

dec 28 16:39:17 controller-1.cluster systemd[1]: Unit omd.service entered failed state.
dec 28 16:39:17 controller-1.cluster systemd[1]: omd.service failed.
dec 28 16:39:18 controller-1.cluster systemd[1]: omd.service holdoff time over, scheduling restart.
dec 28 16:39:18 controller-1.cluster systemd[1]: start request repeated too quickly for omd.service
dec 28 16:39:18 controller-1.cluster systemd[1]: Failed to start Dockerized Omd.
dec 28 16:39:18 controller-1.cluster systemd[1]: Unit omd.service entered failed state.
dec 28 16:39:18 controller-1.cluster systemd[1]: omd.service failed.

From xcat.log:

Mon Dec 28 15:16:39 CET 2015 Running postscript: cv_install_rsa
Using default tag: latest
Trying to pull repository 192.168.1.254:5050/omd ... not found
Error: image omd:latest not found
Error response from daemon: could not find image: no such id: 192.168.1.254:5050/omd
mkdir: cannot create directory ‘/cluster/omd’: File exists
Unable to find image 'controller:5050/omd:latest' locally
Trying to pull repository controller:5050/omd ... not found
Error: image omd:latest not found

**Comment by hansthen** [comment]
This is an environment issue. Part of the R7 release is to move the build of the containers to the master (instead of building them when creating the controller). The omd container image was not built on master yet. To build all container images required to install R7 run `bash -x /install/postscripts/cv_build_master_registry` on the master.

**Comment by Marc69** [comment]
[root@controller(amaster) ~]# systemctl -l status omd
● omd.service - Dockerized Omd
   Loaded: loaded (/usr/lib/systemd/system/omd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

**Comment by Marc69** [comment]
But still problematic in 4dc20f7:

[root@controller(amaster) postscripts]# systemctl status omd
● omd.service - Dockerized Omd
   Loaded: loaded (/usr/lib/systemd/system/omd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since di 2016-01-05 16:37:56 CET; 9min ago
  Process: 18367 ExecStop=/usr/bin/docker stop -t 2 omd (code=exited, status=1/FAILURE)
  Process: 18361 ExecStart=/usr/bin/docker start -a omd (code=exited, status=1/FAILURE)
 Main PID: 18361 (code=exited, status=1/FAILURE)

jan 05 16:37:55 controller.cluster systemd[1]: Unit omd.service entered failed state.
jan 05 16:37:55 controller.cluster systemd[1]: omd.service failed.
jan 05 16:37:56 controller.cluster systemd[1]: omd.service holdoff time over, scheduling restart.
jan 05 16:37:56 controller.cluster systemd[1]: start request repeated too quickly for omd.service
jan 05 16:37:56 controller.cluster systemd[1]: Failed to start Dockerized Omd.
jan 05 16:37:56 controller.cluster systemd[1]: Unit omd.service entered failed state.
jan 05 16:37:56 controller.cluster systemd[1]: omd.service failed.

**Comment by Marc69** [comment]
Solved in * r7_fixes
1cec307
