### ISSUE TITLE
Controller and compute nodes have different time zones

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#566]
**Version:** r7 4dc20f7
**Environment:** amaster

[root@controller(amaster) ~]# date +%Z
CET

[root@node001 ~]# date +%Z
UTC

**Comment by brunopereira81** [comment]
You need to use the `setupntp` script in the post install or post boot for the time to be synchronized from node to controller, without it ntp does not update the time in the nodes themselves.

**Comment by hansthen** [comment]
The timezone of a cluster is determined by the timezone variable in the xCAT site table. Since the master deploys the controller node, we need to set the value in the master correctly. I have corrected this for the amaster server.

**Comment by Marc69** [comment]
Site table's been set to UTC on amaster, but master and controller still have CET:

[root@node001 ~]# date +%Z
UTC
[root@controller(amaster) ~]# date +%Z
CET
[root@master ~]# date +%Z
CET

**Comment by hansthen** [comment]
@Marc69 Did you redeploy controller after I set the timezone to UTC?

**Comment by Marc69** [comment]
Solved in:
**Version:** r7 b14c0de
**Environment:** tmaster
```[root@controller(tmaster*) ~]# date
Mon Feb 22 12:09:18 UTC 2016
[root@controller(tmaster*) ~]# ssh node001 date
Warning: Permanently added 'node001,10.141.0.1' (ECDSA) to the list of known hosts.
Mon Feb 22 12:09:24 UTC 2016
```
