### ISSUE TITLE
login nodes get into error state after reboot

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#574]
**Version:** r7 85ff0e9
**Environment:** dmaster

After the fix of #556, login nodes should be retained after controller reboot, but they are in error state and must be manually restarted by nova stop and nova start login-a.

```
[root@controller ~(keystone_admin)]# nova list --all-tenants
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| ID                                   | Name      | Status | Task State | Power State | Networks                                 |
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| d5e93315-fc95-46ee-96f9-30412789acb4 | login-a   | ERROR  | -          | Shutdown    | novanetwork=192.168.32.2, 172.16.255.254 |
| 80486544-eb19-4600-aedd-33e80aab29d7 | login-new | ERROR  | -          | Shutdown    | novanetwork=192.168.32.3, 172.17.255.254 |
```

**Comment by themisa** [comment]
No longer in error state after reboot. There are other issues related to login nodes tracked elsewhere.
Not sure if this is fixed in r7 so keeping open. 

**Version:** r7_login_image 1b0aad3
**Environment:** tmaster

```
[root@controller ~(keystone_admin)]# nova list --all-tenants
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| ID                                   | Name      | Status | Task State | Power State | Networks                                 |
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| 600c5f53-281e-4cd6-81f7-e4f8f5775146 | login-a   | ACTIVE | -          | Running     | novanetwork=192.168.32.2, 172.16.255.254 |
| 3aeb0558-0b66-4265-81dd-756eaf9091e7 | login-new | ACTIVE | -          | Running     | novanetwork=192.168.32.3, 172.17.255.254 |
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
```

**Comment by themisa** [comment]
Fixed. Tested in:
[root@controller ~(keystone_a)]# /trinity/report
**Version:** r7 b55e0e1
**Environment:** tmaster

After a controller reboot:
[root@controller ~(keystone_a)]# nova list
+--------------------------------------+---------+--------+------------+-------------+------------------------------------------+
| ID                                   | Name    | Status | Task State | Power State | Networks                                 |
+--------------------------------------+---------+--------+------------+-------------+------------------------------------------+
| 821618a6-8d3a-405b-b1d6-7927ef63da99 | login-a | ACTIVE | -          | Running     | novanetwork=192.168.32.2, 172.16.255.254 |
+--------------------------------------+---------+--------+------------+-------------+------------------------------------------+
