### ISSUE TITLE
Need an openstack image definition on controller

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#58]
**Software:** Trinity
**Component:** controller installation
**Hardware:** controller03
**Use case:** 1.2 Install cluster
**Bug description**: On the controller, there is no openstack image (or cv_install_openstack postcript). 
We could like to be able to create openstack nodes from the controller node. Now it's only possible (without copying things around) from the master.

**Steps to reproduce bug:**
1) ssh to master
2) ssh to controller (03)
3) tabdump osimage

**Expected output:**
inclusion of following line:
"centos7.0-x86_64-install-openstack",,"openstack","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,"cv_install_slapd,cv_install_openstack",,,,,

**Actual output:**
#imagename,groups,profile,imagetype,description,provmethod,rootfstype,osdistroname,osupdatename,cfmdir,osname,osvers,osarch,synclists,postscripts,postbootscripts,serverrole,isdeletable,kitcomponents,comments,disable
"centos7.0-x86_64-install-compute",,"compute","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-xen",,"xen","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-storage",,"storage","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-all",,"all","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-iscsi",,"iscsi","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-compute",,"compute","linux",,"netboot",,,,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-xen",,"xen","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-kvm",,"kvm","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-trinity",,"trinity","linux",,"netboot",,,,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-compute",,"compute","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-xen",,"xen","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-kvm",,"kvm","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-trinity",,"trinity","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,

**Comment by themisa** [comment]
We can create now an openstack node from master. That option should still be there. Maybe we can also think of having a combined openstack+controller node image created from master (run the cv_install_openstack script after controller installation), and another option to create an openstack node from the controller.

**Comment by hansthen** [comment]
I have copied all the cv_install_* postscripts from master into controller. They are symlinked in the repo, so editing the scripts on master will automatically adapt the same scripts on controller.

**Comment by themisa** [comment]
@hansthen 
not sure yet if this is fixed: (no openstack image or cv_install scripts on controller)
on controller:
[root@controller postscripts]# tabdump osimage
#imagename,groups,profile,imagetype,description,provmethod,rootfstype,osdistroname,osupdatename,cfmdir,osname,osvers,osarch,synclists,postscripts,postbootscripts,serverrole,isdeletable,kitcomponents,comments,disable
"centos7.0-x86_64-install-compute",,"compute","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-xen",,"xen","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-storage",,"storage","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-all",,"all","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-iscsi",,"iscsi","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-compute",,"compute","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-xen",,"xen","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-kvm",,"kvm","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-compute",,"compute","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-xen",,"xen","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-kvm",,"kvm","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,

**Comment by hansthen** [comment]
I moved files from controller/* into controller/rootimg/ but did not update cv_install_xcat. Should be okay again.

**Comment by hansthen** [comment]
After installing on controller02.
[root@controller ~]# ls /install/custom/
install  netboot

**Comment by themisa** [comment]
Fixed in: cb242d7

[root@controller install]# tabdump osimage
#imagename,groups,profile,imagetype,description,provmethod,rootfstype,osdistroname,osupdatename,cfmdir,osname,osvers,osarch,synclists,postscripts,postbootscripts,serverrole,isdeletable,kitcomponents,comments,disable
"centos7.0-x86_64-install-compute",,"compute","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-master",,"master","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-openstack",,"openstack","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-all",,"all","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-controller",,"controller","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-xen",,"xen","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-storage",,"storage","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-install-iscsi",,"iscsi","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-compute",,"compute","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-xen",,"xen","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-kvm",,"kvm","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-netboot-trinity",,"trinity","linux",,"netboot",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-compute",,"compute","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-xen",,"xen","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-kvm",,"kvm","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,
"centos7.0-x86_64-statelite-trinity",,"trinity","linux",,"statelite",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,,,,,,

**Comment by themisa** [comment]
Regression in v * r3
ee93d17

tamdump osimage, linuximage does not include openstack image

**Comment by themisa** [comment]
fixed in 9fe3b3b
