### ISSUE TITLE
PackStack answer file: Network Interface names are hardcoded

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#59]
**Software:**
Branch r3
**Component:**
cv_install_openstack
**Hardware:**
Dell PowerEdge
**Bug description:**
The OpenStack controller image fails to install OpenStack because the packstack answer file has
the network interface names hardcoded as eno*. 
**Steps to reproduce:**
packstack --answer-file=packstack-answers.txt
**Expected output:**
functional openstack controller
**Actual output:**
ERROR : Failed to run remote script, stdout: Device eno2 does not exist

stderr: Warning: Permanently added '192.168.1.2' (ECDSA) to the list of known hosts.
+ trap t ERR
+ ip addr show dev eno2
Device "eno2" does not exist.
+ echo Device eno2 does not exist
+ exit 1
++ t
++ exit 1

**Comment by hansthen** [comment]
Closed in: 3cecd76
