### ISSUE TITLE
login node hostname changes after controller reboot

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#591]
**Version:** r7_login_image 1b0aad3
**Environment:** tmaster

After a controller reboot, the login node changes hostname

[root@login-a ~]# hostname
login-a.novalocal

**Comment by themisa** [comment]
earlier fix in : #334

**Comment by hansthen** [comment]
**Version:** r7_login_image 0129518
**Environment:** dmaster

```
[root@controller(dmaster) ~]# shutdown -r now
<SNIP>
[root@controller(dmaster) ~]# sshpass -p system ssh login.vc-a hostname 
login
```

**Comment by Marc69** [comment]
**Version:** r7_fixes 1cec307
**Environment:** amaster

Fixed.
