### ISSUE TITLE
bmcsetup fails (cv_install_master)

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#594]
* r7_login_image
3df1df6

when installing master bmcsetup fails (no logs, but screen output showed a patch failure relating to bmcsetup)

Cannot rpower controller

**Comment by themisa** [comment]
[root@master bin]# more bmcsetup.rej 
--- /dev/null
+++ /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/bin/bmcsetup 2015-12-23 15:03:42.560091048 +0100
@@ -99,6 +99,13 @@
 elif [ "$IPMIMFG" == "47488" ]; then
         LOCKEDUSERS=1
 fi
+#
``
+# hans.then@clustervision.com
+# 
+# We always assume LOCKEDUSERS=1 as that will work on both types of HW.
+# 
+LOCKEDUSERS=1
+ 
 echo -n "Auto detecting LAN channel..."
 
 while [ -z "$LANCHAN" ]; do 
```

**Comment by hansthen** [comment]
Error was related to something else (missing IP adres on the bmc range)
