### ISSUE TITLE
controller requires reboot after being disconnected from master

### ISSUE THREAD

**Issue by rispoli** [clustervision/trinity#596]
It seems that when you deploy a controller from a master node and then disconnect it from the master then some mount points keep hanging there and xCAT might not be entirely happy with itself to the point that compute nodes will not be booting.
It's therefore safer to reboot the controller after its deployment.

**Comment by hansthen** [comment]
Indeed. We expect controllers to be attached to the master, until they are ready for shipping, at which point they will be rebooted. Please be aware that we disable network manager, so some automatic network discovery functionality is disabled.
