### ISSUE TITLE
hostname confusing when installing openstack image

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#60]
**Software:** Trinity
**Component:** Openstack image
**Hardware:** Controller04
**Test case:** 1.2.7 We can install openstack nodes (from the controller)
**Bug description:** When setting an openstack image (still from master), the hostname is reporter as controller.cluster, instead of openstack. [surprisingly, on controller02, provisioned with the same image, hostname is openstack]
**Steps to reproduce:**
1) ssh to newmaster
2)  > lsdef -i provmethod controller04
RESULT:
Object name: controller04
    provmethod=centos7.0-x86_64-install-openstack
3) ssh to controller04
4) > hostname
RESULT: controller.cluster

**Expected output:**
openstack.cluster
**Actual output:**
controller.cluster

**Comment by hansthen** [comment]
Is fixed (at least from version aef79d1 onwards).
