### ISSUE TITLE
Nova node fails during genimage

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#605]
It complains about missing openstack packages. 

can be fixed using:

```
repotrack -p /install/post/otherpkgs/centos7/x86_64/ $(grep -hv "^#" /install/custom/netboot/centos/*.otherpkgs)
reposync -n -r updates -p /install/post/otherpkgs/centos7/x86_64/
```

at an appropriate moment in the cv_install_controller.

**Comment by hansthen** [comment]
Should be fixed in r7_fixes.

**Comment by Marc69** [comment]
**Version:** r7 b14c0de
**Environment:** tmaster

Genimage works all right now.
