### ISSUE TITLE
openstack image doesn't come with cv_install_dash+api

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#61]
**Software:** Trinity
**Component:** openstack image
**Hardware:** Controller04
**Test case:** 1.2.8 The openstack nodes can run the trinity dashboard + interface with the trinity API
**Bug description:** The openstack image doesn't have cv_install_dash+api (no /install directory, 
no relevant script in /xcatpost, and not a postscript option)
**Steps to reproduce:**
1) ssh controller04
2) cd xcatpost
3) cat cv_install_api+dash
**Expected output:**
script exists
**Actual output:**
script does not exist

**Comment by hansthen** [comment]
Assigned to Abhi.

**Comment by abhimukh** [comment]
The scripts from the /scripts directory in the repo need to be copied under the  /install tree, and the postscript/postbootscript attribute of the imagedefs need to be updated accordingly. This, should be resolved during master installation or master update.

**Comment by hansthen** [comment]
@abhimukh 
I setup the master_update script.sh so there is a one to one location from files in the github repo and the file structure on the master node. 

We do a copy of ~/trinity/master/rootimg to master:/. Any files on master that are in /trinity/controller/rootimg will be copied to controller:/. So if a file needs to be copied to controller put it in ~/trinity/master/rootimg/trinity/controller/rootimg. Use symlinks if you have files/directories that need to be in multiple locations.

**Comment by hansthen** [comment]
Probably we also need to update the osimage table to run these installation scripts as postscripts on the appropriate nodes.

**Comment by themisa** [comment]
I am closing this ticket since the scripts are now available in /xcatpost.
Some other issues on integration have been documented in #91

**Comment by themisa** [comment]
There was a regression on this ticket somewhere, version 
* r3
4647552

no relevant scripts in /xcatpost.

**Comment by abhimukh** [comment]
@hansthen the cv_install_api and cv_install_dash are available under /xcatpost in the xCAT controller but not on the OpenStack node.

**Comment by hansthen** [comment]
Move the files to trinity/controller/rootimg/install/postscripts

**Comment by themisa** [comment]
fixed in * r3
ae94b4a
