### ISSUE TITLE
no git installed on controller nodes 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#62]
**Software:**Trinity
**Component:** controller
**Hardware:** controller03
**Test case:** general
**Bug description:** Git is not installed during controller installation
**Steps to reproduce:**
1) ssh to controller
2) which git
**Expected output:**
/usr/bin/git
**Actual output:**
/usr/bin/which: no git in (/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by hansthen** [comment]
We will not install git on controllers (automatically). Developers need to work on the master(s).

**Comment by themisa** [comment]
@hansthen 
I am reopening this bug (previously marked invalid) as I noticed that cv_install_master (from controller) in r4_fixes requires a "git clone".

Can we have git installed on the controller by default, or make it a procedure to download git before cv_install_master?

**Comment by hansthen** [comment]
cv_install_master runs on the master, not on the controller.
