### ISSUE TITLE
cv_install_api+dash: openstack controller may not be the same as xCAT controller

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#63]
**Software:** Trinity
**Component:** cv_install_api+dash
**Hardware:** controller04
**Test case:** 1.2.8 The openstack nodes can run the trinity dashboard + interface with the trinity API
**Bug description:** When installing the trinity dashboard and api server on an openstack node, if the openstack node is not the same as the xCAT controller, we need to manually edit /etc/trinity/trinity_api.conf to point to the xCAT controller. We might also need to take into account that the api server is different from the node running openstack/trinity dashboard
**Steps to reproduce:**

**Expected output:**
**Actual output:**

**Comment by abhimukh** [comment]
I created separate scripts for installing the API server, dashboard additions and the xCATWS. If these services are to be hosted on different nodes then these scripts can be run on appropriate nodes. The config files will have to be edited to resolve dependencies between different services.

**Comment by themisa** [comment]
Found the relevant scripts in /xcatpost (cv_install_api, cv_install_dash, cv_install_api+dash)
However i am not sure that the corresponding config files are properly copied over so that they can be edited. (this is for an openstack node, which no longer has xCAT installed).
[no /trinity or /etc/trinity ]

**Comment by themisa** [comment]
split scripts exist. ok
