### ISSUE TITLE
Hostname mismatch

### ISSUE THREAD

**Issue by ADiEmme** [clustervision/trinity#631]
Hi,
not a critical issue, but ugly to see.

[root@controller ~] tabdump hosts
"login-a","172.16.255.254","login.vc-a",,,
"login-b","172.17.255.254","login.vc-b",,,

[root@controller ~]# ssh login-a
[root@login ~]# hostname -f
login-a.vc-a

[root@controller ~]# ssh login-b
[root@login ~]# hostname -f
login-b.vc-b

**Comment by hansthen** [comment]
What are the expected results? This looks fine to me.
