### ISSUE TITLE
xCAT master: controllers with same mac address

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#64]
**Software:** Trinity
**Component:**xCAT master
**Hardware:** SM xCAT master, Cisco switch1, Dell controller01, SM controller02
**Test case:** 1.1 Install controller
**Bug description:**
SM controller was not finishing discovery. tabdump mac showed both controllers on same mac address.
**Steps to reproduce:**
tabdump mac
**Expected output:**
**Actual output:**
[root@master ~]# tabdump mac
#node,interface,mac,comments,disable
"controller02",,"0c:c4:7a:02:03:4c",,
"vm01",,"08:00:27:aa:bf:09!*NOIP*|08:00:27:bd:af:58",,
"vm02",,"08:00:27:27:8b:4b|08:00:27:ba:6f:8e!*NOIP*",,
"vm03",,"08:00:27:5f:63:7e|08:00:27:d0:21:7a!*NOIP*",,
"vm04",,"08:00:27:8a:65:03|08:00:27:69:4d:c6!*NOIP*",,
"vm21",,"08:00:27:03:84:81",,
"controller03",,"00:25:90:f0:67:ba",,
"controller01",,"0c:c4:7a:02:03:4c",,
"controller01,controller02",,"0c:c4:7a:02:03:4c",,
[11:35:39 AM] Hans Then: The same mac is assigned to both controller01 and controller02

**Comment by hansthen** [comment]
Theory: arp cache flustered. Cleared arp cache for both.

**Comment by hansthen** [comment]
Seemed to be a conflict caused by an ARP cache, because we moved a node from one switch position to another. Solved it by cleaning the xCAT tables, dhcp.leases and arp caches. Assigned to Themis for further testing.

**Comment by themisa** [comment]
Have not encountered this error again after following the above steps, and it did not reappear after moving the nodes and switches and re-cabling. Can reopen if it reappears, but above procedure seems to work. Sometimes, even after clearing all tables, it still reported the same mac address for both controllers, but after deleting the offending line from the mac xCAT table, everything worked fine.
