### ISSUE TITLE
Dell poweredge openstack installation: kickstart file problem 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#65]
**Software:** Trinity r3 433cd3f
**Component:** openstack-install
**Hardware:** Dell poweredge (1, controller01)
**Test case:** install openstack
**Bug description:**
When trying to install openstack, the system freezes
**Steps to reproduce:**
nodeset controller01 osimage=centos7.0-x86_64-install-openstack
**Expected output:**
**Actual output:**
Running pre-installation scripts
The following problem occurred on line 1 of the kickstart file:
--ondisk option requires an argument

**Comment by themisa** [comment]
same with controller installation. Seems to be hardware related.

**Comment by hansthen** [comment]
This was solved by Daniel Mantione by changing a BIOS setting.
