### ISSUE TITLE
R8 / genimage fails to copy /etc/yum.repos.d content

### ISSUE THREAD

**Issue by quentinleburel** [clustervision/trinity#676]
Initial problem was "base repos are not enabled on compute node"
```
[root@controller-1(Engineering) centos]# grep enabled /install/netboot/centos7/x86_64/trinity/rootimg/etc/yum.repos.d/CentOS-Base.repo
enabled=0
enabled=0
enabled=0
enabled=0
```
(this command returns 1110 in R7)

To reproduce, manually run
`genimage "centos7-x86_64-netboot-trinity"`

One of the error messages in genimage output will be:
`cp: cannot overwrite directory ‘/install/netboot/centos7/x86_64/trinity/rootimg/etc/yum.repos.d’ with non-directory
`
This is caused by the trinity postinstall script `/install/custom/netboot/centos/trinity.centos7.postinstall` :
`cp -rT /etc/yum.repos.d $installroot/etc/yum.repos.d`
should be:
`cp -rT /etc/yum.repos.d/ $installroot/etc/yum.repos.d`

This is because /etc/yum.repos.d is now a symlink to /drbd. Without the last / the copy will fail, and then the repos are not properly setup on compute nodes

**Comment by Marc69** [comment]
Works fine here:
**Version:** r8_fixes r8.2-63-g46084cf
**Environment:** amaster
