### ISSUE TITLE
Master installer: controllers have no ipmi password set

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#69]
Software: Trinity r3 69bcecc
Component: Master installer
Bug description:

The controller nodes have no ipmi password set. Error is a faulty template database.

    [root@master ~]# tabdump ipmi
    #node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable
    "controllers","/\z/-bmc/","0",,,,,,

**Comment by hansthen** [comment]
Fixed in 2d91b2a

**Comment by themisa** [comment]
@hansthen 

in the latest version: 
* r3
26af0dd

[root@master ~]# tabdump ipmi
#node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable
"controllers","/\z/-bmc/","0",,,,,,

is there a special way to update tables? (would update_master do it?)

**Comment by hansthen** [comment]
update_master --include-tables

**Comment by themisa** [comment]
Tested on newmaster after update_master --with-tables

[root@newmaster ~]# tabdump ipmi
#node,bmc,bmcport,taggedvlan,bmcid,username,password,comments,disable
"controllers","/\z/-bmc/","0",,,"root","system",,
