### ISSUE TITLE
Master installer: adding rpms to the /install repository makes the stateful install fail

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#7]
Kickstart cannot deal with a repository which has extra rpms installed. It fails with a NoSuchGroup (core) message.

**Comment by hansthen** [comment]
Workarounds:
- have the postinstall point to a different repo
- specify a different repo for a stateful install
- use otherpackages in the image definition

**Comment by abhimukh** [comment]
couple of other options:

* copy the new rpms to dir under /install, and then append the pkgdir
attribute of the osimage table
chdef -t osimage rhels6.2-x86_64-install-compute -p
pkgdir=/install/rhels6.3/x86_64

* use sysclone to create a golden client
http://sourceforge.net/p/xcat/wiki/Using_Clone_to_Deploy_Server/

**Comment by hansthen** [comment]
Actual scope is M2, but we have a workaround now. So I propose to solve this in M3.

**Comment by hansthen** [comment]
I have removed the extra packages from the repositories. However, we still need to add the extra packages (I believe docker and slurm) package dir.

**Comment by hansthen** [comment]
This is done and has been tested by me. Docker images now get generated. See #35 for the solution. I am not yet closing, as we still need to rebase the repos from the kickstart based installers to point to the xCAT master/controller node.

**Comment by hansthen** [comment]
Fixed in master_installer branch.

**Comment by themisa** [comment]
@hansthen, this doesn't have a commit number, was this merged with r3?

**Comment by hansthen** [comment]
I will merge master_installer with r4.

**Comment by themisa** [comment]
@hansthen , did you already merge with r4?

**Comment by themisa** [comment]
@hansthen could you check state and define test procedure"?

**Comment by hansthen** [comment]
openstack.tmpl still contained a repo definition. Now fixed in master_installer. To test, do a manual inspection of the *.tmpl files inside /install/custom/install to see if they use %include /tmp/repos to define the repositories.

**Comment by themisa** [comment]
Openstack now only uses local repos.
However, controller template file includes a yum install:
```
controller.tmpl:yum -y install createrepo net-snmp-utils bind-utils wget ntp
```
in *master_installer 1030300

**Comment by hansthen** [comment]
That's okay. Yum point to the local repo. We could move these to the package file, but that is an enhancement.
