### ISSUE TITLE
controller installation: stuck at wget

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#70]
**Software:** Trinity r3 69bcecc
**Component:** install controller
**Hardware:** Controller02, supermicro
**Bug description:** When we nodeset controller02 with a controller installation, the postinstall phase
gets stuck. By looking at the autogenerated kickstart file wget master://install/autoinst/controller02,  it looks like it is getting stuck at a wget (redirects)

**Comment by hansthen** [comment]
Assigned to Themis for re-testing.

**Comment by themisa** [comment]
Specifically, still stuck (v fc3432c ) on wget of cv_install_xcatws

Looking at master : /var/log/httpd/access_log:
.168.1.2 - - [23/Feb/2015:14:00:03 +0100] "GET /install/postscripts/cv_install_rsa HTTP/1.1" 200 646 "http://192.168.1.254/install/postscripts/" "Wget/1.14 (linux-gnu)"
192.168.1.2 - - [23/Feb/2015:14:00:03 +0100] "GET /install/postscripts/cv_install_slapd HTTP/1.1" 200 3540 "http://192.168.1.254/install/postscripts/" "Wget/1.14 (linux-gnu)"
192.168.1.2 - - [23/Feb/2015:14:00:03 +0100] "GET /install/postscripts/cv_install_xcat HTTP/1.1" 200 4329 "http://192.168.1.254/install/postscripts/" "Wget/1.14 (linux-gnu)"
192.168.1.2 - - [23/Feb/2015:14:00:03 +0100] "GET /install/postscripts/cv_install_xcat_ws HTTP/1.1" 200 494 "http://192.168.1.254/install/postscripts/" "Wget/1.14 (linux-gnu)"
192.168.1.2 - - [23/Feb/2015:14:00:03 +0100] "GET /install/postscripts/cv_install_xcatws HTTP/1.1" 302 243 "http://192.168.1.254/install/postscripts/" "Wget/1.14 (linux-gnu)"

(302 code is a redirect)

offending line seems to arise from yum install mod_ssl

**Comment by themisa** [comment]
Removed from master, /install/postscripts/cv_install_xcatws

**Comment by themisa** [comment]
Verified fixed in 26af0dd  (and by removing from master cv_install_xcatws)
