### ISSUE TITLE
cv_install_openstack: xCAT package not found

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#72]
**Software:** Trinity
**Component:** r3 26af0dd
**Hardware:** controller01 /IBM poweredge
**Test case:** general
**Bug description:**
the postscripts of the image centos7.0-x86_64-install-openstack include running the cv_install_xcat, and cv_install_docker. xCAT cannot get installed - packages missing or not copied over from master?
**Steps to reproduce:**
nodeset controller01 osimage=centos7.0-x86_64-install-openstack
rpower controller01 reset
cat /var/log/xcat/xcat.log | grep -i "xcat" --> no xCAT package found

Even though postinstall.log reports xcat installed, it is not (package not copied in yum repos)

**Expected output:**
**Actual output:**
No package xCAT available.
/xcatpost
./cv_install_xcat: line 49: /etc/profile.d/xcat.sh: No such file or directory
ls: cannot access /tmp/trinity/xcat/tables: No such file or directory
./cv_install_xcat: line 56: restorexCATdb: command not found
./cv_install_xcat: line 59: cd: /opt/xcat/share/xcat/netboot/centos: No such file or directory
./cv_install_xcat: line 64: patch: command not found
cat: /tmp/trinity/xcat/patches/*.patch: No such file or directory
./cv_install_xcat: line 65: makedhcp: command not found
./cv_install_xcat: line 66: makedns: command not found
./cv_install_xcat: line 112: copycds: command not found
./cv_install_xcat: line 114: genimage: command not found

**Comment by hansthen** [comment]
That configuration is wrong. Cause of the problem is the postscripts table:
"controllers",,"cv_install_slapd,cv_install_xcat,cv_install_docker",,

However, we should not install this for the group controllers, but only for the right osimage. Those tables are not yet in github (but they should be). Will do a quick fix for now.

**Comment by hansthen** [comment]
In the osimage table

"centos7.0-x86_64-install-controller",,"controller","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,"cv_install_slapd,cv_install_xcat,cv_install_docker",,,,,
"centos7.0-x86_64-install-openstack",,"openstack","linux",,"install",,"centos7.0-x86_64",,,"Linux","centos7.0","x86_64",,,"cv_install_openstack",,,,,

**Comment by themisa** [comment]
Fixed in aa36e942c . Now openstack image only postinstalls ldap. 

[root@newmaster ~]# lsdef -t osimage -o centos7.0-x86_64-install-openstack
Object name: centos7.0-x86_64-install-openstack
    imagetype=linux
    osarch=x86_64
    osdistroname=centos7.0-x86_64
    osname=Linux
    osvers=centos7.0
    otherpkgdir=/install/post/otherpkgs/centos7.0/x86_64
    pkgdir=/install/centos7.0/x86_64
    pkglist=/install/custom/install/centos/openstack.pkglist
    postbootscripts=cv_install_slapd,cv_install_openstack
    profile=openstack
    provmethod=install
    template=/install/custom/install/centos/openstack.tmpl
