### ISSUE TITLE
dell poweredge: BIOS disabled virtualization

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#73]
**Software:** trinity
**Component:** r3
**Hardware:**controller02-Poweredge
**Test case:** openstack
**Bug description:**
Cannot launch instances, since virtualization is disabled on the Dell poweredge.
**Steps to reproduce:**

**Expected output:**
**Actual output:**

**Comment by abhimukh** [comment]
Enabled virtualization on the node. Now, one can ping/ssh the instances.

**Comment by themisa** [comment]
Confirmed fix. closing
