### ISSUE TITLE
controller installation: xcat errors, failures and warnings

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#74]
*Note: this is a placeholder that may spawn a few more issues*

**Software:** Trinity r3  cb242d7
**Component:** controller installation
**Hardware:** controller02 (SM)
**Test case:** 1.1
**Bug description:** There seem to be errors/warnings during the xcat installation that may/may not affect downstream steps in the installation/use of Trinity. Documenting here for completeness, further investigation
**Steps to reproduce:**
> nodeset controllerXX osimage=centos7.0-x86_64-install-controller

After installation + postinstall scripts are done, examine xcat log file

> cat /var/log/xcat/xcat.log | grep -i 'warning\|error\|fail'

**Expected output:**
**Actual output:**

[root@controller install]# cat /var/log/xcat/xcat.log | grep -i 'warning\ |error\ |fail'
warning: /var/cache/yum/x86_64/7/xcat-dep/packages/conserver-xcat-8.1.16-10.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
warning: /var/cache/yum/x86_64/7/xcat-2-core/packages/perl-xCAT-2.8.5-snap201409010228.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID da736c68: NOKEY
Hostname resolution for controller.cluster failed, setting the site.master to NORESOLUTION for now, after the xCAT installation is finished, fix this hostname resolution problem, change the site.master to the correct value and then resart xcatd.
Warning: No 10.141.0.0 specific entry for domain, and no domain defined in site table.
Warning: No dynamic range specified for 10.141.0.0. If hardware discovery is being used, a dynamic range is required.
Warning: No 192.168.1.0 specific entry for domain, and no domain defined in site table.
Warning: No dynamic range specified for 192.168.1.0. If hardware discovery is being used, a dynamic range is required.
Error: domain not defined in site table
warning: /var/cache/yum/x86_64/7/base/packages/iptables-services-1.4.21-13.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
--> Processing Dependency: libgpg-error.so.0()(64bit) for package: systemd-libs-208-11.el7.x86_64
---> Package libgpg-error.x86_64 0:1.12-3.el7 will be installed
 libgpg-error            x86_64 1.12-3.el7             centos7.0-x86_64-0  87 k
  Installing : libgpg-error-1.12-3.el7.x86_64                            44/321 
dracut-install: ERROR: installing 'lspci'
dracut-install: ERROR: installing 'setpci'
  Verifying  : libgpg-error-1.12-3.el7.x86_64                           205/321 
  libgpg-error.x86_64 0:1.12-3.el7                                              
error reading information on service docker: No such file or directory
error reading information on service openvswitch: No such file or directory
Failed to install module mlx_en
Failed to install module mlx_en
warning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-5.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
warning: /var/cache/yum/x86_64/7/epel/packages/munge-0.5.11-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
    warning: no previously-included files matching '*' found under directory 'docs/.build'
    warning: no previously-included files matching '*' found under directory 'docs/.build'

**Comment by hansthen** [comment]
One important error (cause) is that the xCAT tables on controller were not properly configured. As a quick check you can do the following.

    [root@controller ~]# tabdump site
    #key,value,comments,disable
    "domain","cluster",,
    "installdir","/install",,
    "master","10.141.255.254",,
    "forwarders","8.8.8.8,8.8.4.4",,
    "nameservers","<xcatmaster>",,
    "tftpdir","/tftpboot",,
    "xcatdport","3001",,
    "xcatiport","3002",,
    "xcatconfdir","/etc/xcat",,
    "timezone","Europe/Amsterdam",,
    "dhcpinterfaces","eno2",,

**Comment by hansthen** [comment]
But don't make these type of generic errors, as they will never be closed again.

**Comment by hansthen** [comment]
[root@controller ~]# grep -i 'warning|error|fail' /var/log/xcat/xcat.log 
    [root@controller ~]# 

(I also had to fix some other stuff for this to work.)

**Comment by hansthen** [comment]
Assigned to Themis for testing.

**Comment by themisa** [comment]
I will close for now. 
The only "error" remaining i see as of version ee93d17
is:
dracut-install: ERROR: installing 'lspci'
dracut-install: ERROR: installing 'setpci'

But:
[root@controller ~]# which setpci
/usr/sbin/setpci
[root@controller ~]# which lspci
/usr/sbin/lspci
[root@controller ~]# 

those utilities exist.
