### ISSUE TITLE
Controller installation: error message during generation of the trinity image

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#75]
error reading information on service docker: No such file or directory
error reading information on service openvswitch: No such file or directory

This will cause the trinity images do run without docker (and openvswitch), which will cause downstream failures (in use case 1.2).

**Comment by hansthen** [comment]
The otherpackages was not entered in the linuximage table.
reposync was not installed on the controller.

**Comment by hansthen** [comment]
* r3
ee93d17

**Comment by themisa** [comment]
* r3
f0e04dd
fixed
