### ISSUE TITLE
trinity version: file has extra lines

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#76]
**Software:** Trinity 264206d
**Component:** /trinity/version
**Hardware:** 
**Test case:** general
**Bug description:**
The file that stores the version has extra lines
**Steps to reproduce:**
cat /trinity/version
**Expected output:**
* r3 
264206d

**Actual output:**
* r3
264206d
 M master/rootimg/install/postscripts/cv_install_xcat

**Comment by hansthen** [comment]
This was done on purpose. The extra lines show that the repository is not clean. This means that we can check something, before actually doing a commit. It also means that if you accidentally test something against a version that is not committed to the repo, you will be able to see it,

**Comment by themisa** [comment]
ok.
