### ISSUE TITLE
long reads

### ISSUE THREAD

**Issue by JahnDavik** [clustervision/trinity#779]
Hi,
I would like to inquire about the --long_reads option in trinity. I have pacbio reads of my beast (and RNAseq reads) and thought that I'd wait for me having a draft genome pacbio based assembly ready and then do genome guided rnaseq assembly. That makes sense to me. But then I may miss something here? Are there good reasons for using the long reads instead of the assembly?
Thank you.
Jahn

**Comment by jflf-CV** [comment]
Hi Jahn,

I think that you have the wrong Trinity! Our Trinity is a cluster management software for high-performance computing. If you want to buy a cluster to speed up your bioinformatics workflow, then by all means feel free to talk to us: http://clustervision.com/ :)

My best guess is that you are looking for that one:
https://github.com/trinityrnaseq/trinityrnaseq/wiki

Thank you and best regards,
JF

**Comment by JahnDavik** [comment]
Sorry.
jahn
