### ISSUE TITLE
controller: no python-pip available

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#78]
**Software:** Trinity ee93d17
**Component:** controller installation
**Hardware:** SM, controller02
**Test case:** 1.1.16
**Bug description:**
No python-pip on controller, needed for installation of trinity specific scripts
**Steps to reproduce:**
[root@controller xcatpost]# sh cv_install_api
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.amsiohosting.net
 * centosplus: mirror.nl.leaseweb.net
 * extras: mirror.nl.leaseweb.net
 * updates: centos.mirror.transip.nl
Package redhat-lsb-4.1-24.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.supportex.net
 * centosplus: centos.mirror.transip.nl
 * extras: mirrors.supportex.net
 * updates: mirror.nl.webzilla.com
No package python-pip available.
Error: Nothing to do

**Actual output:**

[root@controller xcatpost]# sh cv_install_api
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.amsiohosting.net
 * centosplus: mirror.nl.leaseweb.net
 * extras: mirror.nl.leaseweb.net
 * updates: centos.mirror.transip.nl
Package redhat-lsb-4.1-24.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.supportex.net
 * centosplus: centos.mirror.transip.nl
 * extras: mirrors.supportex.net
 * updates: mirror.nl.webzilla.com
No package python-pip available.
Error: Nothing to do

**Comment by brunopereira81** [comment]
python-pip comes from the EPEL repo, if that repo is not enable - or even
setup - this package will not be available.

**Comment by themisa** [comment]
Installed:
  python-pip.noarch 0:1.5.6-5.el7 

in version: * r3
f0e04dd
