### ISSUE TITLE
Problem obol ldappassword

### ISSUE THREAD

**Issue by tjdm007** [clustervision/trinity#780]
180098 09:22:55 [root@master ~]# obol user show xxxx
[Error] {'desc': 'Invalid credentials'}

**Comment by tjdm007** [comment]
ldappasswd -v -x -H ldaps://master.cluster -D "cn=manager,dc=local" -y /etc/trinity/passwords/openldap/root.txt -S "uid=xxxx,ou=People,dc=local"

someone could help me. My linux server is CENTOS7.

**Comment by tjdm007** [comment]
More precisions :

CentOs : 7.5.1804
OpenLDAP : 2.4.44
Obol : 2016

**Comment by kostty** [comment]
This issue was routed to the CV customer support and will be closed now.
