### ISSUE TITLE
OpenStack installer: instance cannot access metadata service

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#79]
**Software:**
* r3
aa36e94

**Component:**
cv_install_openstack
**Hardware:**
newmaster/controller02

**Bug description:**
Instances launched by nova (in this case from a centos image) cannot access the metadata server.
This results them in not being able to download the ssh keys. 
**Steps to reproduce:**
 - create ssh key-pair 
 - add public key to the metadata server (via e.g., the dashboard )
 - launch instance
 - ssh to the instance with the corresponding private key (for the centos image the username is 'centos')
 
**Expected output:**
Should be able to ssh to the instance

**Actual output:**
Not able to ssh to the instance.

Output from the console-log of the instance

[[32m  OK  [0m] Started OpenSSH server daemon.
cloud-init[736]: 2015-02-26 12:14:44,290 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [0/120s]: bad status code [400]
[[32m  OK  [0m] Started Postfix Mail Transport Agent.
cloud-init[736]: 2015-02-26 12:14:45,295 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [1/120s]: bad status code [400]

CentOS Linux 7 (Core)
Kernel 3.10.0-123.9.3.el7.x86_64 on an x86_64

test-centos-3 login: cloud-init[736]: 2015-02-26 12:14:46,300 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [2/120s]: bad status code [400]
cloud-init[736]: 2015-02-26 12:14:47,304 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [3/120s]: bad status code [400]
cloud-init[736]: 2015-02-26 12:14:48,308 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [4/120s]: bad status code [400]
...

***Additional Comment***
This problem seems to be fixed by commenting out the line 

service_metadata_proxy=True

in /etc/nova/nova.conf

The above line was added by cv_install_openstack

sed -i "s/^#\?service_metadata_proxy=.*/service_metadata_proxy=True/g" /etc/nova/nova.conf

**Comment by hansthen** [comment]
I think I messed up there. It should be set to False.

**Comment by hansthen** [comment]
Please note this is fixed in the fixes branch.

**Comment by themisa** [comment]
Fixed - was able to passwordless ssh into centos instance (with key-pair injection)

* r3
74c8094

**Comment by themisa** [comment]
needs a nova restart for changes to config file to take effect.

**Comment by themisa** [comment]
fixed in * r3
7cb356e
