### ISSUE TITLE
install cluster: switch not pingable (and nodes not discovered)

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#80]
**Software:** Trinity
**Component:** controller/switch
**Hardware:** r3 testing framework (SM controller02, CISCO switch, SM nodes)
**Test case:** 1.2
**Bug description:**
The switch from xCAT controller (02) is not pingable. Nodes are not discovered
**Steps to reproduce:**
ssh to controller02
ping switch
**Expected output:**
**Actual output:**
[root@controller ~]# ping switch
PING switch (10.141.253.1) 56(84) bytes of data.
From controller (10.141.255.254) icmp_seq=1 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=2 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=3 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=4 Destination Host Unreachable

[root@controller ~]# ping node01
ping: unknown host node01

**Comment by hansthen** [comment]
Switch was misconfigured. I have limited the issue to just the switch.

**Comment by themisa** [comment]
[root@controller ~]# ping switch
PING switch (10.141.253.1) 56(84) bytes of data.
64 bytes from switch (10.141.253.1): icmp_seq=1 ttl=64 time=7.17 ms
64 bytes from switch (10.141.253.1): icmp_seq=2 ttl=64 time=0.900 ms
64 bytes from switch (10.141.253.1): icmp_seq=3 ttl=64 time=0.893 ms
^C
