### ISSUE TITLE
Trinity API: setup.py installs an older version of the API server

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#82]
**Software:**
* r3
22a3d75

**Component:**
Trinity API server

**Hardware:**
master/controller01

**Bug description:**
DistUtils (python setup.py) installs an older version of the API server.

**Steps to reproduce:**
In the trinity_api folder, run
python setup.py install

**Expected output:**
The latest version of the distribution (source code from the src folder and conf files from the conf folder) should get installed
**Actual output:**
An older version gets installed.

**Comment by themisa** [comment]
[root@openstack ~]# diff /usr/lib/python2.7/site-packages/trinity_api/api.py /trinity/api+dash/trinity_api/src/api.py 
[root@openstack ~]# 

[root@openstack ~]# diff /usr/lib/python2.7/site-packages/trinity_client/client.py /trinity/api+dash/trinity_client/src/client.py 
[root@openstack ~]#
