### ISSUE TITLE
There is no license associated with this project

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#83]
Cannot find any license associated with the current releases of this project.

This means that anyone can take this code and use it as their own?

**Comment by hansthen** [comment]
No, without license people are not licensed to use this code. May I suggest that you do not use the repository as a vehicle for questions or remarks on the design? We have an FAQ document and a mail address and design reviews for that.

**Comment by brunopereira81** [comment]
Do not know what you mean with "May I suggest that you do not use the repository as a vehicle for questions or remarks on the design?".

Think you are a bit confused with what this place is all about. From the github description of "issues":

`Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team.`

So I do not see the reason not to use the tools we are provided and are currently using as they where purposely developed for. Sorry if that is not acceptable to you.

From the terms of usage of github:

`We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories.`

Since the repository you are using is a public one and there is no license attached to it, you are not doing anything to protect the code you are producing or preventing forking and further usage by third parties.

From the Trinity FAQ (can not find it else where in the repo, so I am assuming it is just an internal document, not shared with the public) it is stated:

`As a company we believe Open Source is the way to go. Open Source avoids vendor lock in and speeds development. However, we will make money using support contracts.`

What does that even mean? What sort of open-source releases are you doing? Can I just fork the code when I think its stable enough and form my company to support the solution being here developed for more than a year by Clustervision and with Clustervision resources? Are we not being a bit naive here?
If so and that is the intended meaning of that statement, that statement should be added together with any further conditions for usage of this code in a document in the repository somewhere, if not in the readme section, not in a internal document only obtainable in the Clustervision network.

**Comment by hansthen** [comment]
Your concerns are addressed in the FAQ. Since this is more a question of company strategy rather than a technical issue or a feature request, I will not discuss this further on GitHub.

**Comment by brunopereira81** [comment]
"Your concerns are addressed in the FAQ."

Please point them to me, I am curious on where I can find them.

"(..) rather than a technical issue or a feature request."

Hum? Its not my responsibility to decide on what the company will do with this project, nor it is my intention to participate in that discussion. Pointing out that that there is lack of information in a public repository can be done by anyone allowed to read that repository (note: the world). This is a technical issue related to the project, not a matter of deciding or not what will be done with it.

You not wanting to do anything about it is your decision, I was just reporting the lack of information present here.

**Comment by linuxstudio** [comment]
I also cannot find the FAQ that Hans is referring to.

**Comment by hansthen** [comment]
The FAQ is the Trinity FAQ that @brunopereira81 was quoting from. It is a Google Document maintained by Heather. If you have any further questions please refer to her.
