### ISSUE TITLE
Master installer: trinity netbooted images need a cleanly formatted /dev/sda1 for /var/lib/docker

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#84]
Part of the netboot procedure should be the (re-) formatting of the file system for the trinity images. This is a step that comes after discovery, but before the nodeset to the trinity image.

For this we created a script ~/trinity/controller/xcat/discovery/runme.sh. However, this script does not seem to be installed. Also, when running it, it did not seem to work:
nodeset node001 runimage=http://controller:/tftpboot/mkfs.tgz

**Comment by hansthen** [comment]
As a workaround, we can install the compute image and then format the disk.

**Comment by brunopereira81** [comment]
`runimage=http://controller:/tftpboot/mkfs.tgz`

This is a obvious malformed URL, no? Is the file accessible from the controller (or a running node) using wget or similar?

**Comment by brunopereira81** [comment]
You could easily accomplish that using nodeset:

`nodeset node runimage=http://controller/mkfs.tgz,runcmd=disk_setup; rpower node reset`

Should set the node to boot with mkfs.tgz as a root filesystem, reboot the node (if you have any power control that is) and run the command disk_setup once the system is booted.

I think what you are missing in the whole setup is the runcmd statement in your chain.

**Comment by hansthen** [comment]
Workaround: after discovery (when the nodes are running the genesis kernel), do the following (from the controller).
```
psh compute   parted -s /dev/sda mklabel msdos
parted -s --align cylinder /dev/sda mkpart primary ext2 0G 100%
mkfs.ext4 /dev/sda1
```

**Comment by hansthen** [comment]
To test:

Need to do a new master install (including --with-tables).
1. After controller install: check if the /install/runimages/mkfs.tgz file is created.
2. After discovery (in standby mode), login to the nodes: `psh node001 "mkdir -p /var/lib/docker; mount /dev/sda1/ /var/lib/docker; ls /var/lib/docker; umount /var/lib/docker"`

**Comment by themisa** [comment]
[root@controller trinity]# psh node001 "mkdir -p /var/lib/docker; mount /dev/sda1/ /var/lib/docker; ls /var/lib/docker; umount /var/lib/docker"
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /opt/xcat/bin/psh line 56.
node001: lost+found

version:
* r3
4647552

**Comment by hansthen** [comment]
Still needs fixing.

**Comment by themisa** [comment]
[root@controller ~]# psh node001 "mkdir -p /var/lib/docker; mount /dev/sda1/ /var/lib/docker; ls /var/lib/docker; umount /var/lib/docker"
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /opt/xcat/bin/psh line 56.
node001: Warning: Permanently added 'node001,10.141.0.1' (ECDSA) to the list of known hosts.
node001: mount: /dev/sda1 is already mounted or /var/lib/docker busy
node001:        /dev/sda1 is already mounted on /var/lib/docker
node001: containers
node001: devicemapper
node001: execdriver
node001: graph
node001: init
node001: linkgraph.db
node001: lost+found
node001: repositories-devicemapper
node001: tmp
node001: trust
node001: volumes
[root@controller ~]#

**Comment by hansthen** [comment]
-s flag was missing from the first line in the script.

**Comment by themisa** [comment]
[root@controller ~]# psh node001 "mkdir -p /var/lib/docker; mount /dev/sda1/ /var/lib/docker; ls /var/lib/docker; umount /var/lib/docker"
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /opt/xcat/bin/psh line 56.
node001: Warning: Permanently added 'node001,10.141.0.1' (RSA) to the list of known hosts.
node001: lost+found

fixed in 
* r3
ae94b4a
