### ISSUE TITLE
Controller installation: no address defined on BMC network on 2nd ethernet interface.

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#85]
We do not define a second IP address on the eno2 interface for the BMC network.

**Comment by hansthen** [comment]
Workaround:

`ip addr a 141.8.255.254/16 dev eno2`

**Comment by themisa** [comment]
#51 earlier duplicate

**Comment by themisa** [comment]
@hans: test?

**Comment by themisa** [comment]
@hansthen: test?

**Comment by hansthen** [comment]
`ip a` should show an address in the 10.148 range.

**Comment by themisa** [comment]
eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 0c:c4:7a:02:03:4d brd ff:ff:ff:ff:ff:ff
    inet 10.141.255.254/16 brd 10.141.255.255 scope global eno2
