### ISSUE TITLE
Trinity nodes become unreachable (every) morning

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#87]
This morning the Trinity nodes were unreachable. See issue #67 for something similar. However on the Trinity we do not disable NetworkManager, so the issue does not seem to be related.

**Comment by themisa** [comment]
12/3/2015- happened today. Containers reachable but not nodes

**Comment by hansthen** [comment]
Problem was caused by lacking network configuration for eno1. Because of this no dhclient was started for this interface.

This was caused because we left the discoverynic blank, so genimage would not create any network definitions for eno1. Since we use illogical network device naming, we need to hack it. I added a postscript that will create a network configuration for the first ethernet device.

**Comment by themisa** [comment]
* r3
5cead59
fixed up 3 days
