### ISSUE TITLE
API server + Dashboard: HPC_Overview page loads very slowly

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#88]
**Software:**
* r3
22a3d75

**Component:**
API server, dashboard

**Hardware:**
master/controller01

**Bug description:**
The HPC_Overview page on the dashboard (login as admin, under System/HPCPanel/HPC_overview) 
loads very, very slowly.

**Steps to reproduce:**
- Login to the Trinity dashboard as admin
- Click on the following items in order on the accordion navigation on the left : System, HPCPanel, HPC_Overview

**Expected output:**
Overview page loads within a time scale of a few second to a few minutes

**Actual output:**
Overview page takes of the order of several minutes to load

**Comment by abhimukh** [comment]
Committed new changes to the code. Now the rendering should be much faster (few seconds)
 Commit No: ee05e02

**Comment by themisa** [comment]
4 seconds (as opposed to 30 minutes)

* r3
7cb356e

**Comment by abhimukh** [comment]
Trinity API now queries the xCAT db during startup and caches the data in memory. Thereafter it queries the xCAT db only during writes (repartitioning).
