### ISSUE TITLE
controller: makedns doesn't work as expected

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#89]
**Software:** Trinity * r3
f0e04dd
**Component:** controller installation
**Hardware:** controller02, SM
**Test case:** 1.1.11
**Bug description:**
makedns gives errors,
**Steps to reproduce:**
makedns xcat
**Expected output:**
**Actual output:**
[root@controller compute]# makedns xcat
Handling switch in /etc/hosts.
Handling controller in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Error: No reply received when sending DNS update to zone cluster.
Error: No reply received when sending DNS update to zone 141.10.IN-ADDR.ARPA.
Completed updating DNS records.
[root@controller compute]# ^C
[root@controller compute]# host switch
Host switch not found: 3(NXDOMAIN)

**Comment by hansthen** [comment]
0c2b95c failed. 
Workaround: `service xcatd restart; makedns -n`
To verify `cat /etc/named.conf`
And `host controller localhost`.

**Comment by hansthen** [comment]
74c8094 Should be fixed now.

**Comment by themisa** [comment]
fixed
