### ISSUE TITLE
Master setup needs to have an automated update from the ~/trinity repository

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#9]
The master relies on files from the trinity repository. However, copying files from the trinity repo to the appropriate locations on the master is somewhat error prone. We need to find a way to make this easier.

**Comment by hansthen** [comment]
Is fixed in the r3 branch (after master_installer) was merged into it. Go into ~/trinity/master and run update_master.sh. If you also want to restore the table definitions from the repo do: update_master.sh --with-tables.

**Comment by themisa** [comment]
Fixed. update_master works
