### ISSUE TITLE
controller:no /cluster/vc-a/etc folder

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#93]
**Software:** Trinity * r3
473c4e6

**Component:** controller installation/trinity node
**Hardware:**SM controller02, SM node001/002
**Test case:** n/a at moment
**Bug description:**
There is no /cluster/vc-a/etc folder on the controller, which would be later mapped on /cluster/etc folder
in containers on trinity compute nodes. Needed to host slurm, and munge config files
**Steps to reproduce:**
On a trinity node:
docker-enter trinity
service slurm status

**Expected output:**
**Actual output:**
 service slurm status
Could not find /etc/slurm/slurm.conf. Bad path?

**Comment by hansthen** [comment]
Leads to a bit of a design option. Who will create this folder and structure? We can do it manually for now (as we have done in the past), but it should probably be done by the same script that installs the virtual login node.

**Comment by themisa** [comment]
config files were not automatically copied inside container.

**Comment by hansthen** [comment]
This part is a duplicate of #86.

**Comment by themisa** [comment]
closing for part1 which is fixed.
