### ISSUE TITLE
Master installer: No way to upgrade a controller

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#94]
Currently, there is no way to "upgrade" a controller. A new controller installation does not
1. keep a customer's customization to the /trinity/clustervision and /cluster file system.
2. keep track of new (customer) installed packages
3. keep track of changes into the customer's xCAT database

**Comment by hansthen** [comment]
One way to do this is to make the cv_install_<whatever> scripts idempotent.

**Comment by hansthen** [comment]
I created a script update_controller.sh (analogously to update_master.sh). This will just copy files (it will not do anything to the xCAT tables).

**Comment by themisa** [comment]
Used update_controller. One must yum install git on controller, git clone the trinity repo, cd /trinity/controller then run sh update_controller.
Working.
