### ISSUE TITLE
login node: munge uid/gid different in login nodes than containers

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#95]
The munge id on the virtual login node is different (997) that that in the containers (1000)
Should be created with id 1000.

**Comment by abhimukh** [comment]
UID=1000 is used by the centos user in the Centos cloud image. So, now we create the munge user with uid=1002 on the login node. The same should be done on the Dockerfile for the containers.

**Comment by themisa** [comment]
[root@login etc]# id munge
uid=1002(munge) gid=1002(munge) groups=1002(munge)

[root@c002 /]# id munge
uid=1002(munge) gid=1002(munge) groups=1002(munge)

fixed in 
* r3
7cb356e
