### ISSUE TITLE
LDAP PAM NSS configuration files on the containers should point to "login" as the LDAP server and not to "controller"

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#98]
The URI for the LDAP server in the files pam_ldap.conf, nslcd.conf and ldap.conf in the containers should be : ldap://login and not ldap://controller

**Comment by themisa** [comment]
[root@c002 /]# cat /etc/pam_ldap.conf 
uri ldap://login
base dc=cluster
ssl no
tls_cacertdir /etc/openldap/cacerts
pam_password md5

Fixed in: * r3
ae94b4a
