### ISSUE TITLE
docker0 should be removed from the compute hosts

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#99]
We do not use the docker0 bridge for networking the containers. Also, the bridge serves as a DHCP server with an IP address range of 172.17.0.0/16. This conflicts with our IP allocation scheme for the containers in the virtual clusters.

**Comment by themisa** [comment]
note: disabling bridge docker0 on controller interferes with connection to docker registry

**Comment by themisa** [comment]
[root@node002 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 0c:c4:7a:02:03:60 brd ff:ff:ff:ff:ff:ff
    inet 10.141.0.2/16 brd 10.141.255.255 scope global dynamic eno1
       valid_lft 39198sec preferred_lft 39198sec
    inet6 fe80::ec4:7aff:fe02:360/64 scope link 
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 0c:c4:7a:02:03:61 brd ff:ff:ff:ff:ff:ff
4: eno3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 0c:c4:7a:02:03:62 brd ff:ff:ff:ff:ff:ff
5: eno4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 0c:c4:7a:02:03:63 brd ff:ff:ff:ff:ff:ff

[root@controller ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 0c:c4:7a:02:03:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global dynamic eno1
       valid_lft 30952sec preferred_lft 30952sec
    inet6 fe80::ec4:7aff:fe02:34c/64 scope link 
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 0c:c4:7a:02:03:4d brd ff:ff:ff:ff:ff:ff
    inet 10.141.255.254/16 brd 10.141.255.255 scope global eno2
       valid_lft forever preferred_lft forever
    inet 10.148.255.254/16 brd 10.148.255.255 scope global eno2
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:fe02:34d/64 scope link 
       valid_lft forever preferred_lft forever
4: eno3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 0c:c4:7a:02:03:4e brd ff:ff:ff:ff:ff:ff
5: eno4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 0c:c4:7a:02:03:4f brd ff:ff:ff:ff:ff:ff
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 10.0.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
